import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { getDb as _getDb } from "../db";
import {
  oscalExports,
  ksiDefinitions,
  ksiEvidence,
  ksiControlMappings,
  ksiValidationRuns,
} from "../../drizzle/schema";
import { eq, desc, and, sql, inArray } from "drizzle-orm";
import crypto from "crypto";

async function getDbSafe() {
  const db = await _getDb();
  if (!db) throw new Error("Database not available");
  return db;
}

function generateId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${crypto.randomBytes(4).toString("hex")}`;
}

function generateUUID(): string {
  return crypto.randomUUID();
}

// ─── OSCAL Document Generators ─────────────────────────────────────────────────

interface OscalMetadata {
  title: string;
  lastModified: string;
  version: string;
  oscalVersion: string;
  roles: Array<{ id: string; title: string }>;
  parties: Array<{ uuid: string; type: string; name: string }>;
}

function buildOscalMetadata(title: string): OscalMetadata {
  return {
    title,
    lastModified: new Date().toISOString(),
    version: "1.0.0",
    oscalVersion: "1.1.2",
    roles: [
      { id: "prepared-by", title: "Prepared By" },
      { id: "system-owner", title: "System Owner" },
      { id: "authorizing-official", title: "Authorizing Official" },
    ],
    parties: [
      {
        uuid: generateUUID(),
        type: "organization",
        name: "ACE C3 Platform — Automated Compliance Engine",
      },
    ],
  };
}

/** Generate OSCAL System Security Plan (SSP) */
function generateSSP(
  title: string,
  ksiDefs: any[],
  evidence: any[],
  controlMappings: any[],
  validationRuns: any[]
) {
  const controlImplementations = ksiDefs.map(def => {
    const relatedEvidence = evidence.filter(e => e.ksiId === def.ksiId);
    const relatedMappings = controlMappings.filter(m => m.ksiId === def.ksiId);
    const relatedRuns = validationRuns.filter(r => r.ksiId === def.ksiId);
    const latestRun = relatedRuns[0];

    return {
      uuid: generateUUID(),
      "control-id": def.ksiId,
      description: def.title,
      "by-components": [
        {
          "component-uuid": generateUUID(),
          uuid: generateUUID(),
          description: `ACE C3 Module: ${def.aceC3Module || "N/A"}`,
          "implementation-status": {
            state: def.coverageStatus === "direct" ? "implemented" :
                   def.coverageStatus === "supporting" ? "partially-implemented" :
                   "planned",
          },
          props: [
            { name: "ksi-theme", value: def.themeName },
            { name: "validation-type", value: def.validationType },
            { name: "frequency", value: def.frequency || "TBD" },
            { name: "coverage-status", value: def.coverageStatus },
            { name: "evidence-count", value: String(relatedEvidence.length) },
            ...(latestRun ? [
              { name: "last-validation-status", value: latestRun.status },
              { name: "last-validation-date", value: latestRun.completedAt?.toISOString() || "" },
            ] : []),
          ],
        },
      ],
      "responsible-roles": [{ "role-id": "system-owner" }],
    };
  });

  return {
    "system-security-plan": {
      uuid: generateUUID(),
      metadata: buildOscalMetadata(title),
      "import-profile": {
        href: "https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_MODERATE-baseline_profile.json",
      },
      "system-characteristics": {
        "system-ids": [{ id: generateUUID() }],
        "system-name": title,
        description: "FedRAMP 20x KSI Compliance — Generated by ACE C3",
        "security-sensitivity-level": "moderate",
        "system-information": {
          "information-types": [
            {
              uuid: generateUUID(),
              title: "Cloud Service Offering Security Assessment",
              description: "FedRAMP 20x Key Security Indicator compliance data",
              "confidentiality-impact": { base: "moderate" },
              "integrity-impact": { base: "moderate" },
              "availability-impact": { base: "moderate" },
            },
          ],
        },
        "security-impact-level": {
          "security-objective-confidentiality": "moderate",
          "security-objective-integrity": "moderate",
          "security-objective-availability": "moderate",
        },
        status: { state: "operational" },
        "authorization-boundary": {
          description: "FedRAMP authorized cloud service offering boundary",
        },
      },
      "system-implementation": {
        users: [
          {
            uuid: generateUUID(),
            title: "System Administrator",
            "role-ids": ["system-owner"],
          },
        ],
        components: [
          {
            uuid: generateUUID(),
            type: "software",
            title: "ACE C3 Platform",
            description: "Ace Cyber Campaign Command — Comprehensive penetration testing and FedRAMP compliance platform",
            status: { state: "operational" },
            props: [
              { name: "total-ksis", value: String(ksiDefs.length) },
              { name: "evidence-collected", value: String(evidence.length) },
              { name: "validation-runs", value: String(validationRuns.length) },
            ],
          },
        ],
      },
      "control-implementation": {
        description: "FedRAMP 20x KSI Control Implementation",
        "implemented-requirements": controlImplementations,
      },
    },
  };
}

/** Generate OSCAL Security Assessment Report (SAR) */
function generateSAR(
  title: string,
  ksiDefs: any[],
  evidence: any[],
  validationRuns: any[]
) {
  const findings = ksiDefs.map(def => {
    const relatedEvidence = evidence.filter(e => e.ksiId === def.ksiId);
    const relatedRuns = validationRuns.filter(r => r.ksiId === def.ksiId);
    const latestRun = relatedRuns[0];

    let state = "not-satisfied";
    if (latestRun?.status === "passed") state = "satisfied";
    else if (def.coverageStatus === "direct" && relatedEvidence.length > 0) state = "satisfied";
    else if (def.coverageStatus === "supporting") state = "partially-satisfied";

    return {
      uuid: generateUUID(),
      title: `${def.ksiId}: ${def.title}`,
      description: `Assessment finding for ${def.ksiId}`,
      "target": {
        "type": "objective-id",
        "target-id": def.ksiId,
        status: { state },
      },
      props: [
        { name: "evidence-count", value: String(relatedEvidence.length) },
        { name: "validation-runs", value: String(relatedRuns.length) },
        { name: "coverage-status", value: def.coverageStatus },
      ],
      ...(relatedEvidence.length > 0 ? {
        "related-observations": relatedEvidence.slice(0, 5).map(e => ({
          "observation-uuid": generateUUID(),
        })),
      } : {}),
    };
  });

  const observations = evidence.slice(0, 100).map(e => ({
    uuid: generateUUID(),
    title: e.title,
    description: e.description || `Evidence: ${e.evidenceType} from ${e.sourceModule}`,
    methods: [e.collectionMethod === "automated" ? "EXAMINE" : "INTERVIEW"],
    types: ["finding"],
    "collected": e.createdAt?.toISOString() || new Date().toISOString(),
    props: [
      { name: "ksi-id", value: e.ksiId },
      { name: "evidence-type", value: e.evidenceType },
      { name: "integrity-hash", value: e.integrityHash },
      { name: "source-module", value: e.sourceModule },
    ],
  }));

  return {
    "assessment-results": {
      uuid: generateUUID(),
      metadata: buildOscalMetadata(title),
      "import-ap": {
        href: "#assessment-plan",
      },
      results: [
        {
          uuid: generateUUID(),
          title: "FedRAMP 20x KSI Assessment Results",
          description: "Automated assessment results generated by ACE C3",
          start: new Date().toISOString(),
          findings,
          observations,
          props: [
            { name: "total-ksis-assessed", value: String(ksiDefs.length) },
            { name: "satisfied", value: String(findings.filter(f => f.target.status.state === "satisfied").length) },
            { name: "partially-satisfied", value: String(findings.filter(f => f.target.status.state === "partially-satisfied").length) },
            { name: "not-satisfied", value: String(findings.filter(f => f.target.status.state === "not-satisfied").length) },
          ],
        },
      ],
    },
  };
}

/** Generate OSCAL Plan of Action and Milestones (POA&M) */
function generatePOAM(
  title: string,
  ksiDefs: any[],
  validationRuns: any[]
) {
  const failingKSIs = ksiDefs.filter(def => {
    const runs = validationRuns.filter(r => r.ksiId === def.ksiId);
    const latestRun = runs[0];
    return !latestRun || latestRun.status === "failed" || latestRun.status === "error" || def.coverageStatus === "planned";
  });

  const poamItems = failingKSIs.map((def, idx) => ({
    uuid: generateUUID(),
    title: `${def.ksiId}: ${def.title}`,
    description: `Remediation plan for ${def.ksiId} — ${def.coverageStatus === "planned" ? "Module not yet implemented" : "Validation failed"}`,
    props: [
      { name: "ksi-id", value: def.ksiId },
      { name: "theme", value: def.themeName },
      { name: "priority", value: def.coverageStatus === "planned" ? "high" : "medium" },
      { name: "planned-module", value: def.aceC3Module || "TBD" },
    ],
    origins: [
      {
        actors: [{ type: "tool", "actor-uuid": generateUUID() }],
      },
    ],
    "related-findings": [
      { "finding-uuid": generateUUID() },
    ],
  }));

  return {
    "plan-of-action-and-milestones": {
      uuid: generateUUID(),
      metadata: buildOscalMetadata(title),
      "import-ssp": { href: "#ssp" },
      "poam-items": poamItems,
      props: [
        { name: "total-items", value: String(poamItems.length) },
        { name: "high-priority", value: String(poamItems.filter(p => p.props.find(pp => pp.name === "priority" && pp.value === "high")).length) },
      ],
    },
  };
}

// ─── Router ────────────────────────────────────────────────────────────────────

export const oscalExportRouter = router({
  /** Generate an OSCAL export */
  generate: protectedProcedure
    .input(z.object({
      documentType: z.enum(["ssp", "sar", "poam", "component_definition", "assessment_plan"]),
      title: z.string(),
      description: z.string().optional(),
      engagementId: z.string().optional(),
      ksiScope: z.array(z.string()).optional(),
      outputFormat: z.enum(["json", "xml", "yaml"]).default("json"),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDbSafe();
      const exportId = generateId("OSC");

      // Create the export record
      await db.insert(oscalExports).values({
        exportId,
        documentType: input.documentType,
        title: input.title,
        description: input.description,
        engagementId: input.engagementId,
        ksiScope: input.ksiScope,
        outputFormat: input.outputFormat,
        status: "generating",
        generatedBy: ctx.user?.id,
        generatedByName: ctx.user?.name || "System",
      });

      try {
        // Fetch all needed data
        const ksiDefs = await db.select().from(ksiDefinitions);
        const evidence = await db.select().from(ksiEvidence).orderBy(desc(ksiEvidence.createdAt)).limit(500);
        const controlMappings = await db.select().from(ksiControlMappings);
        const validationRuns = await db.select().from(ksiValidationRuns).orderBy(desc(ksiValidationRuns.createdAt)).limit(500);

        // Filter by scope if specified
        const scopedDefs = input.ksiScope && input.ksiScope.length > 0
          ? ksiDefs.filter(d => input.ksiScope!.includes(d.ksiId) || input.ksiScope!.includes(d.themeCode))
          : ksiDefs;

        let oscalDocument: any;

        switch (input.documentType) {
          case "ssp":
            oscalDocument = generateSSP(input.title, scopedDefs, evidence, controlMappings, validationRuns);
            break;
          case "sar":
            oscalDocument = generateSAR(input.title, scopedDefs, evidence, validationRuns);
            break;
          case "poam":
            oscalDocument = generatePOAM(input.title, scopedDefs, validationRuns);
            break;
          default:
            oscalDocument = generateSSP(input.title, scopedDefs, evidence, controlMappings, validationRuns);
        }

        const outputJson = JSON.stringify(oscalDocument, null, 2);
        const outputHash = crypto.createHash("sha256").update(outputJson).digest("hex");

        // Update export record with completed status
        await db.update(oscalExports)
          .set({
            status: "complete",
            outputHash,
            completedAt: new Date(),
            metadata: {
              ksiCount: scopedDefs.length,
              evidenceCount: evidence.length,
              validationRunCount: validationRuns.length,
              documentSize: outputJson.length,
            },
          })
          .where(eq(oscalExports.exportId, exportId));

        return {
          exportId,
          documentType: input.documentType,
          outputHash,
          document: oscalDocument,
          documentSize: outputJson.length,
        };
      } catch (error: any) {
        await db.update(oscalExports)
          .set({
            status: "failed",
            errorMessage: error.message,
          })
          .where(eq(oscalExports.exportId, exportId));

        throw error;
      }
    }),

  /** List all OSCAL exports */
  listExports: protectedProcedure
    .input(z.object({
      documentType: z.enum(["ssp", "sar", "poam", "component_definition", "assessment_plan"]).optional(),
      status: z.enum(["pending", "generating", "complete", "failed"]).optional(),
      limit: z.number().min(1).max(100).default(20),
    }).optional())
    .query(async ({ input }) => {
      const db = await getDbSafe();
      const conditions = [];
      if (input?.documentType) conditions.push(eq(oscalExports.documentType, input.documentType));
      if (input?.status) conditions.push(eq(oscalExports.status, input.status));

      let query = db.select().from(oscalExports);
      if (conditions.length > 0) {
        query = query.where(and(...conditions)) as any;
      }
      return (query as any).orderBy(desc(oscalExports.createdAt)).limit(input?.limit || 20);
    }),

  /** Get a specific OSCAL export */
  getExport: protectedProcedure
    .input(z.object({ exportId: z.string() }))
    .query(async ({ input }) => {
      const db = await getDbSafe();
      const result = await db.select().from(oscalExports).where(eq(oscalExports.exportId, input.exportId));
      return result[0] || null;
    }),

  /** Get OSCAL export summary statistics */
  getStats: protectedProcedure.query(async () => {
    const db = await getDbSafe();
    const total = await db.select({ count: sql<number>`count(*)` }).from(oscalExports);
    const byType = await db.select({
      type: oscalExports.documentType,
      count: sql<number>`count(*)`,
    }).from(oscalExports).groupBy(oscalExports.documentType);
    const byStatus = await db.select({
      status: oscalExports.status,
      count: sql<number>`count(*)`,
    }).from(oscalExports).groupBy(oscalExports.status);

    return {
      totalExports: total[0]?.count || 0,
      byType,
      byStatus,
    };
  }),

  /** Get supported document types */
  getDocumentTypes: protectedProcedure.query(() => {
    return [
      { id: "ssp", name: "System Security Plan (SSP)", description: "Comprehensive security plan documenting KSI implementations and evidence" },
      { id: "sar", name: "Security Assessment Report (SAR)", description: "Assessment findings with evidence observations and satisfaction status" },
      { id: "poam", name: "Plan of Action & Milestones (POA&M)", description: "Remediation plan for failing or unimplemented KSIs" },
      { id: "component_definition", name: "Component Definition", description: "ACE C3 component capabilities mapped to KSI requirements" },
      { id: "assessment_plan", name: "Assessment Plan", description: "Planned assessment activities and validation schedules" },
    ];
  }),
});
