// ─────────────────────────────────────────────────────────────────────────────
// Submission History Router
// ─────────────────────────────────────────────────────────────────────────────
// Persists generated/exported/rejected bounty submissions for trend analysis
// and program-level win-rate tracking.
//
// Author: Harrison Cook — AceofCloud (https://aceofcloud.com)
// ─────────────────────────────────────────────────────────────────────────────

import { z } from "zod";
import { router, protectedProcedure } from "../_core/trpc";
import { submissionHistory } from "../../drizzle/schema";
import { eq, and, desc, sql, count } from "drizzle-orm";
import { TRPCError } from "@trpc/server";

const statusEnum = z.enum(['draft', 'exported', 'submitted', 'accepted', 'rejected', 'duplicate', 'informative', 'not_applicable']);
const severityEnum = z.enum(['critical', 'high', 'medium', 'low', 'informational']);

async function requireDb() {
  const { getDb } = await import("../db");
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database unavailable" });
  return db;
}

export const submissionHistoryRouter = router({
  // ── Create a new submission record ──────────────────────────────────────
  create: protectedProcedure
    .input(z.object({
      engagementId: z.number(),
      platform: z.string().min(1).max(64),
      programName: z.string().max(255).optional(),
      vulnClass: z.string().min(1).max(128),
      severity: severityEnum,
      title: z.string().min(1).max(512),
      body: z.string().optional(),
      affectedEndpoint: z.string().max(1024).optional(),
      status: statusEnum.optional().default('draft'),
      sourceHypothesisId: z.string().max(128).optional(),
      confidenceAtGeneration: z.number().min(0).max(1).optional(),
      isAutoGenerated: z.boolean().optional().default(false),
      metadata: z.object({
        cvssScore: z.number().optional(),
        cvssVector: z.string().optional(),
        cweIds: z.array(z.string()).optional(),
        references: z.array(z.string()).optional(),
        stepsToReproduce: z.array(z.string()).optional(),
        impact: z.string().optional(),
        remediation: z.string().optional(),
        tags: z.array(z.string()).optional(),
      }).optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const db = await requireDb();
      const [result] = await db.insert(submissionHistory).values({
        engagementId: input.engagementId,
        userId: ctx.user.id,
        platform: input.platform,
        programName: input.programName,
        vulnClass: input.vulnClass,
        severity: input.severity,
        title: input.title,
        body: input.body,
        affectedEndpoint: input.affectedEndpoint,
        status: input.status,
        sourceHypothesisId: input.sourceHypothesisId,
        confidenceAtGeneration: input.confidenceAtGeneration,
        isAutoGenerated: input.isAutoGenerated ? 1 : 0,
        metadata: input.metadata as any,
      });
      return { id: result.insertId };
    }),

  // ── List submissions with filtering ─────────────────────────────────────
  list: protectedProcedure
    .input(z.object({
      engagementId: z.number().optional(),
      platform: z.string().optional(),
      status: statusEnum.optional(),
      severity: severityEnum.optional(),
      vulnClass: z.string().optional(),
      limit: z.number().min(1).max(100).optional().default(50),
      offset: z.number().min(0).optional().default(0),
    }))
    .query(async ({ input }) => {
      const db = await requireDb();
      const conditions: any[] = [];
      if (input.engagementId) conditions.push(eq(submissionHistory.engagementId, input.engagementId));
      if (input.platform) conditions.push(eq(submissionHistory.platform, input.platform));
      if (input.status) conditions.push(eq(submissionHistory.status, input.status));
      if (input.severity) conditions.push(eq(submissionHistory.severity, input.severity));
      if (input.vulnClass) conditions.push(eq(submissionHistory.vulnClass, input.vulnClass));

      const where = conditions.length > 0 ? and(...conditions) : undefined;

      const [items, [countResult]] = await Promise.all([
        db.select().from(submissionHistory)
          .where(where)
          .orderBy(desc(submissionHistory.createdAt))
          .limit(input.limit)
          .offset(input.offset),
        db.select({ total: count() }).from(submissionHistory).where(where),
      ]);

      return {
        items,
        total: countResult.total,
        hasMore: input.offset + input.limit < countResult.total,
      };
    }),

  // ── Get a single submission by ID ───────────────────────────────────────
  getById: protectedProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const db = await requireDb();
      const [row] = await db.select().from(submissionHistory)
        .where(eq(submissionHistory.id, input.id))
        .limit(1);
      return row || null;
    }),

  // ── Update submission status/content ────────────────────────────────────
  update: protectedProcedure
    .input(z.object({
      id: z.number(),
      title: z.string().max(512).optional(),
      body: z.string().optional(),
      affectedEndpoint: z.string().max(1024).optional(),
      status: statusEnum.optional(),
      severity: severityEnum.optional(),
      platform: z.string().max(64).optional(),
      programName: z.string().max(255).optional(),
      exportFormat: z.string().max(64).optional(),
      metadata: z.object({
        cvssScore: z.number().optional(),
        cvssVector: z.string().optional(),
        cweIds: z.array(z.string()).optional(),
        references: z.array(z.string()).optional(),
        stepsToReproduce: z.array(z.string()).optional(),
        impact: z.string().optional(),
        remediation: z.string().optional(),
        tags: z.array(z.string()).optional(),
      }).optional(),
    }))
    .mutation(async ({ input }) => {
      const db = await requireDb();
      const updates: Record<string, any> = {};
      if (input.title !== undefined) updates.title = input.title;
      if (input.body !== undefined) updates.body = input.body;
      if (input.affectedEndpoint !== undefined) updates.affectedEndpoint = input.affectedEndpoint;
      if (input.status !== undefined) updates.status = input.status;
      if (input.severity !== undefined) updates.severity = input.severity;
      if (input.platform !== undefined) updates.platform = input.platform;
      if (input.programName !== undefined) updates.programName = input.programName;
      if (input.exportFormat !== undefined) updates.exportFormat = input.exportFormat;
      if (input.metadata !== undefined) updates.metadata = input.metadata;

      await db.update(submissionHistory)
        .set(updates)
        .where(eq(submissionHistory.id, input.id));
      return { success: true };
    }),

  // ── Record export event ─────────────────────────────────────────────────
  markExported: protectedProcedure
    .input(z.object({
      id: z.number(),
      exportFormat: z.string().max(64),
    }))
    .mutation(async ({ input }) => {
      const db = await requireDb();
      await db.update(submissionHistory)
        .set({
          status: 'exported',
          exportFormat: input.exportFormat,
          exportedAt: new Date().toISOString(),
        })
        .where(eq(submissionHistory.id, input.id));
      return { success: true };
    }),

  // ── Record submission to platform ───────────────────────────────────────
  markSubmitted: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input }) => {
      const db = await requireDb();
      await db.update(submissionHistory)
        .set({
          status: 'submitted',
          submittedAt: new Date().toISOString(),
        })
        .where(eq(submissionHistory.id, input.id));
      return { success: true };
    }),

  // ── Record outcome (accepted/rejected/duplicate) ────────────────────────
  recordOutcome: protectedProcedure
    .input(z.object({
      id: z.number(),
      status: z.enum(['accepted', 'rejected', 'duplicate', 'informative', 'not_applicable']),
      rejectionReason: z.string().optional(),
      rejectionCategory: z.string().max(128).optional(),
      bountyAmountCents: z.number().optional(),
    }))
    .mutation(async ({ input }) => {
      const db = await requireDb();
      const updates: Record<string, any> = {
        status: input.status,
        outcomeRecordedAt: new Date().toISOString(),
      };
      if (input.rejectionReason) updates.rejectionReason = input.rejectionReason;
      if (input.rejectionCategory) updates.rejectionCategory = input.rejectionCategory;
      if (input.bountyAmountCents !== undefined) updates.bountyAmountCents = input.bountyAmountCents;

      await db.update(submissionHistory)
        .set(updates)
        .where(eq(submissionHistory.id, input.id));
      return { success: true };
    }),

  // ── Delete a submission ─────────────────────────────────────────────────
  delete: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input }) => {
      const db = await requireDb();
      await db.delete(submissionHistory)
        .where(eq(submissionHistory.id, input.id));
      return { success: true };
    }),

  // ── Analytics: Win rate by platform ─────────────────────────────────────
  analytics: protectedProcedure
    .input(z.object({
      engagementId: z.number().optional(),
    }))
    .query(async ({ input }) => {
      const db = await requireDb();
      const conditions: any[] = [];
      if (input.engagementId) conditions.push(eq(submissionHistory.engagementId, input.engagementId));
      const where = conditions.length > 0 ? and(...conditions) : undefined;

      // Overall stats
      const [totalResult] = await db.select({ total: count() })
        .from(submissionHistory).where(where);

      // Status breakdown
      const statusBreakdown = await db.select({
        status: submissionHistory.status,
        count: count(),
      }).from(submissionHistory).where(where).groupBy(submissionHistory.status);

      // Platform breakdown
      const platformBreakdown = await db.select({
        platform: submissionHistory.platform,
        total: count(),
        accepted: sql<number>`SUM(CASE WHEN ${submissionHistory.status} = 'accepted' THEN 1 ELSE 0 END)`,
        rejected: sql<number>`SUM(CASE WHEN ${submissionHistory.status} = 'rejected' THEN 1 ELSE 0 END)`,
        totalBounty: sql<number>`COALESCE(SUM(${submissionHistory.bountyAmountCents}), 0)`,
      }).from(submissionHistory).where(where).groupBy(submissionHistory.platform);

      // Severity breakdown
      const severityBreakdown = await db.select({
        severity: submissionHistory.severity,
        total: count(),
        accepted: sql<number>`SUM(CASE WHEN ${submissionHistory.status} = 'accepted' THEN 1 ELSE 0 END)`,
      }).from(submissionHistory).where(where).groupBy(submissionHistory.severity);

      // Vuln class breakdown (top 10)
      const vulnClassBreakdown = await db.select({
        vulnClass: submissionHistory.vulnClass,
        total: count(),
        accepted: sql<number>`SUM(CASE WHEN ${submissionHistory.status} = 'accepted' THEN 1 ELSE 0 END)`,
        avgConfidence: sql<number>`AVG(${submissionHistory.confidenceAtGeneration})`,
      }).from(submissionHistory).where(where)
        .groupBy(submissionHistory.vulnClass)
        .orderBy(desc(count()))
        .limit(10);

      // Rejection pattern analysis
      const rejectionPatterns = await db.select({
        category: submissionHistory.rejectionCategory,
        count: count(),
      }).from(submissionHistory)
        .where(and(
          eq(submissionHistory.status, 'rejected'),
          ...(input.engagementId ? [eq(submissionHistory.engagementId, input.engagementId)] : []),
        ))
        .groupBy(submissionHistory.rejectionCategory)
        .orderBy(desc(count()))
        .limit(10);

      // Total bounty earned
      const [bountyResult] = await db.select({
        totalBountyCents: sql<number>`COALESCE(SUM(${submissionHistory.bountyAmountCents}), 0)`,
      }).from(submissionHistory).where(and(
        eq(submissionHistory.status, 'accepted'),
        ...(input.engagementId ? [eq(submissionHistory.engagementId, input.engagementId)] : []),
      ));

      const totalSubmissions = totalResult.total;
      const acceptedCount = statusBreakdown.find(s => s.status === 'accepted')?.count || 0;
      const winRate = totalSubmissions > 0 ? (acceptedCount / totalSubmissions * 100) : 0;

      return {
        totalSubmissions,
        winRate: Math.round(winRate * 10) / 10,
        totalBountyEarnedCents: bountyResult.totalBountyCents,
        statusBreakdown: statusBreakdown.map(s => ({ status: s.status, count: s.count })),
        platformBreakdown: platformBreakdown.map(p => ({
          platform: p.platform,
          total: p.total,
          accepted: Number(p.accepted),
          rejected: Number(p.rejected),
          winRate: p.total > 0 ? Math.round(Number(p.accepted) / p.total * 1000) / 10 : 0,
          totalBountyCents: Number(p.totalBounty),
        })),
        severityBreakdown: severityBreakdown.map(s => ({
          severity: s.severity,
          total: s.total,
          accepted: Number(s.accepted),
          winRate: s.total > 0 ? Math.round(Number(s.accepted) / s.total * 1000) / 10 : 0,
        })),
        vulnClassBreakdown: vulnClassBreakdown.map(v => ({
          vulnClass: v.vulnClass,
          total: v.total,
          accepted: Number(v.accepted),
          winRate: v.total > 0 ? Math.round(Number(v.accepted) / v.total * 1000) / 10 : 0,
          avgConfidence: v.avgConfidence ? Math.round(Number(v.avgConfidence) * 100) / 100 : null,
        })),
        rejectionPatterns: rejectionPatterns.map(r => ({
          category: r.category || 'uncategorized',
          count: r.count,
        })),
      };
    }),
});
