CREATE TABLE `engagements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`description` text,
	`engagementType` enum('red_team','phishing','pentest','purple_team','tabletop') NOT NULL DEFAULT 'red_team',
	`status` enum('planning','active','paused','completed','archived') NOT NULL DEFAULT 'planning',
	`startDate` timestamp,
	`endDate` timestamp,
	`targetDomain` varchar(255),
	`targetIpRange` varchar(255),
	`phishingDomain` varchar(255),
	`calderaOperationId` varchar(255),
	`calderaAdversaryId` varchar(255),
	`gophishCampaignId` int,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `engagements_id` PRIMARY KEY(`id`)
);
