CREATE TABLE `domain_recon` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagementId` int NOT NULL,
	`domain` varchar(255) NOT NULL,
	`mxRecords` json,
	`spfRecord` text,
	`dmarcRecord` text,
	`dkimSelector` text,
	`nsRecords` json,
	`aRecords` json,
	`spoofable` boolean DEFAULT false,
	`spoofScore` int DEFAULT 0,
	`spoofAnalysis` text,
	`subdomains` json,
	`whoisData` json,
	`techStack` json,
	`breachData` json,
	`discoveredEmails` json,
	`scanStatus` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`scanStartedAt` timestamp,
	`scanCompletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `domain_recon_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `osint_findings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagementId` int NOT NULL,
	`reconId` int,
	`category` enum('subdomain','email','credential_leak','tech_stack','social_media','dark_web','dns_misconfiguration','certificate','open_port','other') NOT NULL,
	`severity` enum('info','low','medium','high','critical') NOT NULL DEFAULT 'info',
	`title` varchar(512) NOT NULL,
	`description` text,
	`rawData` json,
	`source` varchar(255),
	`campaignRelevance` text,
	`usedInCampaign` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `osint_findings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `typosquat_domains` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagementId` int NOT NULL,
	`reconId` int NOT NULL,
	`originalDomain` varchar(255) NOT NULL,
	`permutedDomain` varchar(255) NOT NULL,
	`permutationType` varchar(64) NOT NULL,
	`isRegistered` boolean DEFAULT false,
	`dnsResolved` boolean DEFAULT false,
	`resolvedIp` varchar(45),
	`mxRecords` json,
	`spoofable` boolean DEFAULT false,
	`status` enum('discovered','recommended','purchased','configured','in_use','transferred','released') NOT NULL DEFAULT 'discovered',
	`registrar` varchar(255),
	`purchaseDate` timestamp,
	`expiryDate` timestamp,
	`annualCost` varchar(32),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `typosquat_domains_id` PRIMARY KEY(`id`)
);
