CREATE TABLE `discovered_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` int NOT NULL,
	`assetId` varchar(128),
	`hostname` varchar(255) NOT NULL,
	`url` text,
	`assetType` varchar(64),
	`dnsRecords` json,
	`dnsStatus` varchar(32),
	`headers` text,
	`technologies` json,
	`assetClasses` json,
	`tags` json,
	`carverScores` json,
	`shockScores` json,
	`missionImpactScore` int,
	`suggestedTier` varchar(32),
	`hybridRiskScore` int,
	`riskBand` varchar(32),
	`cvssEstimate` int,
	`contextIndicators` json,
	`postureFindings` json,
	`testVectors` json,
	`recommendedCalderaAbilities` json,
	`recommendedGophishTemplates` json,
	`recommendedAttackChain` json,
	`confidence` int,
	`confidenceExplanation` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `discovered_assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `domain_intel_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagementId` int,
	`primaryDomain` varchar(255) NOT NULL,
	`additionalDomains` json,
	`clientType` enum('msp','enterprise','saas','paas','iaas','mixed_hosting','other') NOT NULL DEFAULT 'enterprise',
	`sector` varchar(128),
	`criticalFunctions` json,
	`complianceFlags` json,
	`notes` text,
	`orgProfile` json,
	`status` enum('pending','discovering','analyzing','scoring','recommending','completed','failed') NOT NULL DEFAULT 'pending',
	`totalAssets` int DEFAULT 0,
	`totalFindings` int DEFAULT 0,
	`overallRiskScore` int,
	`overallRiskBand` varchar(32),
	`executiveSummary` text,
	`threatModelSummary` text,
	`campaignRecommendations` json,
	`pipelineOutput` json,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `domain_intel_scans_id` PRIMARY KEY(`id`)
);
