CREATE TABLE `engagement_pipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`pipelineName` varchar(255) NOT NULL,
	`pipelineStatus` enum('pending','intel_scan','risk_scoring','campaign_design','caldera_setup','gophish_setup','ready','running','completed','failed') NOT NULL DEFAULT 'pending',
	`targetDomains` json,
	`pipelineClientType` varchar(64),
	`orgProfile` json,
	`intelScanId` int,
	`riskSummary` json,
	`recommendedActors` json,
	`calderaOperationId` varchar(128),
	`calderaAdversaryId` varchar(128),
	`calderaAbilitiesDeployed` int,
	`gophishCampaignId` int,
	`gophishTemplateId` int,
	`gophishLandingPageId` int,
	`engagementId` int,
	`currentStep` int DEFAULT 0,
	`totalSteps` int DEFAULT 6,
	`stepLog` json,
	`errorMessage` text,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `engagement_pipelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ioc_feeds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`feedSource` varchar(64) NOT NULL,
	`feedType` varchar(64) NOT NULL,
	`title` text,
	`description` text,
	`feedSeverity` enum('critical','high','medium','low','info') DEFAULT 'medium',
	`feedIocType` varchar(64),
	`iocValue` text,
	`cveId` varchar(32),
	`vendorProduct` varchar(255),
	`knownRansomware` boolean DEFAULT false,
	`dateAdded` varchar(32),
	`dueDate` varchar(32),
	`linkedActors` json,
	`feedTags` json,
	`rawData` json,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ioc_feeds_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `threat_actor_abilities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorId` varchar(128) NOT NULL,
	`abilityId` varchar(128) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`tactic` varchar(128) NOT NULL,
	`techniqueId` varchar(32) NOT NULL,
	`techniqueName` varchar(255),
	`platforms` json,
	`singleton` boolean DEFAULT false,
	`repeatable` boolean DEFAULT true,
	`requirements` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `threat_actor_abilities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `threat_actor_iocs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorId` varchar(128) NOT NULL,
	`iocType` varchar(64) NOT NULL,
	`value` text NOT NULL,
	`description` text,
	`iocConfidence` enum('high','medium','low') DEFAULT 'medium',
	`iocFirstSeen` varchar(32),
	`iocLastSeen` varchar(32),
	`source` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `threat_actor_iocs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `threat_actors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorId` varchar(128) NOT NULL,
	`name` varchar(255) NOT NULL,
	`aliases` json,
	`actorType` enum('apt','cybercrime','ransomware','hacktivist','unknown') NOT NULL,
	`origin` varchar(128),
	`description` text,
	`motivation` varchar(255),
	`firstSeen` varchar(32),
	`lastActive` varchar(32),
	`threatLevel` enum('critical','high','medium','low') DEFAULT 'medium',
	`sophistication` enum('nation-state','advanced','intermediate','basic') DEFAULT 'intermediate',
	`targetSectors` json,
	`targetRegions` json,
	`techniques` json,
	`tools` json,
	`malware` json,
	`calderaProfile` json,
	`activityTimeline` json,
	`stixId` varchar(128),
	`dataSource` varchar(128),
	`confidence` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `threat_actors_id` PRIMARY KEY(`id`),
	CONSTRAINT `threat_actors_actorId_unique` UNIQUE(`actorId`)
);
