CREATE TABLE `ttp_knowledge` (
	`id` int AUTO_INCREMENT NOT NULL,
	`techniqueId` varchar(32) NOT NULL,
	`techniqueName` varchar(255) NOT NULL,
	`tactic` varchar(128) NOT NULL,
	`description` text,
	`executionMethods` json,
	`toolsUsed` json,
	`iocPatterns` json,
	`artifacts` json,
	`detectionRules` json,
	`eventLogSources` json,
	`calderaAbilities` json,
	`attackChainPosition` varchar(64),
	`prerequisiteTechniques` json,
	`followUpTechniques` json,
	`defensiveGaps` json,
	`redTeamValue` int,
	`blueTeamPriority` int,
	`purpleTeamNotes` text,
	`dataSource` varchar(128),
	`confidence` int,
	`lastEnriched` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ttp_knowledge_id` PRIMARY KEY(`id`),
	CONSTRAINT `ttp_knowledge_techniqueId_unique` UNIQUE(`techniqueId`)
);
