CREATE TABLE `ransomware_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reGroupName` varchar(255) NOT NULL,
	`victimName` varchar(512) NOT NULL,
	`victimUrl` varchar(512),
	`reCountry` varchar(128),
	`reSector` varchar(128),
	`reDescription` text,
	`publishedAt` timestamp,
	`reSource` varchar(128),
	`verified` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ransomware_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ransomware_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupName` varchar(255) NOT NULL,
	`aliases` json,
	`description` text,
	`activityScore` int DEFAULT 0,
	`trend` enum('surging','active','declining','dormant') DEFAULT 'active',
	`rwThreatLevel` enum('critical','high','medium','low') DEFAULT 'medium',
	`victims7d` int DEFAULT 0,
	`victims30d` int DEFAULT 0,
	`totalVictims` int DEFAULT 0,
	`topSectors` json,
	`topCountries` json,
	`associatedMalware` json,
	`mitreTechniques` json,
	`ransomwareFamily` varchar(255),
	`extortionModel` enum('single','double','triple','unknown') DEFAULT 'unknown',
	`affiliateProgram` boolean DEFAULT false,
	`knownInfrastructure` json,
	`notableAttacks` json,
	`rwFirstSeen` varchar(32),
	`rwLastActive` varchar(32),
	`calderaActorId` varchar(128),
	`rwDataSource` varchar(128),
	`rwConfidence` int DEFAULT 75,
	`lastEnriched` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ransomware_groups_id` PRIMARY KEY(`id`),
	CONSTRAINT `ransomware_groups_groupName_unique` UNIQUE(`groupName`)
);
