CREATE TABLE `phishing_drafts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` int,
	`engagementId` int,
	`campaignRecommendationIndex` int,
	`draftStatus` enum('draft','approved','deployed','launched','completed','archived') NOT NULL DEFAULT 'draft',
	`campaignName` varchar(255) NOT NULL,
	`campaignType` varchar(64),
	`draftPriority` enum('critical','high','medium','low') DEFAULT 'medium',
	`targetDomain` varchar(255),
	`targetSector` varchar(128),
	`templateName` varchar(255),
	`templateSubject` varchar(500),
	`templateHtml` text,
	`templateText` text,
	`landingPageName` varchar(255),
	`landingPageHtml` text,
	`landingPageRedirectUrl` varchar(500),
	`captureCredentials` boolean DEFAULT true,
	`capturePasswords` boolean DEFAULT false,
	`targetGroupName` varchar(255),
	`targetEmails` json,
	`smtpProfileName` varchar(255),
	`phishingUrl` varchar(500),
	`attackChain` json,
	`calderaAbilities` json,
	`calderaOperationId` varchar(128),
	`autoTriggerCaldera` boolean DEFAULT false,
	`triggerCondition` json,
	`threatActorId` varchar(128),
	`threatActorName` varchar(255),
	`matchRationale` text,
	`gophishTemplateId` int,
	`gophishPageId` int,
	`gophishGroupId` int,
	`gophishCampaignId` int,
	`launchDate` timestamp,
	`sendByDate` timestamp,
	`campaignStats` json,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `phishing_drafts_id` PRIMARY KEY(`id`)
);
