CREATE TABLE `access_broker_listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brokerId` varchar(128) NOT NULL,
	`brokerName` varchar(255) NOT NULL,
	`aliases` json,
	`listingType` enum('vpn_access','rdp_access','citrix_access','webshell','domain_admin','cloud_access','email_access','database_access','zero_day','exploit_kit','credential_dump','other') NOT NULL DEFAULT 'other',
	`accessType` varchar(128),
	`victimSector` varchar(128),
	`victimCountry` varchar(128),
	`victimRevenue` varchar(64),
	`victimEmployeeCount` varchar(64),
	`askingPrice` varchar(64),
	`currency` varchar(16) DEFAULT 'USD',
	`forumSource` varchar(128),
	`forumPostUrl` text,
	`brokerReputation` enum('established','rising','new','unknown') DEFAULT 'unknown',
	`totalListings` int DEFAULT 0,
	`successfulSales` int DEFAULT 0,
	`activeForums` json,
	`linkedActorIds` json,
	`linkedRansomwareGroups` json,
	`accessLevel` enum('domain_admin','local_admin','user','service_account','unknown') DEFAULT 'unknown',
	`persistenceMechanism` varchar(255),
	`mitreTechniques` json,
	`iabStatus` enum('active','sold','expired','removed','law_enforcement') DEFAULT 'active',
	`iabFirstSeen` varchar(32),
	`iabLastActive` varchar(32),
	`postedAt` timestamp,
	`iabDataSource` varchar(128),
	`iabConfidence` int DEFAULT 75,
	`iabDescription` text,
	`iabRawData` json,
	`iabCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`iabUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `access_broker_listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `info_ops_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ioCampaignId` varchar(128) NOT NULL,
	`ioCampaignName` varchar(255) NOT NULL,
	`ioAliases` json,
	`attributedTo` varchar(255),
	`sponsorState` varchar(128),
	`operatorGroup` varchar(255),
	`ioLinkedActorIds` json,
	`operationType` enum('disinformation','influence','hack_and_leak','astroturfing','election_interference','propaganda','cyber_espionage_io','economic_coercion','diplomatic_pressure','other') NOT NULL DEFAULT 'other',
	`ioStatus` enum('active','disrupted','dormant','attributed','ongoing') DEFAULT 'active',
	`ioTargetCountries` json,
	`targetAudiences` json,
	`ioTargetPlatforms` json,
	`targetNarratives` json,
	`estimatedReach` varchar(128),
	`accountsIdentified` int DEFAULT 0,
	`contentPiecesIdentified` int DEFAULT 0,
	`platformActionsTaken` json,
	`ioTechniques` json,
	`cyberComponent` boolean DEFAULT false,
	`linkedCyberOps` json,
	`ioMitreTechniques` json,
	`primarySource` varchar(255),
	`sourceUrls` json,
	`reportTitle` varchar(512),
	`ioStartDate` varchar(32),
	`ioEndDate` varchar(32),
	`discoveredDate` varchar(32),
	`ioThreatLevel` enum('critical','high','medium','low') DEFAULT 'medium',
	`ioConfidence` int DEFAULT 75,
	`ioDescription` text,
	`ioDataSource` varchar(128),
	`ioLastEnriched` timestamp,
	`ioCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`ioUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `info_ops_campaigns_id` PRIMARY KEY(`id`),
	CONSTRAINT `info_ops_campaigns_ioCampaignId_unique` UNIQUE(`ioCampaignId`)
);
