CREATE TABLE `exploit_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`msfServerId` int NOT NULL,
	`targetIp` varchar(45) NOT NULL,
	`targetPort` int,
	`targetDomain` varchar(255),
	`exploitScanId` int,
	`exploitModule` varchar(512) NOT NULL,
	`payloadModule` varchar(512),
	`exploitCveId` varchar(32),
	`exploitOptions` json,
	`calderaStagerUrl` text,
	`calderaAgentPaw` varchar(64),
	`exploitJobStatus` enum('pending','approved','running','success','failed','aborted','timeout') NOT NULL DEFAULT 'pending',
	`msfJobId` int,
	`msfSessionId` int,
	`sessionType` varchar(32),
	`exploitResult` text,
	`exploitErrorMessage` text,
	`exploitStartedAt` timestamp,
	`exploitCompletedAt` timestamp,
	`approvedBy` varchar(255),
	`approvedAt` timestamp,
	`scopeVerified` boolean DEFAULT false,
	`exploitJobCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`exploitJobUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exploit_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `metasploit_servers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`dropletId` varchar(64),
	`ipAddress` varchar(45),
	`region` varchar(32) DEFAULT 'nyc1',
	`dropletSize` varchar(32) DEFAULT 's-2vcpu-4gb',
	`rpcPort` int DEFAULT 55553,
	`rpcUser` varchar(64) DEFAULT 'msf',
	`rpcPass` text,
	`rpcSsl` boolean DEFAULT true,
	`rpcToken` text,
	`msfStatus` enum('provisioning','installing','online','offline','error','destroying') NOT NULL DEFAULT 'provisioning',
	`msfStatusMessage` text,
	`msfLastHealthCheck` timestamp,
	`msfVersion` varchar(64),
	`moduleCount` int,
	`activeSessionCount` int DEFAULT 0,
	`autoDestroy` boolean DEFAULT false,
	`engagementId` int,
	`msfCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`msfUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `metasploit_servers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `unified_exploit_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`catalogId` varchar(128) NOT NULL,
	`exploitName` varchar(512) NOT NULL,
	`exploitDescription` text,
	`tier` enum('initial_access','post_access') NOT NULL,
	`exploitCategory` varchar(64) NOT NULL,
	`exploitSource` varchar(32) NOT NULL,
	`exploitCveIds` json,
	`exploitCvssScore` double,
	`exploitSeverity` varchar(16),
	`exploitMitreId` varchar(32),
	`exploitMitreName` varchar(255),
	`exploitMitreTactic` varchar(64),
	`exploitPlatform` varchar(64),
	`exploitType` varchar(32),
	`exploitReliability` varchar(16),
	`exploitDifficulty` varchar(16),
	`exploitEffectiveness` int,
	`msfModule` varchar(512),
	`msfRank` int,
	`edbId` varchar(32),
	`edbUrl` varchar(512),
	`phishingExploitId` varchar(64),
	`calderaAbilityId` varchar(128),
	`calderaAbilityPayload` json,
	`calderaSynced` boolean DEFAULT false,
	`calderaSyncedAt` timestamp,
	`agentStagerType` varchar(32),
	`agentStagerCommand` text,
	`agentStagerPayload` text,
	`agentCallbackUrl` text,
	`landingPageCode` text,
	`emailTemplateCode` text,
	`exploitTags` json,
	`exploitDetectionIndicators` json,
	`exploitPrerequisites` json,
	`exploitVerified` boolean DEFAULT false,
	`exploitLastVerifiedAt` timestamp,
	`exploitEnabled` boolean DEFAULT true,
	`exploitAuthor` varchar(255),
	`exploitDatePublished` varchar(32),
	`catalogCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`catalogUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `unified_exploit_catalog_id` PRIMARY KEY(`id`),
	CONSTRAINT `unified_exploit_catalog_catalogId_unique` UNIQUE(`catalogId`)
);
