CREATE TABLE `engagement_shares` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagementId` int NOT NULL,
	`token` varchar(64) NOT NULL,
	`expiresAt` timestamp,
	`accessPassword` varchar(255),
	`maxViews` int,
	`viewCount` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`includeSections` json,
	`includeFindings` boolean NOT NULL DEFAULT true,
	`includeRiskScores` boolean NOT NULL DEFAULT true,
	`includeRecommendations` boolean NOT NULL DEFAULT true,
	`includeExecutiveSummary` boolean NOT NULL DEFAULT true,
	`includeAssets` boolean NOT NULL DEFAULT true,
	`includeCompliance` boolean NOT NULL DEFAULT false,
	`clientName` varchar(255),
	`clientLogo` text,
	`brandingColor` varchar(32),
	`customMessage` text,
	`createdBy` int,
	`lastAccessedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `engagement_shares_id` PRIMARY KEY(`id`),
	CONSTRAINT `engagement_shares_token_unique` UNIQUE(`token`)
);
