CREATE TABLE `ad_domain_connections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ad_environment_id` int,
	`ad_conn_engagement_id` int,
	`connection_name` varchar(255) NOT NULL,
	`server_host` varchar(255) NOT NULL,
	`server_port` int NOT NULL DEFAULT 389,
	`use_tls` boolean DEFAULT false,
	`tls_reject_unauthorized` boolean DEFAULT true,
	`base_dn` varchar(1024) NOT NULL,
	`bind_dn` varchar(1024),
	`encrypted_bind_password` text,
	`bind_password_iv` varchar(64),
	`bind_password_tag` varchar(64),
	`ldap_domain_name` varchar(255) NOT NULL,
	`search_scope` enum('base','one','sub') DEFAULT 'sub',
	`conn_status` enum('connected','disconnected','testing','error') NOT NULL DEFAULT 'disconnected',
	`last_connected_at` timestamp,
	`last_enumeration_at` timestamp,
	`conn_error_message` text,
	`conn_created_by` varchar(255),
	`conn_created_at` timestamp DEFAULT (now()),
	`conn_updated_at` timestamp DEFAULT (now()),
	CONSTRAINT `ad_domain_connections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ad_enumeration_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ad_connection_id` int NOT NULL,
	`ad_enum_environment_id` int,
	`ad_enum_engagement_id` int,
	`ad_enum_status` enum('pending','running','completed','error','partial') NOT NULL DEFAULT 'pending',
	`ad_enum_scope` enum('full','users','groups','computers','gpos','ous','trusts','spns','certificates') DEFAULT 'full',
	`ad_total_users_found` int DEFAULT 0,
	`ad_total_groups_found` int DEFAULT 0,
	`ad_total_computers_found` int DEFAULT 0,
	`ad_total_gpos_found` int DEFAULT 0,
	`ad_total_ous_found` int DEFAULT 0,
	`ad_total_trusts_found` int DEFAULT 0,
	`ad_total_spns_found` int DEFAULT 0,
	`privileged_users_found` int DEFAULT 0,
	`kerberoastable_found` int DEFAULT 0,
	`asrep_roastable_found` int DEFAULT 0,
	`ad_enum_results` json,
	`ad_enum_error_log` json,
	`ad_enum_started_at` timestamp,
	`ad_enum_completed_at` timestamp,
	`ad_enum_created_at` timestamp DEFAULT (now()),
	CONSTRAINT `ad_enumeration_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cloud_credentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider_id` int,
	`engagement_id` int,
	`cred_provider` enum('aws','azure','gcp') NOT NULL,
	`credential_name` varchar(255) NOT NULL,
	`credential_type` enum('aws_access_key','aws_assume_role','aws_session_token','azure_client_secret','azure_managed_identity','azure_cli','gcp_service_account_key','gcp_workload_identity','gcp_oauth') NOT NULL,
	`encrypted_data` text NOT NULL,
	`encryption_iv` varchar(64) NOT NULL,
	`encryption_tag` varchar(64) NOT NULL,
	`cred_account_id` varchar(255),
	`cred_region` varchar(64),
	`role_arn` varchar(512),
	`external_id` varchar(255),
	`tenant_id` varchar(255),
	`subscription_id` varchar(255),
	`project_id` varchar(255),
	`cred_status` enum('active','expired','revoked','testing','error') NOT NULL DEFAULT 'active',
	`last_validated_at` timestamp,
	`last_used_at` timestamp,
	`expires_at` timestamp,
	`cred_created_by` varchar(255),
	`cred_created_at` timestamp DEFAULT (now()),
	`cred_updated_at` timestamp DEFAULT (now()),
	CONSTRAINT `cloud_credentials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cloud_enumeration_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`credential_id` int NOT NULL,
	`enum_provider_id` int,
	`enum_engagement_id` int,
	`enum_provider` enum('aws','azure','gcp') NOT NULL,
	`enum_status` enum('pending','running','completed','error','partial') NOT NULL DEFAULT 'pending',
	`enum_scope` json,
	`total_users_found` int DEFAULT 0,
	`total_roles_found` int DEFAULT 0,
	`total_policies_found` int DEFAULT 0,
	`total_groups_found` int DEFAULT 0,
	`total_service_accounts_found` int DEFAULT 0,
	`total_misconfigs_found` int DEFAULT 0,
	`enum_results` json,
	`enum_error_log` json,
	`enum_started_at` timestamp,
	`enum_completed_at` timestamp,
	`enum_created_at` timestamp DEFAULT (now()),
	CONSTRAINT `cloud_enumeration_runs_id` PRIMARY KEY(`id`)
);
