CREATE TABLE `exploit_ingestion_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eij_source` enum('exploitdb','metasploit','github_poc','nuclei_template','mixed') NOT NULL,
	`eij_query` varchar(512),
	`eij_scope` enum('single_cve','cve_batch','module_path','keyword_search','full_sync') NOT NULL,
	`eij_status` enum('pending','running','completed','partial','failed') NOT NULL DEFAULT 'pending',
	`eij_total_found` int DEFAULT 0,
	`eij_total_ingested` int DEFAULT 0,
	`eij_total_skipped` int DEFAULT 0,
	`eij_total_errors` int DEFAULT 0,
	`eij_error_log` json,
	`eij_script_ids` json,
	`eij_caldera_generated` int DEFAULT 0,
	`eij_triggered_by` varchar(255),
	`eij_started_at` timestamp,
	`eij_completed_at` timestamp,
	`eij_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exploit_ingestion_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exploit_scripts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`es_source_type` enum('exploitdb','metasploit','github_poc','nuclei_template','custom','packetstorm') NOT NULL,
	`es_source_id` varchar(255) NOT NULL,
	`es_source_url` text,
	`es_cve_id` varchar(32),
	`es_additional_cves` json,
	`es_filename` varchar(512) NOT NULL,
	`es_language` enum('ruby','python','c','cpp','perl','bash','powershell','javascript','go','java','yaml','html','php','csharp','other') NOT NULL,
	`es_code` mediumtext NOT NULL,
	`es_code_hash` varchar(64) NOT NULL,
	`es_code_size` int NOT NULL,
	`es_title` varchar(512) NOT NULL,
	`es_description` text,
	`es_author` varchar(255),
	`es_date_published` varchar(32),
	`es_platform` varchar(64),
	`es_architecture` varchar(32),
	`es_exploit_type` varchar(64),
	`es_verified` boolean DEFAULT false,
	`es_reliability` enum('excellent','great','good','normal','average','low','unknown') DEFAULT 'unknown',
	`es_destructive` boolean DEFAULT false,
	`es_requires_auth` boolean DEFAULT false,
	`es_requires_interaction` boolean DEFAULT false,
	`es_mitre_id` varchar(32),
	`es_mitre_tactic` varchar(64),
	`es_mitre_technique` varchar(255),
	`es_caldera_generated` boolean DEFAULT false,
	`es_caldera_ability_yaml` text,
	`es_caldera_executor` varchar(32),
	`es_caldera_command` text,
	`es_caldera_cleanup` text,
	`es_caldera_platform` varchar(32),
	`es_catalog_id` int,
	`es_times_deployed` int DEFAULT 0,
	`es_last_deployed` timestamp,
	`es_success_rate` double,
	`es_tags` json,
	`es_dependencies` json,
	`es_target_products` json,
	`es_ingested_by` varchar(255),
	`es_ingested_at` timestamp NOT NULL DEFAULT (now()),
	`es_last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exploit_scripts_id` PRIMARY KEY(`id`)
);
