CREATE TABLE `apt_ics_mappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`aim_apt_group_name` varchar(255) NOT NULL,
	`aim_aliases` json,
	`aim_attribution` varchar(128),
	`aim_targeted_vendors` json,
	`aim_targeted_protocols` json,
	`aim_targeted_device_types` json,
	`aim_targeted_sectors` json,
	`aim_targeted_countries` json,
	`aim_mitre_attack_ics_techniques` json,
	`aim_mitre_attack_enterprise_techniques` json,
	`aim_malware_tools` json,
	`aim_initial_access_methods` json,
	`aim_known_campaigns` json,
	`aim_threat_level` enum('critical','high','medium','low') DEFAULT 'medium',
	`aim_active_status` enum('active','dormant','disbanded','unknown') DEFAULT 'active',
	`aim_last_known_activity` varchar(255),
	`aim_description` text,
	`aim_references` json,
	`aim_created_at` timestamp NOT NULL DEFAULT (now()),
	`aim_updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `apt_ics_mappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ics_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ica_user_id` int NOT NULL,
	`ica_name` varchar(255) NOT NULL,
	`ica_description` text,
	`ica_target_network` varchar(255),
	`ica_target_sector` varchar(128),
	`ica_devices_discovered` int DEFAULT 0,
	`ica_vulnerabilities_found` int DEFAULT 0,
	`ica_critical_findings` int DEFAULT 0,
	`ica_apt_groups_matched` int DEFAULT 0,
	`ica_overall_risk_score` double,
	`ica_risk_level` enum('critical','high','medium','low') DEFAULT 'medium',
	`ica_protocol_analysis` json,
	`ica_status` enum('pending','running','completed','failed') DEFAULT 'pending',
	`ica_started_at` timestamp,
	`ica_completed_at` timestamp,
	`ica_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ics_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ics_devices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`icd_user_id` int NOT NULL,
	`icd_assessment_id` int,
	`icd_ip_address` varchar(45) NOT NULL,
	`icd_hostname` varchar(255),
	`icd_mac_address` varchar(17),
	`icd_device_type` enum('plc','rtu','hmi','dcs','scada_server','historian','engineering_workstation','safety_system','gateway','switch','sensor','actuator','iot_device','camera','building_automation','medical_device','smart_meter','unknown') NOT NULL DEFAULT 'unknown',
	`icd_vendor` varchar(255),
	`icd_model` varchar(255),
	`icd_firmware_version` varchar(128),
	`icd_serial_number` varchar(128),
	`icd_protocols` json,
	`icd_open_ports` json,
	`icd_purdue_level` enum('level_0','level_1','level_2','level_3','level_3_5','level_4','level_5'),
	`icd_network_segment` varchar(255),
	`icd_facility_name` varchar(255),
	`icd_sector` enum('energy','water','oil_gas','manufacturing','transportation','chemical','nuclear','building_automation','healthcare','food_agriculture','mining','telecom','defense','other'),
	`icd_geolocation` json,
	`icd_criticality` enum('critical','high','medium','low') DEFAULT 'medium',
	`icd_exposed_to_internet` boolean DEFAULT false,
	`icd_has_default_creds` boolean DEFAULT false,
	`icd_has_known_vulns` boolean DEFAULT false,
	`icd_risk_score` double,
	`icd_discovery_source` enum('shodan','censys','nmap','protocol_scan','manual','caldera') DEFAULT 'manual',
	`icd_shodan_data` json,
	`icd_censys_data` json,
	`icd_last_seen` timestamp,
	`icd_created_at` timestamp NOT NULL DEFAULT (now()),
	`icd_updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ics_devices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ics_exploits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ice_cve_id` varchar(20),
	`ice_ics_cert_advisory_id` varchar(30),
	`ice_title` varchar(500) NOT NULL,
	`ice_description` text,
	`ice_affected_vendor` varchar(255),
	`ice_affected_product` varchar(255),
	`ice_affected_versions` json,
	`ice_affected_protocols` json,
	`ice_affected_device_types` json,
	`ice_cvss_score` double,
	`ice_cvss_vector` varchar(128),
	`ice_safety_impact` enum('none','low','medium','high','critical') DEFAULT 'none',
	`ice_availability_impact` enum('none','low','medium','high','critical') DEFAULT 'none',
	`ice_process_integrity_impact` enum('none','low','medium','high','critical') DEFAULT 'none',
	`ice_physical_impact` boolean DEFAULT false,
	`ice_exploit_available` boolean DEFAULT false,
	`ice_exploit_source` varchar(255),
	`ice_exploit_script_id` int,
	`ice_published_date` timestamp,
	`ice_sector` json,
	`ice_references` json,
	`ice_mitigations` text,
	`ice_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ics_exploits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ot_networks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`otn_user_id` int NOT NULL,
	`otn_name` varchar(255) NOT NULL,
	`otn_description` text,
	`otn_cidr` varchar(45),
	`otn_vlan` int,
	`otn_purdue_level` enum('level_0','level_1','level_2','level_3','level_3_5','level_4','level_5'),
	`otn_network_type` enum('process_control','safety','supervisory','dmz','enterprise','field_bus','iot_segment'),
	`otn_parent_network_id` int,
	`otn_connected_network_ids` json,
	`otn_protocol_distribution` json,
	`otn_device_count` int DEFAULT 0,
	`otn_has_firewall` boolean DEFAULT false,
	`otn_has_data_diode` boolean DEFAULT false,
	`otn_has_ids` boolean DEFAULT false,
	`otn_segmentation_score` double,
	`otn_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ot_networks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `protocol_findings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pf_assessment_id` int NOT NULL,
	`pf_device_id` int,
	`pf_protocol` varchar(50) NOT NULL,
	`pf_finding_type` enum('unauthenticated_access','default_credentials','cleartext_protocol','firmware_vulnerability','configuration_weakness','exposed_service','information_disclosure','command_injection','denial_of_service','replay_attack','man_in_the_middle','unauthorized_write','safety_bypass','logic_manipulation','other') NOT NULL,
	`pf_severity` enum('critical','high','medium','low','info') DEFAULT 'medium',
	`pf_title` varchar(500) NOT NULL,
	`pf_description` text,
	`pf_evidence` text,
	`pf_safety_impact` boolean DEFAULT false,
	`pf_process_impact` boolean DEFAULT false,
	`pf_remediation` text,
	`pf_compensating_controls` text,
	`pf_relevant_apt_groups` json,
	`pf_relevant_mitre_techniques` json,
	`pf_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `protocol_findings_id` PRIMARY KEY(`id`)
);
