CREATE TABLE `web_app_findings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scan_id` int NOT NULL,
	`alert_name` varchar(512),
	`severity` varchar(50) DEFAULT 'info',
	`confidence` double DEFAULT 0.5,
	`description` text,
	`solution` text,
	`reference_links` text,
	`cwe_id` int,
	`wasc_id` int,
	`url` varchar(2048),
	`method` varchar(10),
	`param` varchar(512),
	`attack` text,
	`evidence` text,
	`zap_plugin_id` varchar(50),
	`zap_alert_ref` varchar(50),
	`mitre_attack_id` varchar(20),
	`mitre_attack_name` varchar(255),
	`mitre_tactic` varchar(100),
	`exploit_available` boolean DEFAULT false,
	`exploit_module_path` varchar(512),
	`caldera_ability_id` varchar(100),
	`ai_triage_verdict` varchar(50),
	`ai_triage_reason` text,
	`false_positive_score` double,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `web_app_findings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `web_app_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`target_url` varchar(2048) NOT NULL,
	`scan_name` varchar(255),
	`scan_type` varchar(50) NOT NULL DEFAULT 'full',
	`scan_mode` varchar(30) NOT NULL DEFAULT 'passive',
	`status` varchar(50) NOT NULL DEFAULT 'starting',
	`started_by` varchar(255),
	`started_at` timestamp,
	`completed_at` timestamp,
	`zap_spider_scan_id` varchar(100),
	`zap_active_scan_id` varchar(100),
	`zap_ajax_spider_scan_id` varchar(100),
	`spider_progress` int DEFAULT 0,
	`active_scan_progress` int DEFAULT 0,
	`urls_discovered` int DEFAULT 0,
	`total_alerts` int DEFAULT 0,
	`alert_counts` text,
	`error_message` text,
	`detected_tech_stack` text,
	`llm_scan_config` text,
	`scan_policy_name` varchar(100),
	`auth_configured` boolean DEFAULT false,
	`ajax_spider_used` boolean DEFAULT false,
	`attack_chain_id` varchar(100),
	`caldera_operation_id` varchar(100),
	`metasploit_session_id` varchar(100),
	`domain_intel_scan_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `web_app_scans_id` PRIMARY KEY(`id`)
);
