CREATE TABLE `atomic_test_executions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`atomic_test_id` int NOT NULL,
	`guid` varchar(64) NOT NULL,
	`technique_id` varchar(20) NOT NULL,
	`test_name` varchar(512) NOT NULL,
	`executed_by` varchar(64) NOT NULL,
	`target_host` varchar(255),
	`target_platform` varchar(64),
	`status` enum('queued','running','success','failed','blocked','cleanup') NOT NULL DEFAULT 'queued',
	`executor_type` varchar(64),
	`command_executed` text,
	`input_args` text,
	`stdout` text,
	`stderr` text,
	`exit_code` int,
	`detection_triggered` boolean DEFAULT false,
	`detection_details` text,
	`cleanup_ran` boolean DEFAULT false,
	`cleanup_output` text,
	`attack_chain_id` varchar(100),
	`caldera_operation_id` varchar(100),
	`duration_ms` int,
	`started_at` timestamp,
	`completed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `atomic_test_executions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `atomic_tests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`guid` varchar(64) NOT NULL,
	`technique_id` varchar(20) NOT NULL,
	`technique_name` varchar(512) NOT NULL,
	`test_name` varchar(512) NOT NULL,
	`description` text,
	`supported_platforms` varchar(128),
	`executor_type` varchar(64),
	`executor_command` text,
	`cleanup_command` text,
	`elevation_required` boolean DEFAULT false,
	`input_arguments` text,
	`dependencies` text,
	`mitre_tactic` varchar(255),
	`last_synced_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `atomic_tests_id` PRIMARY KEY(`id`),
	CONSTRAINT `atomic_tests_guid_unique` UNIQUE(`guid`)
);
