CREATE TABLE `roe_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int,
	`title` varchar(512) NOT NULL,
	`version` varchar(32) NOT NULL DEFAULT '1.0',
	`status` enum('draft','pending_review','approved','active','completed','archived') NOT NULL DEFAULT 'draft',
	`organization_name` varchar(512),
	`organization_address` text,
	`testing_firm_name` varchar(512),
	`testing_firm_address` text,
	`purpose` text,
	`scope_description` text,
	`assumptions` text,
	`limitations` text,
	`risks` text,
	`test_schedule_start` timestamp,
	`test_schedule_end` timestamp,
	`testing_window_start` varchar(16),
	`testing_window_end` varchar(16),
	`testing_days` json,
	`test_timezone` varchar(64),
	`test_site_locations` json,
	`remote_testing_allowed` boolean DEFAULT true,
	`vpn_required` boolean DEFAULT false,
	`badge_escort_required` boolean DEFAULT false,
	`test_equipment` json,
	`communication_frequency` enum('daily','weekly','bi-weekly','as-needed') DEFAULT 'daily',
	`communication_method` enum('email','phone','secure_portal','encrypted_email') DEFAULT 'secure_portal',
	`status_report_frequency` enum('daily','weekly','milestone-based') DEFAULT 'daily',
	`incident_definition` text,
	`incident_response_procedure` text,
	`emergency_halt_criteria` text,
	`resumption_procedure` text,
	`in_scope_assets` json,
	`out_of_scope_assets` json,
	`in_scope_ip_ranges` json,
	`out_of_scope_ip_ranges` json,
	`in_scope_domains` json,
	`out_of_scope_domains` json,
	`in_scope_applications` json,
	`cloud_environments` json,
	`wireless_networks` json,
	`physical_locations` json,
	`testing_types` json,
	`attack_vectors` json,
	`social_engineering_pretexts` json,
	`dos_testing_allowed` boolean DEFAULT false,
	`physical_testing_allowed` boolean DEFAULT false,
	`wireless_testing_allowed` boolean DEFAULT false,
	`social_engineering_allowed` boolean DEFAULT false,
	`credentialed_testing` boolean DEFAULT false,
	`credential_accounts` json,
	`file_modification_allowed` boolean DEFAULT false,
	`file_installation_allowed` boolean DEFAULT false,
	`pivoting_allowed` boolean DEFAULT true,
	`exfiltration_allowed` boolean DEFAULT false,
	`persistence_allowed` boolean DEFAULT false,
	`shunning_policy` enum('allowed','not_allowed','notify_first') DEFAULT 'notify_first',
	`fedramp_compliant` boolean DEFAULT false,
	`fedramp_attack_vectors` json,
	`fedramp_impact_level` enum('low','moderate','high','not_applicable') DEFAULT 'not_applicable',
	`service_model` enum('iaas','paas','saas','hybrid','not_applicable') DEFAULT 'not_applicable',
	`data_handling_procedure` text,
	`evidence_retention_days` int DEFAULT 90,
	`evidence_encryption_required` boolean DEFAULT true,
	`pii_handling_policy` text,
	`evidence_destruction_method` enum('secure_delete','physical_destruction','crypto_erase') DEFAULT 'secure_delete',
	`report_deliverables` json,
	`report_frequency` enum('daily','weekly','final_only') DEFAULT 'final_only',
	`critical_finding_notification` text,
	`legal_jurisdiction` varchar(256),
	`third_party_agreements` json,
	`liability_waiver` text,
	`nda_required` boolean DEFAULT true,
	`nda_reference` varchar(256),
	`compliance_frameworks` json,
	`created_by` int,
	`approved_by` int,
	`approved_at` timestamp,
	`last_modified_by` int,
	`pdf_url` varchar(1024),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `roe_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roe_personnel` (
	`id` int AUTO_INCREMENT NOT NULL,
	`roe_id` int NOT NULL,
	`role` enum('system_owner','ciso','cio','isso','authorizing_official','trusted_agent','test_lead','test_member','emergency_contact','legal_counsel','third_party_poc','incident_response_lead','customer_poc','project_manager') NOT NULL,
	`name` varchar(256) NOT NULL,
	`title` varchar(256),
	`organization` varchar(256),
	`email` varchar(320),
	`phone` varchar(32),
	`alternate_phone` varchar(32),
	`clearance_level` varchar(64),
	`is_primary` boolean DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `roe_personnel_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `roe_signatures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`roe_id` int NOT NULL,
	`signer_name` varchar(256) NOT NULL,
	`signer_title` varchar(256),
	`signer_organization` varchar(256),
	`signer_role` enum('customer_executive','customer_technical','testing_lead','authorizing_official','legal_counsel') NOT NULL,
	`signed_at` timestamp,
	`signature_data` text,
	`ip_address` varchar(45),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `roe_signatures_id` PRIMARY KEY(`id`)
);
