CREATE TABLE `ksi_control_mappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`control_id` varchar(32) NOT NULL,
	`control_family` varchar(64),
	`control_title` varchar(512),
	`mapping_strength` enum('direct','supporting','partial') NOT NULL DEFAULT 'direct',
	`ace_c3_module` varchar(256),
	`automation_level` enum('full','partial','manual') NOT NULL DEFAULT 'manual',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ksi_control_mappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ksi_definitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`theme_code` varchar(8) NOT NULL,
	`theme_name` varchar(128) NOT NULL,
	`title` varchar(512) NOT NULL,
	`requirement` text,
	`validation_type` enum('machine','human','mixed','tbd') NOT NULL DEFAULT 'tbd',
	`frequency` varchar(64),
	`impact_level` enum('low','moderate','high','all') NOT NULL DEFAULT 'all',
	`sp800_53_controls` json,
	`ace_c3_module` varchar(256),
	`coverage_status` enum('direct','supporting','planned','not_applicable') NOT NULL DEFAULT 'planned',
	`coverage_notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ksi_definitions_id` PRIMARY KEY(`id`),
	CONSTRAINT `ksi_definitions_ksi_id_unique` UNIQUE(`ksi_id`)
);
--> statement-breakpoint
CREATE TABLE `ksi_evidence` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evidence_id` varchar(64) NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`engagement_id` varchar(128),
	`title` varchar(512) NOT NULL,
	`description` text,
	`evidence_type` enum('scan_result','configuration_check','log_entry','screenshot','document','api_response','test_result','attestation','policy_document','training_record','incident_report','audit_log') NOT NULL,
	`source_module` varchar(128) NOT NULL,
	`source_id` varchar(256),
	`collection_method` enum('automated','manual','hybrid') NOT NULL DEFAULT 'automated',
	`raw_data` json,
	`metadata` json,
	`integrity_hash` varchar(128) NOT NULL,
	`previous_hash` varchar(128),
	`hash_algorithm` varchar(16) NOT NULL DEFAULT 'SHA-256',
	`status` enum('collected','verified','validated','expired','rejected') NOT NULL DEFAULT 'collected',
	`validated_by` varchar(256),
	`validated_at` timestamp,
	`expires_at` timestamp,
	`collected_by` int,
	`collected_by_name` varchar(256),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ksi_evidence_id` PRIMARY KEY(`id`),
	CONSTRAINT `ksi_evidence_evidence_id_unique` UNIQUE(`evidence_id`)
);
--> statement-breakpoint
CREATE TABLE `ksi_evidence_chains` (
	`id` int AUTO_INCREMENT NOT NULL,
	`chain_id` varchar(64) NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`engagement_id` varchar(128),
	`name` varchar(256) NOT NULL,
	`description` text,
	`evidence_count` int NOT NULL DEFAULT 0,
	`chain_hash` varchar(128),
	`chain_valid` boolean NOT NULL DEFAULT true,
	`last_verified_at` timestamp,
	`status` enum('active','complete','broken','archived') NOT NULL DEFAULT 'active',
	`created_by` int,
	`created_by_name` varchar(256),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ksi_evidence_chains_id` PRIMARY KEY(`id`),
	CONSTRAINT `ksi_evidence_chains_chain_id_unique` UNIQUE(`chain_id`)
);
--> statement-breakpoint
CREATE TABLE `ksi_validation_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`run_id` varchar(64) NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`engagement_id` varchar(128),
	`validation_type` enum('machine','human','mixed') NOT NULL,
	`trigger_type` enum('scheduled','manual','event_driven') NOT NULL DEFAULT 'scheduled',
	`status` enum('pending','running','passed','failed','warning','error','skipped') NOT NULL DEFAULT 'pending',
	`result` json,
	`score` int,
	`max_score` int,
	`evidence_ids` json,
	`error_message` text,
	`started_at` timestamp,
	`completed_at` timestamp,
	`next_scheduled_at` timestamp,
	`run_by` int,
	`run_by_name` varchar(256),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ksi_validation_runs_id` PRIMARY KEY(`id`),
	CONSTRAINT `ksi_validation_runs_run_id_unique` UNIQUE(`run_id`)
);
--> statement-breakpoint
CREATE TABLE `ksi_validation_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`schedule_id` varchar(64) NOT NULL,
	`ksi_id` varchar(32) NOT NULL,
	`engagement_id` varchar(128),
	`frequency_hours` int NOT NULL,
	`cron_expression` varchar(100),
	`enabled` boolean NOT NULL DEFAULT true,
	`last_run_id` varchar(64),
	`last_run_status` varchar(32),
	`last_run_at` timestamp,
	`next_run_at` timestamp,
	`consecutive_failures` int NOT NULL DEFAULT 0,
	`alert_threshold` int NOT NULL DEFAULT 3,
	`config` json,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ksi_validation_schedules_id` PRIMARY KEY(`id`),
	CONSTRAINT `ksi_validation_schedules_schedule_id_unique` UNIQUE(`schedule_id`)
);
--> statement-breakpoint
CREATE TABLE `oscal_exports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`export_id` varchar(64) NOT NULL,
	`document_type` enum('ssp','sar','poam','component_definition','assessment_plan') NOT NULL,
	`title` varchar(512) NOT NULL,
	`description` text,
	`engagement_id` varchar(128),
	`ksi_scope` json,
	`oscal_version` varchar(16) NOT NULL DEFAULT '1.1.2',
	`status` enum('pending','generating','complete','failed') NOT NULL DEFAULT 'pending',
	`output_format` enum('json','xml','yaml') NOT NULL DEFAULT 'json',
	`output_url` text,
	`output_hash` varchar(128),
	`metadata` json,
	`error_message` text,
	`generated_by` int,
	`generated_by_name` varchar(256),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`completed_at` timestamp,
	CONSTRAINT `oscal_exports_id` PRIMARY KEY(`id`),
	CONSTRAINT `oscal_exports_export_id_unique` UNIQUE(`export_id`)
);
