CREATE TABLE `web_crawl_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` varchar(64) NOT NULL,
	`scanId` int,
	`engagementId` int,
	`targetDomain` varchar(255) NOT NULL,
	`seedUrls` json,
	`maxDepth` int NOT NULL DEFAULT 2,
	`maxPages` int NOT NULL DEFAULT 50,
	`timeoutMs` int NOT NULL DEFAULT 30000,
	`respectRobotsTxt` boolean NOT NULL DEFAULT true,
	`jobStatus` enum('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
	`totalUrlsQueued` int DEFAULT 0,
	`totalUrlsCrawled` int DEFAULT 0,
	`totalUrlsFailed` int DEFAULT 0,
	`totalFindings` int DEFAULT 0,
	`findingSummary` json,
	`technologiesSummary` json,
	`securityGrade` varchar(4),
	`startedBy` varchar(64),
	`startedAt` bigint,
	`completedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `web_crawl_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `web_crawl_jobs_jobId_unique` UNIQUE(`jobId`)
);
--> statement-breakpoint
CREATE TABLE `web_crawl_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` int,
	`assetId` int,
	`engagementId` int,
	`targetUrl` varchar(2048) NOT NULL,
	`finalUrl` varchar(2048),
	`domain` varchar(255) NOT NULL,
	`crawlStatus` enum('queued','crawling','completed','failed','timeout') NOT NULL DEFAULT 'queued',
	`httpStatus` int,
	`responseTimeMs` int,
	`contentType` varchar(128),
	`contentLength` int,
	`depth` int NOT NULL DEFAULT 0,
	`parentCrawlId` int,
	`securityHeaders` json,
	`securityHeaderGrade` varchar(4),
	`detectedTechnologies` json,
	`serverHeader` varchar(255),
	`poweredBy` varchar(255),
	`pageTitle` varchar(512),
	`metaDescription` text,
	`internalLinks` json,
	`externalLinks` json,
	`resourceUrls` json,
	`forms` json,
	`exposedPaths` json,
	`robotsTxt` text,
	`securityTxt` text,
	`sitemapUrls` json,
	`cookies` json,
	`tlsInfo` json,
	`findings` json,
	`findingCounts` json,
	`totalFindings` int DEFAULT 0,
	`rawHeaders` json,
	`crawlConfig` json,
	`crawledBy` varchar(64),
	`startedAt` bigint,
	`completedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `web_crawl_results_id` PRIMARY KEY(`id`)
);
