CREATE TABLE `agent_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentId` varchar(36) NOT NULL,
	`eventType` enum('register','heartbeat','task_assigned','task_sent','task_completed','task_failed','artifact_uploaded','payload_downloaded','paused','resumed','terminated','lost','reconnected','deregistered','approved','rejected') NOT NULL,
	`actorId` int,
	`actorType` enum('operator','system','agent') NOT NULL,
	`details` json,
	`recordHash` varchar(64) NOT NULL,
	`previousHash` varchar(64) NOT NULL,
	`ipAddress` varchar(45),
	`userAgent` varchar(512),
	`createdAt` bigint NOT NULL,
	CONSTRAINT `agent_audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `agent_deployments` (
	`id` varchar(36) NOT NULL,
	`engagementId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`targetPlatform` enum('windows','linux','darwin') NOT NULL,
	`c2Protocol` enum('caldera','sliver','metasploit','native') NOT NULL,
	`agentStatus` enum('pending_approval','approved','deploying','active','paused','lost','completed','terminated','failed') DEFAULT 'pending_approval',
	`publicKey` text,
	`certificateHash` varchar(128),
	`registrationTokenHash` varchar(128),
	`ttlSeconds` int NOT NULL DEFAULT 86400,
	`watchdogSeconds` int NOT NULL DEFAULT 14400,
	`beaconIntervalSeconds` int NOT NULL DEFAULT 60,
	`calderaPaw` varchar(64),
	`sliverImplantId` varchar(64),
	`msfSessionId` varchar(64),
	`targetHostname` varchar(255),
	`targetIp` varchar(45),
	`targetNetwork` varchar(255),
	`agentPlatform` varchar(64),
	`agentArchitecture` varchar(32),
	`agentUsername` varchar(128),
	`agentPrivilege` enum('user','elevated') DEFAULT 'user',
	`agentExecutors` json,
	`agentPid` int,
	`requestedBy` int NOT NULL,
	`approvedBy` int,
	`approvedAt` bigint,
	`rejectionReason` text,
	`deployedAt` bigint,
	`lastHeartbeat` bigint,
	`terminatedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `agent_deployments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `agent_tasks` (
	`id` varchar(36) NOT NULL,
	`agentId` varchar(36) NOT NULL,
	`techniqueId` varchar(32),
	`techniqueName` varchar(255),
	`c2Source` enum('caldera','sliver','metasploit','native') NOT NULL,
	`commandEncrypted` text,
	`executor` varchar(32),
	`timeoutSeconds` int DEFAULT 300,
	`payloadName` varchar(255),
	`taskStatus` enum('queued','sent','executing','completed','failed','timeout','cancelled') DEFAULT 'queued',
	`outputEncrypted` text,
	`stderrEncrypted` text,
	`exitCode` int,
	`pid` int,
	`queuedAt` bigint NOT NULL,
	`sentAt` bigint,
	`startedAt` bigint,
	`completedAt` bigint,
	`assignedBy` int NOT NULL,
	`roeVerified` boolean DEFAULT false,
	CONSTRAINT `agent_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `c2_servers` (
	`id` varchar(36) NOT NULL,
	`name` varchar(255) NOT NULL,
	`c2Type` enum('caldera','sliver','metasploit') NOT NULL,
	`baseUrl` varchar(512) NOT NULL,
	`authConfigEncrypted` text NOT NULL,
	`c2Status` enum('connected','disconnected','error') DEFAULT 'disconnected',
	`lastHealthCheck` bigint,
	`healthDetails` json,
	`version` varchar(64),
	`capabilities` json,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `c2_servers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fips_compliance_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`checkType` enum('tls_cipher','algorithm_usage','key_strength','certificate_validation','provider_status','full_audit') NOT NULL,
	`complianceStatus` enum('compliant','non_compliant','warning') NOT NULL,
	`component` varchar(128) NOT NULL,
	`details` json,
	`opensslVersion` varchar(64),
	`fipsProviderActive` boolean DEFAULT false,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `fips_compliance_records_id` PRIMARY KEY(`id`)
);
