CREATE TABLE `observation_alert_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`obs_alert_id` varchar(128) NOT NULL,
	`obs_alert_rule_id` varchar(128) NOT NULL,
	`obs_alert_rule_name` varchar(255) NOT NULL,
	`obs_alert_trigger_type` varchar(64) NOT NULL,
	`obs_alert_severity` enum('info','low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`obs_alert_title` varchar(512) NOT NULL,
	`obs_alert_message` text NOT NULL,
	`obs_alert_matched_obs` json,
	`obs_alert_matched_signals` json,
	`obs_alert_asset_id` varchar(128),
	`obs_alert_asset_host` varchar(512),
	`obs_alert_details` json,
	`obs_alert_notif_sent` boolean NOT NULL DEFAULT false,
	`obs_alert_notif_result` varchar(255),
	`obs_alert_ack_at` bigint,
	`obs_alert_ack_by` varchar(255),
	`obs_alert_dismissed_at` bigint,
	`obs_alert_triggered_at` bigint NOT NULL,
	CONSTRAINT `observation_alert_history_id` PRIMARY KEY(`id`),
	CONSTRAINT `observation_alert_history_obs_alert_id_unique` UNIQUE(`obs_alert_id`)
);
--> statement-breakpoint
CREATE TABLE `observation_alert_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`obs_rule_id` varchar(128) NOT NULL,
	`obs_rule_name` varchar(255) NOT NULL,
	`obs_rule_description` text,
	`obs_rule_enabled` boolean NOT NULL DEFAULT true,
	`obs_trigger_type` enum('critical_cve','new_open_port','high_severity_signal','risk_score_threshold','observation_count','new_vulnerability','tls_expiry','misconfiguration','custom') NOT NULL,
	`obs_rule_conditions` json NOT NULL,
	`obs_rule_notify_owner` boolean NOT NULL DEFAULT true,
	`obs_rule_cooldown` int NOT NULL DEFAULT 60,
	`obs_rule_last_triggered` bigint,
	`obs_rule_trigger_count` int NOT NULL DEFAULT 0,
	`obs_rule_created_by` varchar(255),
	`obs_rule_created_at` bigint NOT NULL,
	`obs_rule_updated_at` bigint NOT NULL,
	CONSTRAINT `observation_alert_rules_id` PRIMARY KEY(`id`),
	CONSTRAINT `observation_alert_rules_obs_rule_id_unique` UNIQUE(`obs_rule_id`)
);
