CREATE TABLE `ability_graph_edges` (
	`id` int AUTO_INCREMENT NOT NULL,
	`edge_id` varchar(64) NOT NULL,
	`graph_id` varchar(64) NOT NULL,
	`source_node_id` varchar(64) NOT NULL,
	`target_node_id` varchar(64) NOT NULL,
	`condition` varchar(32) NOT NULL DEFAULT 'on_success',
	`condition_expression` text,
	`output_match_pattern` varchar(512),
	`weight` int DEFAULT 1,
	`label` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ability_graph_edges_id` PRIMARY KEY(`id`),
	CONSTRAINT `ability_graph_edges_edge_id_unique` UNIQUE(`edge_id`)
);
--> statement-breakpoint
CREATE TABLE `ability_graph_nodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`node_id` varchar(64) NOT NULL,
	`graph_id` varchar(64) NOT NULL,
	`label` varchar(255) NOT NULL,
	`description` text,
	`technique_id` varchar(32) NOT NULL,
	`technique_name` varchar(255) NOT NULL,
	`tactic` varchar(128) NOT NULL,
	`caldera_ability_id` varchar(128),
	`executor` varchar(32),
	`platform` varchar(32),
	`command` text,
	`cleanup_command` text,
	`payload` text,
	`preconditions` json,
	`exit_criteria` json,
	`safety_tier` varchar(32) NOT NULL DEFAULT 'medium_impact',
	`timeout` int DEFAULT 300,
	`retry_count` int DEFAULT 1,
	`status` varchar(32) NOT NULL DEFAULT 'pending',
	`execution_order` int DEFAULT 0,
	`layer` int DEFAULT 0,
	`execution_result` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ability_graph_nodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `ability_graph_nodes_node_id_unique` UNIQUE(`node_id`)
);
--> statement-breakpoint
CREATE TABLE `ability_graphs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`graph_id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`source_type` varchar(64) NOT NULL,
	`source_id` varchar(128),
	`actor_name` varchar(255),
	`tactics` json,
	`technique_count` int DEFAULT 0,
	`node_count` int DEFAULT 0,
	`edge_count` int DEFAULT 0,
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`safety_tier` varchar(32) NOT NULL DEFAULT 'medium_impact',
	`scan_mode` varchar(32) NOT NULL DEFAULT 'active-standard',
	`execution_id` varchar(128),
	`started_at` timestamp,
	`completed_at` timestamp,
	`nodes_completed` int DEFAULT 0,
	`nodes_failed` int DEFAULT 0,
	`nodes_skipped` int DEFAULT 0,
	`created_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ability_graphs_id` PRIMARY KEY(`id`),
	CONSTRAINT `ability_graphs_graph_id_unique` UNIQUE(`graph_id`)
);
--> statement-breakpoint
ALTER TABLE `ttp_knowledge` ADD `environmentalConstraints` json;--> statement-breakpoint
ALTER TABLE `ttp_knowledge` ADD `expectedTelemetry` json;