CREATE TABLE `chain_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`chain_id` varchar(64) NOT NULL,
	`status` varchar(32) NOT NULL DEFAULT 'pending',
	`progress` int NOT NULL DEFAULT 0,
	`current_stage` varchar(32),
	`cancelled` boolean NOT NULL DEFAULT false,
	`domains` json NOT NULL,
	`seed_ips` json,
	`seed_urls` json,
	`engagement_id` int,
	`operator_id` varchar(64),
	`skip_stages` json,
	`stage_config` json,
	`max_duration_sec` int DEFAULT 3600,
	`continue_on_partial_failure` boolean DEFAULT false,
	`total_findings` int DEFAULT 0,
	`total_subdomains` int DEFAULT 0,
	`total_hosts` int DEFAULT 0,
	`total_open_ports` int DEFAULT 0,
	`total_services` int DEFAULT 0,
	`total_vulnerabilities` int DEFAULT 0,
	`findings_by_severity` json,
	`findings_by_stage` json,
	`stages_completed` int DEFAULT 0,
	`stages_total` int DEFAULT 4,
	`stages_failed` int DEFAULT 0,
	`stages_skipped` int DEFAULT 0,
	`unique_cves` json,
	`attack_techniques` json,
	`started_at` bigint NOT NULL,
	`completed_at` bigint,
	`duration_ms` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chain_runs_id` PRIMARY KEY(`id`),
	CONSTRAINT `chain_runs_chain_id_unique` UNIQUE(`chain_id`)
);
--> statement-breakpoint
CREATE TABLE `chain_stage_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`chain_id` varchar(64) NOT NULL,
	`stage_id` varchar(32) NOT NULL,
	`status` varchar(32) NOT NULL DEFAULT 'pending',
	`input_target_count` int DEFAULT 0,
	`output_count` int DEFAULT 0,
	`finding_count` int DEFAULT 0,
	`errors` json,
	`findings` json,
	`raw_output` mediumtext,
	`started_at` bigint DEFAULT 0,
	`completed_at` bigint,
	`duration_ms` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chain_stage_results_id` PRIMARY KEY(`id`)
);
