CREATE TABLE `carver_risk_cards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`domain` varchar(512) NOT NULL,
	`scan_title` varchar(512),
	`domain_intel_scan_id` int,
	`inferred_sector` varchar(128),
	`sector_confidence` varchar(32),
	`naics_code` varchar(16),
	`naics_label` varchar(256),
	`industry` varchar(256),
	`regulatory_tags` json,
	`country` varchar(8),
	`carver_scores` json,
	`shock_scores` json,
	`hybrid_score` json,
	`priority_tier` varchar(8),
	`confidence_band` varchar(32),
	`top_drivers` json,
	`recommended_actions` json,
	`caldera_ops` json,
	`threat_likelihood` json,
	`fedramp_profile` varchar(32),
	`fips_199_category` json,
	`full_risk_card` json,
	`source` varchar(64) DEFAULT 'manual',
	`batch_id` varchar(128),
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `carver_risk_cards_id` PRIMARY KEY(`id`)
);
