CREATE TABLE `container_image_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registry_id` int NOT NULL,
	`engagement_id` int,
	`user_id` int NOT NULL,
	`repository` varchar(512) NOT NULL,
	`tag` varchar(255) NOT NULL,
	`digest` varchar(128),
	`image_size` bigint,
	`architecture` varchar(32),
	`os` varchar(32),
	`scan_status` enum('queued','pulling','scanning','complete','error') NOT NULL DEFAULT 'queued',
	`total_vulnerabilities` int DEFAULT 0,
	`critical_count` int DEFAULT 0,
	`high_count` int DEFAULT 0,
	`medium_count` int DEFAULT 0,
	`low_count` int DEFAULT 0,
	`negligible_count` int DEFAULT 0,
	`fixed_available` int DEFAULT 0,
	`vulnerabilities` json,
	`packages` json,
	`base_image` varchar(512),
	`layers` json,
	`compliance_issues` json,
	`malware_detected` boolean DEFAULT false,
	`secrets_detected` int DEFAULT 0,
	`scan_duration_ms` int,
	`scan_engine` varchar(64) DEFAULT 'built-in',
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `container_image_scans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `container_registries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`engagement_id` int,
	`registry_type` enum('docker_hub','ecr','acr','gcr','harbor','artifactory','nexus','gitlab','ghcr','quay','custom') NOT NULL,
	`name` varchar(255) NOT NULL,
	`registry_url` varchar(512) NOT NULL,
	`auth_config` text NOT NULL,
	`registry_status` enum('active','inactive','error','pending_validation') NOT NULL DEFAULT 'pending_validation',
	`last_validated` timestamp,
	`last_error` text,
	`repo_count` int DEFAULT 0,
	`image_count` int DEFAULT 0,
	`last_sync_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `container_registries_id` PRIMARY KEY(`id`)
);
