CREATE TABLE `credential_attack_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`target_host` varchar(512) NOT NULL,
	`target_port` int NOT NULL,
	`protocol` varchar(32) NOT NULL,
	`attack_mode` enum('brute_force','password_spray','credential_stuffing','default_credentials','dictionary') NOT NULL,
	`status` enum('running','completed','stopped','error') NOT NULL DEFAULT 'running',
	`total_attempts` int DEFAULT 0,
	`successful_attempts` int DEFAULT 0,
	`lockouts_detected` int DEFAULT 0,
	`rate_limit_hits` int DEFAULT 0,
	`password_list_used` varchar(128),
	`username_list_used` varchar(128),
	`duration_ms` int,
	`config` json,
	`error_message` text,
	`domain_intel_scan_id` int,
	`started_at` timestamp NOT NULL DEFAULT (now()),
	`completed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `credential_attack_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `credential_findings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attack_run_id` int NOT NULL,
	`user_id` int NOT NULL,
	`target_host` varchar(512) NOT NULL,
	`target_port` int NOT NULL,
	`protocol` varchar(32) NOT NULL,
	`username` varchar(256) NOT NULL,
	`password` varchar(256) NOT NULL,
	`is_default` boolean DEFAULT false,
	`vendor` varchar(128),
	`product` varchar(128),
	`access_level` enum('admin','user','read_only','unknown') DEFAULT 'unknown',
	`response_code` int,
	`response_time_ms` int,
	`banner_info` text,
	`verified` boolean DEFAULT false,
	`domain_intel_scan_id` int,
	`notes` text,
	`discovered_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `credential_findings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pentest_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`report_title` varchar(512) NOT NULL,
	`report_type` enum('executive','technical','compliance','full') NOT NULL DEFAULT 'full',
	`classification` enum('CONFIDENTIAL','INTERNAL','PUBLIC') NOT NULL DEFAULT 'CONFIDENTIAL',
	`status` enum('draft','generating','completed','error') NOT NULL DEFAULT 'draft',
	`client_name` varchar(256),
	`engagement_name` varchar(256),
	`tester_name` varchar(256),
	`tester_org` varchar(256),
	`scope_description` text,
	`engagement_start_date` varchar(32),
	`engagement_end_date` varchar(32),
	`domain_intel_scan_ids` json,
	`zap_session_ids` json,
	`credential_attack_run_ids` json,
	`total_findings` int DEFAULT 0,
	`critical_findings` int DEFAULT 0,
	`high_findings` int DEFAULT 0,
	`medium_findings` int DEFAULT 0,
	`low_findings` int DEFAULT 0,
	`info_findings` int DEFAULT 0,
	`credentials_found` int DEFAULT 0,
	`mitre_attack_coverage` json,
	`executive_summary` mediumtext,
	`report_html` mediumtext,
	`generated_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pentest_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `zap_proxy_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`session_name` varchar(256) NOT NULL,
	`target_url` varchar(1024) NOT NULL,
	`status` enum('initializing','active','crawling','scanning','paused','completed','error') NOT NULL DEFAULT 'initializing',
	`proxy_port` int,
	`auth_type` enum('none','form_login','bearer_token','session_cookie','basic_auth') DEFAULT 'none',
	`auth_config` json,
	`waf_evasion_vendor` varchar(64),
	`urls_discovered` int DEFAULT 0,
	`requests_intercepted` int DEFAULT 0,
	`alerts_found` int DEFAULT 0,
	`alerts_critical` int DEFAULT 0,
	`alerts_high` int DEFAULT 0,
	`alerts_medium` int DEFAULT 0,
	`alerts_low` int DEFAULT 0,
	`alerts_info` int DEFAULT 0,
	`scan_progress` int DEFAULT 0,
	`domain_intel_scan_id` int,
	`report_html` mediumtext,
	`started_at` timestamp NOT NULL DEFAULT (now()),
	`completed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `zap_proxy_sessions_id` PRIMARY KEY(`id`)
);
