CREATE TABLE `engagement_timeline_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int NOT NULL,
	`phase` varchar(64) NOT NULL,
	`event_type` enum('phase_started','phase_completed','finding_discovered','exploit_attempted','exploit_succeeded','shell_obtained','credential_found','pivot_established','data_collected','data_exfiltrated','opsec_alert','note_added','handoff_triggered','objective_completed','tool_executed','scan_completed') NOT NULL,
	`severity` enum('info','low','medium','high','critical') DEFAULT 'info',
	`title` varchar(512) NOT NULL,
	`description` text,
	`metadata` json,
	`source_module` varchar(128),
	`source_id` varchar(128),
	`target_host` varchar(256),
	`target_port` int,
	`attack_technique` varchar(64),
	`operator_id` int,
	`timestamp` bigint NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `engagement_timeline_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `engagement_workflow_states` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int NOT NULL,
	`current_phase` enum('pre_engagement','reconnaissance','threat_modeling','vulnerability_analysis','exploitation','post_exploitation','lateral_movement','collection_exfiltration','reporting','completed') NOT NULL DEFAULT 'pre_engagement',
	`phase_progress` json,
	`phase_started_at` json,
	`phase_completed_at` json,
	`auto_handoff_enabled` boolean DEFAULT true,
	`handoff_rules` json,
	`objectives_completed` json,
	`objectives_total` json,
	`overall_progress` int DEFAULT 0,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `engagement_workflow_states_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `exploitation_attempts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int,
	`target_host` varchar(256) NOT NULL,
	`target_port` int,
	`target_service` varchar(128),
	`vulnerability_id` varchar(128),
	`vulnerability_cve` varchar(32),
	`exploit_source` enum('metasploit','nuclei','manual','custom','hydra','netexec','caldera') NOT NULL,
	`exploit_module` varchar(512),
	`exploit_config` json,
	`ea_status` enum('queued','running','succeeded','failed','error','blocked') DEFAULT 'queued',
	`result_type` enum('shell','credential','info_leak','dos','rce','file_access','none'),
	`result_output` mediumtext,
	`shell_obtained` boolean DEFAULT false,
	`ea_shell_type` varchar(64),
	`ea_access_level` enum('none','user','admin','system','root'),
	`ea_evidence` json,
	`ea_attack_technique` varchar(32),
	`match_confidence` int,
	`ea_opsec_risk` int,
	`duration_ms` int,
	`ea_operator_id` int,
	`ea_attempted_at` bigint NOT NULL,
	`ea_completed_at` bigint,
	`ea_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exploitation_attempts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lateral_movement_paths` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int NOT NULL,
	`source_host_id` int NOT NULL,
	`target_ip` varchar(64) NOT NULL,
	`target_hostname` varchar(256),
	`target_port` int,
	`technique` varchar(128) NOT NULL,
	`attack_id` varchar(32),
	`lm_status` enum('planned','attempted','succeeded','failed','blocked') DEFAULT 'planned',
	`credential_used` json,
	`tunnel_config` json,
	`result_output` text,
	`evidence` json,
	`opsec_risk` int,
	`attempted_at` bigint,
	`lm_completed_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lateral_movement_paths_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lolbin_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lolbin_name` varchar(128) NOT NULL,
	`binary_path` varchar(512) NOT NULL,
	`lolbin_os` enum('windows','linux','macos') NOT NULL,
	`lolbin_category` enum('execute','download','upload','copy','compile','encode_decode','reconnaissance','credential_access','persistence','lateral_movement','defense_evasion','exfiltration') NOT NULL,
	`lolbin_description` text NOT NULL,
	`usage_example` text NOT NULL,
	`attack_techniques` json,
	`detection_guidance` text,
	`lolbin_references` json,
	`is_built_in` boolean DEFAULT true,
	`lolbin_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lolbin_catalog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `obtained_shells` (
	`id` int AUTO_INCREMENT NOT NULL,
	`os_engagement_id` int,
	`exploit_attempt_id` int,
	`os_pivot_host_id` int,
	`os_target_host` varchar(256) NOT NULL,
	`os_target_port` int,
	`os_shell_type` enum('reverse_tcp','bind_tcp','web_shell','ssh','rdp','winrm','agent','other') NOT NULL,
	`os_access_level` enum('user','admin','system','root') DEFAULT 'user',
	`os_username` varchar(128),
	`os_c2_framework` varchar(64),
	`os_session_id` varchar(128),
	`callback_ip` varchar(64),
	`callback_port` int,
	`is_alive` boolean DEFAULT true,
	`promoted_to_pivot` boolean DEFAULT false,
	`os_notes` text,
	`os_obtained_at` bigint NOT NULL,
	`os_last_checked_at` bigint,
	`os_created_at` timestamp NOT NULL DEFAULT (now()),
	`os_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `obtained_shells_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opsec_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`opsec_engagement_id` int NOT NULL,
	`opsec_action_type` varchar(128) NOT NULL,
	`opsec_action_description` text NOT NULL,
	`risk_score` int NOT NULL,
	`detection_probability` int,
	`triggers_siem_rules` json,
	`triggers_edr_alerts` json,
	`network_noise` enum('silent','low','moderate','loud','very_loud') DEFAULT 'moderate',
	`opsec_source_host` varchar(256),
	`opsec_target_host` varchar(256),
	`opsec_protocol` varchar(32),
	`opsec_attack_technique` varchar(32),
	`safer_alternative` text,
	`was_detected` boolean,
	`detection_details` text,
	`opsec_operator_id` int,
	`opsec_timestamp` bigint NOT NULL,
	`opsec_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `opsec_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opsec_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`opsec_score_engagement_id` int NOT NULL,
	`cumulative_risk` int NOT NULL,
	`current_noise_level` enum('stealth','low','moderate','elevated','critical') DEFAULT 'stealth',
	`opsec_events_count` int DEFAULT 0,
	`high_risk_events_count` int DEFAULT 0,
	`estimated_detection_chance` int DEFAULT 0,
	`infrastructure_health` json,
	`burned_assets` json,
	`opsec_recommendations` json,
	`opsec_last_updated_at` bigint NOT NULL,
	`opsec_score_created_at` timestamp NOT NULL DEFAULT (now()),
	`opsec_score_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `opsec_scores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pivot_hosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`engagement_id` int NOT NULL,
	`hostname` varchar(256),
	`ip_address` varchar(64) NOT NULL,
	`os` varchar(128),
	`access_level` enum('user','admin','system','root') DEFAULT 'user',
	`access_method` varchar(128),
	`credentials` json,
	`is_active` boolean DEFAULT true,
	`agent_id` varchar(128),
	`c2_framework` varchar(64),
	`network_interfaces` json,
	`discovered_services` json,
	`notes` text,
	`obtained_at` bigint NOT NULL,
	`last_seen_at` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pivot_hosts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `privesc_findings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pe_engagement_id` int,
	`pe_pivot_host_id` int,
	`pe_target_host` varchar(256) NOT NULL,
	`pe_os` enum('windows','linux','macos','cloud_aws','cloud_azure','cloud_gcp') NOT NULL,
	`check_name` varchar(256) NOT NULL,
	`check_category` enum('kernel_exploit','suid_sgid','cron_jobs','writable_paths','sudo_misconfig','service_misconfig','registry_keys','scheduled_tasks','dll_hijack','token_abuse','uac_bypass','kerberos','ad_delegation','gpo_abuse','certificate_abuse','iam_misconfig','role_assumption','storage_access','metadata_service') NOT NULL,
	`pe_severity` enum('info','low','medium','high','critical') NOT NULL,
	`pe_description` text NOT NULL,
	`exploit_path` text,
	`pe_attack_technique` varchar(32),
	`pe_tool_used` varchar(128),
	`pe_raw_output` mediumtext,
	`is_exploitable` boolean DEFAULT false,
	`was_exploited` boolean DEFAULT false,
	`resulting_access` varchar(64),
	`pe_evidence` json,
	`pe_discovered_at` bigint NOT NULL,
	`pe_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `privesc_findings_id` PRIMARY KEY(`id`)
);
