CREATE TABLE `saml_auth_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saml_event_type` enum('login_success','login_failure','logout','jit_provision','assertion_error','signature_invalid') NOT NULL,
	`saml_event_idp_config_id` int,
	`saml_event_user_id` int,
	`saml_event_name_id` varchar(512),
	`saml_event_ip_address` varchar(45),
	`saml_event_error_details` text,
	`saml_event_assertion_id` varchar(256),
	`saml_event_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `saml_auth_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `saml_idp_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`saml_idp_name` varchar(256) NOT NULL,
	`saml_idp_provider_type` enum('okta','azure_ad','ping_federate','google_workspace','onelogin','generic') NOT NULL DEFAULT 'generic',
	`saml_idp_entity_id` varchar(512) NOT NULL,
	`saml_idp_sso_url` varchar(1024) NOT NULL,
	`saml_idp_slo_url` varchar(1024),
	`saml_idp_certificate` text NOT NULL,
	`saml_idp_metadata_xml` mediumtext,
	`saml_idp_name_id_format` varchar(256) DEFAULT 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
	`saml_idp_attribute_mapping` json,
	`saml_idp_default_role` enum('user','admin','viewer','operator','team_lead','analyst','executive','client') NOT NULL DEFAULT 'operator',
	`saml_idp_is_active` boolean NOT NULL DEFAULT true,
	`saml_idp_jit_provisioning` boolean NOT NULL DEFAULT true,
	`saml_idp_force_authn` boolean NOT NULL DEFAULT false,
	`saml_idp_want_assertions_signed` boolean NOT NULL DEFAULT true,
	`saml_idp_want_response_signed` boolean NOT NULL DEFAULT true,
	`saml_idp_created_by` int,
	`saml_idp_created_at` timestamp NOT NULL DEFAULT (now()),
	`saml_idp_updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `saml_idp_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`session_hash` varchar(64) NOT NULL,
	`session_user_id` int NOT NULL,
	`session_login_method` enum('oauth','saml','api_key') NOT NULL DEFAULT 'oauth',
	`session_saml_idp_id` int,
	`session_device_fingerprint` varchar(64),
	`session_ip_address` varchar(45),
	`session_geo_city` varchar(128),
	`session_geo_region` varchar(128),
	`session_geo_country` varchar(64),
	`session_geo_lat` double,
	`session_geo_lon` double,
	`session_user_agent` text,
	`session_browser_name` varchar(64),
	`session_browser_version` varchar(32),
	`session_os_name` varchar(64),
	`session_os_version` varchar(32),
	`session_device_type` varchar(32),
	`session_is_current` boolean DEFAULT false,
	`session_status` enum('active','expired','revoked') NOT NULL DEFAULT 'active',
	`session_last_activity_at` timestamp NOT NULL DEFAULT (now()),
	`session_expires_at` timestamp NOT NULL,
	`session_created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_sessions_session_hash_unique` UNIQUE(`session_hash`)
);
