ALTER TABLE `activity_logs` ADD `alog_tenant_id` int;--> statement-breakpoint
ALTER TABLE `attack_paths` ADD `atp_tenant_id` int;--> statement-breakpoint
ALTER TABLE `campaigns` ADD `cmp_tenant_id` int;--> statement-breakpoint
ALTER TABLE `chat_sessions` ADD `cs_tenant_id` int;--> statement-breakpoint
ALTER TABLE `credential_exposures` ADD `ce_tenant_id` int;--> statement-breakpoint
ALTER TABLE `defense_scores` ADD `dfs_tenant_id` int;--> statement-breakpoint
ALTER TABLE `discovered_assets` ADD `da_tenant_id` int;--> statement-breakpoint
ALTER TABLE `engagements` ADD `eng_tenant_id` int;--> statement-breakpoint
ALTER TABLE `evasion_sessions` ADD `evs_tenant_id` int;--> statement-breakpoint
ALTER TABLE `evidence_items` ADD `evi_tenant_id` int;--> statement-breakpoint
ALTER TABLE `exploitation_attempts` ADD `expa_tenant_id` int;--> statement-breakpoint
ALTER TABLE `opsec_events` ADD `opse_tenant_id` int;--> statement-breakpoint
ALTER TABLE `pentest_reports` ADD `ptr_tenant_id` int;--> statement-breakpoint
ALTER TABLE `phishing_drafts` ADD `pd_tenant_id` int;--> statement-breakpoint
ALTER TABLE `platform_errors` ADD `perr_tenant_id` int;--> statement-breakpoint
ALTER TABLE `roe_documents` ADD `roe_tenant_id` int;--> statement-breakpoint
ALTER TABLE `scan_observations` ADD `sobs_tenant_id` int;--> statement-breakpoint
ALTER TABLE `scan_policies` ADD `sp_tenant_id` int;--> statement-breakpoint
ALTER TABLE `threat_actors` ADD `ta_tenant_id` int;--> statement-breakpoint
ALTER TABLE `web_app_scans` ADD `was_tenant_id` int;