// Part 2: Additional APT groups, Cybercrime, Ransomware, Hacktivist
import type { SeedThreatActor } from "./threatActorSeed";

// ============================================================
// MORE APT GROUPS (Russian, Iranian, NK, Others)
// ============================================================

const MORE_APT_GROUPS: SeedThreatActor[] = [
  // Russian APTs
  {
    actorId: "turla", name: "Turla", aliases: ["Snake", "Venomous Bear", "Uroburos", "Waterbug", "Secret Blizzard", "KRYPTON"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian FSB-linked group, one of the most sophisticated threat actors globally. Known for hijacking other APT groups' infrastructure and satellite-based C2.",
    firstSeen: "1996", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Diplomatic", "Research", "Aerospace"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1071.004", name: "DNS", tactic: "Command and Control", score: 3, description: "DNS-based C2 and tunneling." },
      { id: "T1102", name: "Web Service", tactic: "Command and Control", score: 3, description: "Using legitimate web services for C2." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 3, description: "Sophisticated injection techniques." },
      { id: "T1027", name: "Obfuscated Files or Information", tactic: "Defense Evasion", score: 3, description: "Heavy obfuscation and encryption." },
    ],
    tools: ["Snake", "Carbon", "Kazuar", "ComRAT", "Gazer", "LightNeuron"],
    malware: ["Snake", "Carbon", "Kazuar", "ComRAT", "Gazer", "LightNeuron", "TinyTurla"],
    activityTimeline: [
      { date: "2008", event: "Agent.BTZ infection of US military networks", source: "US DoD" },
      { date: "2020", event: "ComRAT v4 using Gmail for C2", source: "ESET" },
      { date: "2023", event: "Snake malware infrastructure disrupted by FBI", source: "FBI/CISA" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "sandworm", name: "Sandworm", aliases: ["Voodoo Bear", "IRIDIUM", "Seashell Blizzard", "TeleBots", "Electrum"],
    type: "apt", origin: "Russia", motivation: "Disruption / Espionage",
    description: "Russian GRU Unit 74455, responsible for the most destructive cyberattacks in history including NotPetya ($10B+ damage), Ukrainian power grid attacks, and Olympic Destroyer.",
    firstSeen: "2009", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Energy", "Government", "Transportation", "Financial Services", "Media"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of network infrastructure." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "NotPetya and other destructive ransomware." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Wiper malware deployment." },
      { id: "T1495", name: "Firmware Corruption", tactic: "Impact", score: 3, description: "Industrial control system attacks." },
    ],
    tools: ["BlackEnergy", "Industroyer", "NotPetya", "Olympic Destroyer", "CaddyWiper"],
    malware: ["BlackEnergy", "Industroyer", "NotPetya", "Olympic Destroyer", "CaddyWiper", "WhisperGate"],
    activityTimeline: [
      { date: "2015", event: "Ukrainian power grid attack (BlackEnergy)", source: "CISA" },
      { date: "2017", event: "NotPetya global destructive attack ($10B+ damage)", source: "Multiple" },
      { date: "2018", event: "Olympic Destroyer targeting PyeongChang Olympics", source: "Kaspersky" },
      { date: "2022", event: "Industroyer2 targeting Ukrainian power grid", source: "ESET" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "gamaredon", name: "Gamaredon", aliases: ["Primitive Bear", "Shuckworm", "Actinium", "Aqua Blizzard", "Armageddon"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian FSB-linked group (Crimea-based) conducting high-volume, persistent targeting of Ukrainian government and military organizations.",
    firstSeen: "2013", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Military", "Law Enforcement", "Diplomatic"],
    targetRegions: ["Eastern Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "High-volume phishing campaigns." },
      { id: "T1059.005", name: "Visual Basic", tactic: "Execution", score: 3, description: "VBS scripts for payload delivery." },
      { id: "T1091", name: "Replication Through Removable Media", tactic: "Lateral Movement", score: 2, description: "USB worm propagation." },
    ],
    tools: ["Pteranodon", "QuietSieve", "GammaLoad", "GammaSteel"],
    malware: ["Pteranodon", "QuietSieve", "GammaLoad", "GammaSteel"],
    activityTimeline: [
      { date: "2022", event: "Massive escalation targeting Ukraine during invasion", source: "CERT-UA" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "dragonfly", name: "Dragonfly", aliases: ["Energetic Bear", "Crouching Yeti", "DYMALLOY", "Berserk Bear"],
    type: "apt", origin: "Russia", motivation: "Espionage / Sabotage",
    description: "Russian state-sponsored group targeting energy sector and critical infrastructure, particularly ICS/SCADA systems in the US and Europe.",
    firstSeen: "2011", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Energy", "Utilities", "Nuclear", "Manufacturing"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Trojanized ICS software updates." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks on energy sector sites." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Stolen VPN and RDP credentials." },
    ],
    tools: ["Havex", "Karagany", "Sysmain", "Heriplor"],
    malware: ["Havex", "Karagany", "Heriplor"],
    activityTimeline: [
      { date: "2014", event: "Havex malware targeting ICS systems", source: "Symantec" },
      { date: "2017", event: "Dragonfly 2.0 targeting US nuclear facilities", source: "CISA/FBI" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "star-blizzard", name: "Star Blizzard", aliases: ["COLDRIVER", "Callisto", "SEABORGIUM", "TA446"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian FSB-linked group targeting government officials, think tanks, journalists, and NGOs through sophisticated credential phishing campaigns.",
    firstSeen: "2015", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Think Tanks", "Media", "NGO", "Academic"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Highly targeted credential phishing." },
      { id: "T1598.003", name: "Spearphishing Link (Recon)", tactic: "Reconnaissance", score: 3, description: "Social engineering for intelligence gathering." },
      { id: "T1078.004", name: "Cloud Accounts", tactic: "Persistence", score: 3, description: "Cloud email account compromise." },
    ],
    tools: ["EvilGinx", "Custom phishing frameworks"],
    malware: ["SPICA"],
    activityTimeline: [
      { date: "2023", event: "DOJ seizes Star Blizzard infrastructure", source: "US DOJ" },
      { date: "2024", event: "Targeting US and UK government officials", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  // Iranian APTs
  {
    actorId: "muddywater", name: "MuddyWater", aliases: ["Mercury", "Mango Sandstorm", "TEMP.Zagros", "Static Kitten"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian MOIS-linked group targeting government, telecommunications, and oil sectors across the Middle East, Europe, and North America.",
    firstSeen: "2017", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Telecommunications", "Oil & Gas", "Defense"],
    targetRegions: ["Middle East", "Europe", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Macro-enabled documents." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell-based backdoors." },
      { id: "T1218.005", name: "Mshta", tactic: "Defense Evasion", score: 2, description: "Mshta for script execution." },
    ],
    tools: ["POWERSTATS", "MuddyC2Go", "PhonyC2", "Atera", "SimpleHelp"],
    malware: ["POWERSTATS", "MuddyC2Go", "PhonyC2"],
    activityTimeline: [
      { date: "2022", event: "CISA advisory on MuddyWater targeting critical infrastructure", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "moses-staff", name: "Moses Staff", aliases: ["Marigold Sandstorm", "DEV-0500"],
    type: "apt", origin: "Iran", motivation: "Disruption / Hacktivism",
    description: "Iranian group conducting destructive attacks against Israeli organizations, using wiper malware and data leaks for political purposes.",
    firstSeen: "2021", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Finance", "Technology", "Defense"],
    targetRegions: ["Middle East"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploiting Exchange and web servers." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Encryption without ransom demand." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Data wiping operations." },
    ],
    tools: ["PyDCrypt", "DCSrv", "StrifeWater"],
    malware: ["PyDCrypt", "DCSrv", "StrifeWater"],
    activityTimeline: [
      { date: "2021", event: "Destructive attacks against Israeli organizations", source: "Check Point" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "agrius", name: "Agrius", aliases: ["Pink Sandstorm", "DEV-0227"],
    type: "apt", origin: "Iran", motivation: "Disruption",
    description: "Iranian group conducting destructive operations disguised as ransomware against Israeli and Middle Eastern targets.",
    firstSeen: "2020", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Technology", "Diamond Industry", "Education"],
    targetRegions: ["Middle East", "Africa"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of web-facing applications." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Fake ransomware (actually wiper)." },
    ],
    tools: ["Apostle", "Fantasy", "Moneybird"],
    malware: ["Apostle", "Fantasy", "Moneybird"],
    activityTimeline: [
      { date: "2022", event: "Fantasy wiper targeting diamond industry", source: "ESET" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  // North Korean
  {
    actorId: "kimsuky", name: "Kimsuky", aliases: ["Velvet Chollima", "Emerald Sleet", "THALLIUM", "Black Banshee", "TA406"],
    type: "apt", origin: "North Korea", motivation: "Espionage",
    description: "North Korean intelligence group targeting think tanks, academic institutions, and government organizations focused on Korean peninsula affairs, nuclear policy, and sanctions.",
    firstSeen: "2012", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Think Tanks", "Academic", "Defense", "Media"],
    targetRegions: ["East Asia", "North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing impersonating journalists and academics." },
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential harvesting phishing." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell-based backdoors." },
      { id: "T1113", name: "Screen Capture", tactic: "Collection", score: 2, description: "Screenshot capture for intelligence." },
    ],
    tools: ["BabyShark", "AppleSeed", "FlowerPower", "GoldDragon"],
    malware: ["BabyShark", "AppleSeed", "FlowerPower", "GoldDragon", "ReconShark"],
    activityTimeline: [
      { date: "2019", event: "Targeting US think tanks on North Korea policy", source: "CISA" },
      { date: "2023", event: "ReconShark malware targeting policy experts", source: "SentinelOne" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "andariel", name: "Andariel", aliases: ["Silent Chollima", "Onyx Sleet", "Stonefly", "PLUTONIUM"],
    type: "apt", origin: "North Korea", motivation: "Financial / Espionage",
    description: "North Korean RGB-linked group targeting defense, aerospace, nuclear, and engineering organizations. Also conducts ransomware operations for revenue generation.",
    firstSeen: "2009", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Defense", "Aerospace", "Nuclear", "Engineering", "Healthcare"],
    targetRegions: ["East Asia", "North America"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of Log4Shell and other vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Maui ransomware for revenue generation." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft from defense networks." },
    ],
    tools: ["DTrack", "Maui Ransomware", "TigerRAT", "EarlyRAT"],
    malware: ["DTrack", "Maui", "TigerRAT", "EarlyRAT", "NukeSped"],
    activityTimeline: [
      { date: "2022", event: "CISA advisory on Maui ransomware targeting healthcare", source: "CISA" },
      { date: "2024", event: "DOJ indictment of Andariel member", source: "US DOJ" },
    ],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "scattered-spider", name: "Scattered Spider", aliases: ["Octo Tempest", "UNC3944", "0ktapus", "Starfraud"],
    type: "cybercrime", origin: "US/UK", motivation: "Financial",
    description: "English-speaking cybercrime group known for sophisticated social engineering, SIM swapping, and MFA fatigue attacks. Responsible for MGM Resorts and Caesars Entertainment breaches.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Hospitality", "Technology", "Telecommunications", "Financial Services", "Gaming"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.004", name: "Spearphishing Voice", tactic: "Initial Access", score: 3, description: "Vishing attacks impersonating IT helpdesk." },
      { id: "T1621", name: "Multi-Factor Authentication Request Generation", tactic: "Credential Access", score: 3, description: "MFA fatigue/push bombing attacks." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "SIM swapping for account takeover." },
      { id: "T1098", name: "Account Manipulation", tactic: "Persistence", score: 3, description: "Creating admin accounts and modifying MFA." },
    ],
    tools: ["Cobalt Strike", "Mimikatz", "ALPHV/BlackCat ransomware"],
    malware: ["ALPHV/BlackCat"],
    activityTimeline: [
      { date: "2022", event: "0ktapus campaign targeting 130+ organizations", source: "Group-IB" },
      { date: "2023", event: "MGM Resorts breach ($100M+ impact)", source: "Multiple" },
      { date: "2024", event: "Multiple arrests of group members", source: "FBI" },
    ],
    dataSource: "osint", confidence: 92,
  },
  // More state-sponsored
  {
    actorId: "volt-typhoon", name: "Volt Typhoon", aliases: ["Bronze Silhouette", "Vanguard Panda", "DEV-0391", "Insidious Taurus"],
    type: "apt", origin: "China", motivation: "Pre-positioning / Espionage",
    description: "Chinese state-sponsored group pre-positioning in US critical infrastructure for potential future disruption. Uses living-off-the-land techniques exclusively to avoid detection.",
    firstSeen: "2021", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Critical Infrastructure", "Telecommunications", "Energy", "Water", "Transportation"],
    targetRegions: ["North America", "Pacific Islands"],
    techniques: [
      { id: "T1133", name: "External Remote Services", tactic: "Initial Access", score: 3, description: "Exploitation of SOHO routers and VPN appliances." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "Living-off-the-land with built-in tools." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Stolen credentials for long-term access." },
      { id: "T1218", name: "System Binary Proxy Execution", tactic: "Defense Evasion", score: 3, description: "Using legitimate system binaries." },
    ],
    tools: ["Built-in OS tools only", "netsh", "wmic", "ntdsutil", "PowerShell"],
    malware: [],
    activityTimeline: [
      { date: "2023", event: "Microsoft/CISA advisory on critical infrastructure targeting", source: "Microsoft/CISA" },
      { date: "2024", event: "FBI disrupts KV Botnet used by Volt Typhoon", source: "FBI" },
      { date: "2025", event: "Continued pre-positioning in US infrastructure", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "salt-typhoon", name: "Salt Typhoon", aliases: ["GhostEmperor", "FamousSparrow", "UNC2286"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group that compromised major US telecommunications providers (AT&T, Verizon, T-Mobile) to intercept communications of government officials.",
    firstSeen: "2019", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Telecommunications", "Government", "ISP"],
    targetRegions: ["North America", "Southeast Asia"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of telecom infrastructure." },
      { id: "T1557", name: "Adversary-in-the-Middle", tactic: "Collection", score: 3, description: "Intercepting communications at telecom level." },
      { id: "T1040", name: "Network Sniffing", tactic: "Credential Access", score: 3, description: "Packet capture on telecom networks." },
    ],
    tools: ["Demodex rootkit", "GhostEmperor tools"],
    malware: ["Demodex"],
    activityTimeline: [
      { date: "2024", event: "Compromise of major US telecom providers revealed", source: "CISA/FBI" },
    ],
    dataSource: "osint", confidence: 90,
  },
  {
    actorId: "flax-typhoon", name: "Flax Typhoon", aliases: ["Ethereal Panda", "RedJuliett"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting Taiwanese organizations and building IoT botnets for persistent access to critical infrastructure.",
    firstSeen: "2021", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Technology", "Telecommunications", "Defense"],
    targetRegions: ["East Asia", "North America"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of VPN and web applications." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Credential-based persistence." },
      { id: "T1059.004", name: "Unix Shell", tactic: "Execution", score: 2, description: "Linux-based IoT device compromise." },
    ],
    tools: ["China Chopper", "SoftEther VPN", "Raptor Train botnet"],
    malware: ["Raptor Train"],
    activityTimeline: [
      { date: "2023", event: "Microsoft advisory on Flax Typhoon targeting Taiwan", source: "Microsoft" },
      { date: "2024", event: "FBI disrupts Raptor Train IoT botnet", source: "FBI" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "sidewinder", name: "SideWinder", aliases: ["Rattlesnake", "T-APT-04", "Razor Tiger"],
    type: "apt", origin: "India", motivation: "Espionage",
    description: "Indian state-sponsored group targeting Pakistan, China, and other South Asian countries' military and government organizations.",
    firstSeen: "2012", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Military", "Government", "Defense", "Diplomatic"],
    targetRegions: ["South Asia", "East Asia", "Middle East"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Military-themed phishing lures." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 3, description: "CVE exploitation in Office documents." },
      { id: "T1059.005", name: "Visual Basic", tactic: "Execution", score: 2, description: "VBA macro execution." },
    ],
    tools: ["SideWinder.StealerPy", "WarHawk"],
    malware: ["SideWinder.StealerPy", "WarHawk"],
    activityTimeline: [
      { date: "2023", event: "Targeting Pakistani military organizations", source: "Kaspersky" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "patchwork", name: "Patchwork", aliases: ["Dropping Elephant", "Chinastrats", "Monsoon", "ZINC"],
    type: "apt", origin: "India", motivation: "Espionage",
    description: "Indian state-sponsored group targeting Pakistan and China, known for using copy-pasted code from various sources (hence the name).",
    firstSeen: "2015", lastActive: "2024", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Government", "Military", "Diplomatic", "Think Tanks"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with geopolitical lures." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 2, description: "Document exploit delivery." },
    ],
    tools: ["BADNEWS", "Ragnatela", "Brute Ratel"],
    malware: ["BADNEWS", "Ragnatela"],
    activityTimeline: [
      { date: "2022", event: "Accidentally infected own systems, exposing operations", source: "Malwarebytes" },
    ],
    dataSource: "mitre", confidence: 75,
  },
  {
    actorId: "donot-team", name: "DoNot Team", aliases: ["APT-C-35", "SectorE02", "Origami Elephant"],
    type: "apt", origin: "India", motivation: "Espionage",
    description: "Indian state-sponsored group targeting Pakistan, Kashmir, and South Asian diplomatic entities.",
    firstSeen: "2016", lastActive: "2024", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Government", "Military", "Diplomatic"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing campaigns." },
      { id: "T1204.002", name: "Malicious File", tactic: "Execution", score: 2, description: "Malicious document execution." },
    ],
    tools: ["yty framework", "DarkMusical", "Gedit"],
    malware: ["yty", "DarkMusical"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 70,
  },
  {
    actorId: "bitter", name: "BITTER", aliases: ["APT-C-08", "T-APT-17"],
    type: "apt", origin: "India", motivation: "Espionage",
    description: "South Asian threat group targeting government and energy organizations in Pakistan, China, and Bangladesh.",
    firstSeen: "2013", lastActive: "2024", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Government", "Energy", "Engineering"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with exploit documents." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 2, description: "Office vulnerability exploitation." },
    ],
    tools: ["BitterRAT", "ArtraDownloader"],
    malware: ["BitterRAT", "ArtraDownloader"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 70,
  },
];

// ============================================================
// CYBERCRIME GROUPS
// ============================================================

const CYBERCRIME_GROUPS: SeedThreatActor[] = [
  {
    actorId: "fin7", name: "FIN7", aliases: ["Carbanak", "Carbon Spider", "Sangria Tempest", "ELBRUS"],
    type: "cybercrime", origin: "Russia", motivation: "Financial",
    description: "One of the most prolific financially motivated threat groups, responsible for stealing over $1 billion from banks and retailers worldwide. Operates like a legitimate business with HR, developers, and pen testers.",
    firstSeen: "2013", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Financial Services", "Retail", "Hospitality", "Restaurant"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Sophisticated phishing with social engineering." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell-based backdoors." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 3, description: "In-memory execution." },
      { id: "T1005", name: "Data from Local System", tactic: "Collection", score: 3, description: "POS malware for card data theft." },
    ],
    tools: ["Carbanak", "GRIFFON", "BOOSTWRITE", "Cobalt Strike", "Metasploit"],
    malware: ["Carbanak", "GRIFFON", "BOOSTWRITE", "BIRDWATCH"],
    activityTimeline: [
      { date: "2018", event: "Three FIN7 members arrested", source: "US DOJ" },
      { date: "2021", event: "FIN7 creates fake security company Bastion Secure", source: "Recorded Future" },
      { date: "2024", event: "Continued operations with ransomware affiliations", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "fin8", name: "FIN8", aliases: ["Syssphinx", "White Rabbit"],
    type: "cybercrime", origin: "Unknown", motivation: "Financial",
    description: "Financially motivated group targeting POS systems in retail, hospitality, and entertainment sectors.",
    firstSeen: "2016", lastActive: "2023", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Retail", "Hospitality", "Entertainment", "Financial Services"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with malicious documents." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for execution." },
      { id: "T1005", name: "Data from Local System", tactic: "Collection", score: 3, description: "POS memory scraping." },
    ],
    tools: ["BADHATCH", "PUNCHTRACK", "White Rabbit ransomware"],
    malware: ["BADHATCH", "PUNCHTRACK", "White Rabbit"],
    activityTimeline: [
      { date: "2021", event: "Deployment of White Rabbit ransomware", source: "Trend Micro" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "fin11", name: "FIN11", aliases: ["TA505", "Graceful Spider", "GOLD TAHOE"],
    type: "cybercrime", origin: "Russia", motivation: "Financial",
    description: "Prolific financially motivated group known for massive spam campaigns, Cl0p ransomware deployment, and exploitation of zero-day vulnerabilities in file transfer applications.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Financial Services", "Healthcare", "Retail", "Technology"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Massive phishing campaigns." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation (MOVEit, GoAnywhere, Accellion)." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Cl0p ransomware deployment." },
    ],
    tools: ["Cl0p ransomware", "FlawedAmmyy", "SDBbot", "Get2"],
    malware: ["Cl0p", "FlawedAmmyy", "SDBbot", "Get2", "DEWMODE"],
    activityTimeline: [
      { date: "2023", event: "MOVEit Transfer zero-day exploitation affecting 2,500+ organizations", source: "Multiple" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "fin12", name: "FIN12", aliases: ["Pistol Tempest", "DEV-0237"],
    type: "cybercrime", origin: "Russia", motivation: "Financial",
    description: "Ransomware-focused group known for rapid deployment of Ryuk/Conti ransomware, particularly targeting healthcare organizations.",
    firstSeen: "2018", lastActive: "2023", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Education", "Government", "Manufacturing"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "BazarLoader delivery via phishing." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Rapid ransomware deployment." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft for lateral movement." },
    ],
    tools: ["Cobalt Strike", "Ryuk", "Conti", "Mimikatz", "BazarLoader"],
    malware: ["Ryuk", "Conti", "BazarLoader"],
    activityTimeline: [
      { date: "2020", event: "Targeting US hospitals during COVID-19", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "wizard-spider", name: "Wizard Spider", aliases: ["GOLD BLACKBURN", "Grim Spider", "UNC1878"],
    type: "cybercrime", origin: "Russia", motivation: "Financial",
    description: "Russian cybercrime syndicate operating TrickBot botnet, Ryuk and Conti ransomware. One of the most impactful cybercrime operations in history.",
    firstSeen: "2016", lastActive: "2024", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Healthcare", "Government", "Education", "Manufacturing", "Financial Services"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Emotet/TrickBot delivery via phishing." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Ryuk/Conti ransomware." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft with Mimikatz." },
      { id: "T1021.002", name: "SMB/Windows Admin Shares", tactic: "Lateral Movement", score: 3, description: "Lateral movement via SMB." },
    ],
    tools: ["TrickBot", "BazarLoader", "Cobalt Strike", "Mimikatz", "Ryuk", "Conti"],
    malware: ["TrickBot", "BazarLoader", "Ryuk", "Conti", "Diavol"],
    activityTimeline: [
      { date: "2020", event: "TrickBot botnet disruption by Microsoft", source: "Microsoft" },
      { date: "2022", event: "Conti source code and chat logs leaked", source: "ContiLeaks" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "evil-corp", name: "Evil Corp", aliases: ["INDRIK SPIDER", "Manatee Tempest", "GOLD DRAKE", "Dridex Gang"],
    type: "cybercrime", origin: "Russia", motivation: "Financial",
    description: "Russian cybercrime group led by Maksim Yakubets, operating Dridex banking trojan and multiple ransomware families. Under US Treasury sanctions.",
    firstSeen: "2007", lastActive: "2024", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Financial Services", "Government", "Healthcare", "Technology"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Dridex delivery via phishing." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for payload delivery." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "WastedLocker, Hades, Phoenix ransomware." },
    ],
    tools: ["Dridex", "WastedLocker", "Hades", "Phoenix Locker", "Cobalt Strike"],
    malware: ["Dridex", "WastedLocker", "Hades", "Phoenix Locker", "Macaw Locker"],
    activityTimeline: [
      { date: "2019", event: "US Treasury sanctions and $5M bounty on leader", source: "US Treasury" },
      { date: "2022", event: "Rebranding ransomware to evade sanctions", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "lapsus", name: "LAPSUS$", aliases: ["DEV-0537", "Strawberry Tempest"],
    type: "cybercrime", origin: "UK/Brazil", motivation: "Financial / Notoriety",
    description: "Teenage-led extortion group that breached Microsoft, Nvidia, Samsung, Uber, and Rockstar Games through social engineering and insider recruitment.",
    firstSeen: "2021", lastActive: "2023", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Technology", "Gaming", "Telecommunications", "Government"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.004", name: "Spearphishing Voice", tactic: "Initial Access", score: 3, description: "Social engineering of helpdesks." },
      { id: "T1621", name: "Multi-Factor Authentication Request Generation", tactic: "Credential Access", score: 3, description: "MFA fatigue attacks." },
      { id: "T1586.002", name: "Email Accounts", tactic: "Resource Development", score: 2, description: "Insider recruitment via Telegram." },
    ],
    tools: ["Social engineering", "SIM swapping tools"],
    malware: [],
    activityTimeline: [
      { date: "2022", event: "Breaches of Microsoft, Nvidia, Samsung, Okta", source: "Multiple" },
      { date: "2023", event: "Members arrested and convicted in UK", source: "UK Police" },
    ],
    dataSource: "osint", confidence: 90,
  },
  {
    actorId: "magecart", name: "Magecart", aliases: ["Web Skimming Groups"],
    type: "cybercrime", origin: "Various", motivation: "Financial",
    description: "Umbrella term for multiple cybercrime groups specializing in web-based card skimming attacks, injecting malicious JavaScript into e-commerce checkout pages.",
    firstSeen: "2015", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["E-commerce", "Retail", "Hospitality", "Travel"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Compromising third-party JavaScript libraries." },
      { id: "T1059.007", name: "JavaScript", tactic: "Execution", score: 3, description: "Malicious JavaScript injection." },
      { id: "T1185", name: "Browser Session Hijacking", tactic: "Collection", score: 3, description: "Capturing payment card data from browsers." },
    ],
    tools: ["Custom JavaScript skimmers", "Inter skimmer kit"],
    malware: ["Inter skimmer", "Grelos"],
    activityTimeline: [
      { date: "2018", event: "British Airways breach (380,000 cards)", source: "RiskIQ" },
      { date: "2019", event: "Ticketmaster breach via third-party script", source: "RiskIQ" },
    ],
    dataSource: "osint", confidence: 85,
  },
];

// ============================================================
// RANSOMWARE GROUPS
// ============================================================

const RANSOMWARE_GROUPS: SeedThreatActor[] = [
  {
    actorId: "lockbit", name: "LockBit", aliases: ["ABCD Ransomware", "Gold Mystic", "Bitwise Spider"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Most prolific ransomware-as-a-service (RaaS) operation, responsible for the highest number of ransomware attacks globally. Disrupted by Operation Cronos in 2024 but attempted comeback.",
    firstSeen: "2019", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Healthcare", "Manufacturing", "Government", "Financial Services", "Education"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of VPN and RDP vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "LockBit 3.0 ransomware encryption." },
      { id: "T1567", name: "Exfiltration Over Web Service", tactic: "Exfiltration", score: 3, description: "StealBit data exfiltration tool." },
      { id: "T1489", name: "Service Stop", tactic: "Impact", score: 3, description: "Stopping backup and security services." },
    ],
    tools: ["LockBit 3.0", "StealBit", "Cobalt Strike", "Mimikatz"],
    malware: ["LockBit", "LockBit 2.0", "LockBit 3.0", "LockBit Green", "StealBit"],
    activityTimeline: [
      { date: "2022", event: "LockBit becomes most active ransomware group", source: "Multiple" },
      { date: "2024", event: "Operation Cronos disrupts LockBit infrastructure", source: "NCA/FBI" },
    ],
    dataSource: "osint", confidence: 95,
  },
  {
    actorId: "blackcat-alphv", name: "BlackCat/ALPHV", aliases: ["ALPHV", "Noberus", "Sphynx"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Sophisticated RaaS operation written in Rust, known for triple extortion and targeting critical infrastructure including healthcare (Change Healthcare breach).",
    firstSeen: "2021", lastActive: "2024", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Healthcare", "Financial Services", "Government", "Technology", "Legal"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Rust-based cross-platform encryption." },
      { id: "T1567", name: "Exfiltration Over Web Service", tactic: "Exfiltration", score: 3, description: "Data theft before encryption." },
    ],
    tools: ["BlackCat/ALPHV ransomware", "ExMatter", "Eamfo", "Cobalt Strike"],
    malware: ["BlackCat", "ALPHV", "Sphynx", "ExMatter"],
    activityTimeline: [
      { date: "2023", event: "FBI disrupts ALPHV infrastructure", source: "FBI" },
      { date: "2024", event: "Change Healthcare breach ($22M ransom paid)", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 92,
  },
  {
    actorId: "black-basta-rw", name: "Black Basta", aliases: ["Storm-0506"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group believed to be composed of former Conti members. Known for rapid encryption and targeting critical infrastructure.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Manufacturing", "Healthcare", "Construction", "Technology", "Financial Services"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "QakBot delivery via phishing." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Rapid encryption with ChaCha20." },
      { id: "T1567", name: "Exfiltration Over Web Service", tactic: "Exfiltration", score: 3, description: "Data theft for double extortion." },
    ],
    tools: ["QakBot", "Cobalt Strike", "Mimikatz", "SystemBC"],
    malware: ["Black Basta ransomware", "QakBot"],
    activityTimeline: [
      { date: "2024", event: "CISA advisory on Black Basta targeting healthcare", source: "CISA" },
      { date: "2025", event: "Internal chat logs leaked", source: "ExploitWhispers" },
    ],
    dataSource: "osint", confidence: 90,
  },
  {
    actorId: "clop-rw", name: "Cl0p", aliases: ["TA505", "FIN11", "Lace Tempest"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group known for mass exploitation of zero-day vulnerabilities in file transfer applications (MOVEit, GoAnywhere, Accellion), affecting thousands of organizations.",
    firstSeen: "2019", lastActive: "2025", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Financial Services", "Healthcare", "Government", "Education", "Technology"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation of file transfer apps." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Cl0p ransomware encryption." },
      { id: "T1567", name: "Exfiltration Over Web Service", tactic: "Exfiltration", score: 3, description: "Mass data exfiltration." },
    ],
    tools: ["Cl0p ransomware", "TrueBot", "FlawedGrace", "DEWMODE"],
    malware: ["Cl0p", "TrueBot", "FlawedGrace", "DEWMODE", "LEMURLOOT"],
    activityTimeline: [
      { date: "2023", event: "MOVEit Transfer exploitation affecting 2,500+ organizations", source: "Multiple" },
      { date: "2025", event: "Cleo file transfer exploitation", source: "Huntress" },
    ],
    dataSource: "osint", confidence: 95,
  },
  {
    actorId: "play-rw", name: "Play", aliases: ["PlayCrypt", "Balloonfly"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group targeting Latin American and European organizations, known for exploiting FortiOS and Microsoft Exchange vulnerabilities.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Manufacturing", "Technology", "Telecommunications"],
    targetRegions: ["Latin America", "Europe", "North America"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "FortiOS and Exchange exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Play ransomware encryption." },
    ],
    tools: ["Play ransomware", "Cobalt Strike", "SystemBC", "Grixba"],
    malware: ["Play ransomware", "Grixba"],
    activityTimeline: [
      { date: "2023", event: "CISA advisory on Play ransomware", source: "CISA" },
    ],
    dataSource: "osint", confidence: 85,
  },
  {
    actorId: "royal-rw", name: "Royal", aliases: ["DEV-0569", "Blacksuit"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group composed of former Conti members, rebranded to BlackSuit in 2023. Known for targeting critical infrastructure.",
    firstSeen: "2022", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Manufacturing", "Education", "Government"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Callback phishing campaigns." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Royal/BlackSuit encryption." },
    ],
    tools: ["Royal ransomware", "BlackSuit", "Cobalt Strike", "QakBot"],
    malware: ["Royal", "BlackSuit"],
    activityTimeline: [
      { date: "2023", event: "CISA advisory on Royal ransomware", source: "CISA" },
      { date: "2024", event: "Rebrand to BlackSuit ransomware", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 85,
  },
  {
    actorId: "akira-rw", name: "Akira", aliases: ["Storm-1567"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group with retro-themed leak site, targeting SMBs and exploiting Cisco VPN vulnerabilities.",
    firstSeen: "2023", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Manufacturing", "Technology", "Professional Services", "Healthcare"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1133", name: "External Remote Services", tactic: "Initial Access", score: 3, description: "Cisco VPN exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Cross-platform encryption (Windows/Linux)." },
    ],
    tools: ["Akira ransomware", "Megazord", "Cobalt Strike"],
    malware: ["Akira", "Megazord"],
    activityTimeline: [
      { date: "2024", event: "CISA advisory on Akira ransomware", source: "CISA" },
    ],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "rhysida-rw", name: "Rhysida", aliases: ["Vice Society successor"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group targeting healthcare, education, and government. Known for the British Library attack.",
    firstSeen: "2023", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Education", "Government", "Manufacturing"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing for initial access." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Rhysida ransomware encryption." },
    ],
    tools: ["Rhysida ransomware", "Cobalt Strike", "SystemBC"],
    malware: ["Rhysida"],
    activityTimeline: [
      { date: "2023", event: "British Library attack", source: "British Library" },
      { date: "2023", event: "CISA advisory on Rhysida", source: "CISA" },
    ],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "medusa-rw", name: "Medusa", aliases: ["MedusaLocker"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group targeting healthcare, education, and technology sectors with double extortion tactics.",
    firstSeen: "2021", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Healthcare", "Education", "Technology", "Manufacturing"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "RDP and vulnerability exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Medusa ransomware encryption." },
    ],
    tools: ["Medusa ransomware", "Cobalt Strike"],
    malware: ["Medusa", "MedusaLocker"],
    activityTimeline: [
      { date: "2025", event: "CISA advisory on Medusa ransomware", source: "CISA" },
    ],
    dataSource: "osint", confidence: 80,
  },
  {
    actorId: "bianlian-rw", name: "BianLian", aliases: [],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group that shifted from encryption to pure data extortion in 2023. Targets healthcare, financial, and professional services.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Financial Services", "Professional Services", "Manufacturing"],
    targetRegions: ["North America", "Europe", "Australia"],
    techniques: [
      { id: "T1133", name: "External Remote Services", tactic: "Initial Access", score: 3, description: "RDP and VPN exploitation." },
      { id: "T1567", name: "Exfiltration Over Web Service", tactic: "Exfiltration", score: 3, description: "Data theft for extortion." },
    ],
    tools: ["BianLian ransomware", "Cobalt Strike", "Rclone"],
    malware: ["BianLian"],
    activityTimeline: [
      { date: "2023", event: "CISA advisory on BianLian", source: "CISA" },
    ],
    dataSource: "osint", confidence: 80,
  },
  {
    actorId: "vice-society", name: "Vice Society", aliases: ["DEV-0832"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group disproportionately targeting the education sector, using multiple ransomware families.",
    firstSeen: "2021", lastActive: "2024", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Education", "Healthcare", "Government"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of known vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Multiple ransomware variants." },
    ],
    tools: ["Hello Kitty", "Zeppelin", "PolyVice", "Cobalt Strike"],
    malware: ["Hello Kitty", "Zeppelin", "PolyVice"],
    activityTimeline: [
      { date: "2022", event: "CISA advisory on Vice Society targeting education", source: "CISA" },
    ],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "hive-rw", name: "Hive", aliases: [],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware-as-a-service operation that was disrupted by FBI in 2023. Had targeted 1,500+ victims in 80+ countries.",
    firstSeen: "2021", lastActive: "2023", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Government", "Technology", "Manufacturing"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "ProxyShell and other exploits." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Hive ransomware encryption." },
    ],
    tools: ["Hive ransomware", "Cobalt Strike", "Mimikatz"],
    malware: ["Hive"],
    activityTimeline: [
      { date: "2023", event: "FBI disrupts Hive infrastructure, saves $130M in ransoms", source: "FBI" },
    ],
    dataSource: "osint", confidence: 88,
  },
  {
    actorId: "conti-rw", name: "Conti", aliases: ["Wizard Spider", "GOLD BLACKBURN"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "One of the most destructive ransomware operations in history, responsible for $180M+ in ransom payments. Disbanded in 2022 after internal leaks, members scattered to other groups.",
    firstSeen: "2020", lastActive: "2022", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Healthcare", "Government", "Manufacturing", "Technology", "Education"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "TrickBot/BazarLoader delivery." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Conti ransomware encryption." },
      { id: "T1021.002", name: "SMB/Windows Admin Shares", tactic: "Lateral Movement", score: 3, description: "Rapid lateral movement." },
    ],
    tools: ["Conti ransomware", "TrickBot", "BazarLoader", "Cobalt Strike", "Mimikatz"],
    malware: ["Conti", "TrickBot", "BazarLoader"],
    activityTimeline: [
      { date: "2021", event: "Irish Health Service Executive attack", source: "HSE" },
      { date: "2022", event: "ContiLeaks: internal chats and source code leaked", source: "ContiLeaks" },
      { date: "2022", event: "Group disbands, members join Black Basta, Royal, etc.", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 95,
  },
  {
    actorId: "revil", name: "REvil", aliases: ["Sodinokibi", "GOLD SOUTHFIELD", "Pinchy Spider"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Major RaaS operation responsible for Kaseya supply chain attack and JBS Foods breach. Disrupted by international law enforcement in 2022.",
    firstSeen: "2019", lastActive: "2022", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Technology", "Food & Agriculture", "Manufacturing", "Legal"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Kaseya VSA supply chain attack." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "REvil/Sodinokibi encryption." },
    ],
    tools: ["REvil ransomware", "Cobalt Strike", "QakBot"],
    malware: ["REvil", "Sodinokibi"],
    activityTimeline: [
      { date: "2021", event: "Kaseya supply chain attack affecting 1,500+ businesses", source: "Kaseya/FBI" },
      { date: "2021", event: "JBS Foods attack ($11M ransom paid)", source: "FBI" },
      { date: "2022", event: "FSB arrests REvil members at US request", source: "FSB" },
    ],
    dataSource: "osint", confidence: 95,
  },
  {
    actorId: "darkside", name: "DarkSide", aliases: ["Carbon Spider (partial)", "UNC2465"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group responsible for the Colonial Pipeline attack that caused fuel shortages across the US East Coast. Rebranded to BlackMatter after shutdown.",
    firstSeen: "2020", lastActive: "2021", threatLevel: "critical", sophistication: "advanced",
    targetSectors: ["Energy", "Manufacturing", "Financial Services", "Technology"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "VPN and RDP exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "DarkSide ransomware encryption." },
    ],
    tools: ["DarkSide ransomware", "Cobalt Strike", "Mimikatz"],
    malware: ["DarkSide", "BlackMatter"],
    activityTimeline: [
      { date: "2021", event: "Colonial Pipeline attack ($4.4M ransom, fuel shortages)", source: "FBI" },
      { date: "2021", event: "Group shuts down, rebrands to BlackMatter", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 92,
  },
  {
    actorId: "ragnar-locker", name: "Ragnar Locker", aliases: ["Viking Spider"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group known for deploying ransomware inside virtual machines to evade detection. Disrupted by Europol in 2023.",
    firstSeen: "2019", lastActive: "2023", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Manufacturing", "Energy", "Financial Services", "Government"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1564.006", name: "Run Virtual Instance", tactic: "Defense Evasion", score: 3, description: "Running ransomware inside VirtualBox VM." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Ragnar Locker encryption." },
    ],
    tools: ["Ragnar Locker ransomware", "VirtualBox"],
    malware: ["Ragnar Locker"],
    activityTimeline: [
      { date: "2023", event: "Europol takes down Ragnar Locker infrastructure", source: "Europol" },
    ],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "8base", name: "8Base", aliases: [],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group that emerged as one of the most active in 2023, targeting SMBs with Phobos ransomware variant.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Manufacturing", "Professional Services", "Construction", "Technology"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing for initial access." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Phobos-based encryption." },
    ],
    tools: ["Phobos ransomware", "SmokeLoader"],
    malware: ["Phobos", "8Base ransomware"],
    activityTimeline: [
      { date: "2025", event: "International law enforcement takedown", source: "Europol" },
    ],
    dataSource: "osint", confidence: 75,
  },
  {
    actorId: "hunters-intl", name: "Hunters International", aliases: ["Hive successor"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group that acquired Hive's source code after FBI disruption. Focuses on data exfiltration over encryption.",
    firstSeen: "2023", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Technology", "Manufacturing", "Government"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Vulnerability exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Hive-derived encryption." },
    ],
    tools: ["Hunters International ransomware", "SharpRhino"],
    malware: ["Hunters International", "SharpRhino"],
    activityTimeline: [
      { date: "2024", event: "Rapid growth as Hive successor", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 75,
  },
  {
    actorId: "inc-ransom", name: "INC Ransom", aliases: ["INC"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Ransomware group targeting healthcare, education, and government with methodical attack approach.",
    firstSeen: "2023", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Healthcare", "Education", "Government"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Citrix and VPN exploitation." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "INC ransomware encryption." },
    ],
    tools: ["INC ransomware", "Cobalt Strike", "MegaSync"],
    malware: ["INC Ransom"],
    activityTimeline: [],
    dataSource: "osint", confidence: 72,
  },
  {
    actorId: "qilin", name: "Qilin", aliases: ["Agenda"],
    type: "ransomware", origin: "Russia", motivation: "Financial",
    description: "Ransomware group that attacked NHS provider Synnovis, causing major disruption to London hospitals.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Manufacturing", "Technology"],
    targetRegions: ["Europe", "North America", "Asia"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Cross-platform Rust-based encryption." },
    ],
    tools: ["Qilin ransomware", "Cobalt Strike"],
    malware: ["Qilin", "Agenda"],
    activityTimeline: [
      { date: "2024", event: "Synnovis/NHS attack disrupting London hospitals", source: "NHS" },
    ],
    dataSource: "osint", confidence: 78,
  },
  {
    actorId: "ransomhub", name: "RansomHub", aliases: ["Cyclops", "Knight"],
    type: "ransomware", origin: "Unknown", motivation: "Financial",
    description: "Emerging RaaS operation that rapidly gained market share after LockBit and ALPHV disruptions.",
    firstSeen: "2024", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Government", "Technology", "Financial Services"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of known vulnerabilities." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "RansomHub encryption." },
    ],
    tools: ["RansomHub ransomware", "Cobalt Strike"],
    malware: ["RansomHub"],
    activityTimeline: [
      { date: "2024", event: "CISA advisory on RansomHub", source: "CISA" },
    ],
    dataSource: "osint", confidence: 75,
  },
];

// ============================================================
// HACKTIVIST GROUPS
// ============================================================

const HACKTIVIST_GROUPS: SeedThreatActor[] = [
  {
    actorId: "killnet", name: "KillNet", aliases: ["Anonymous Russia"],
    type: "hacktivist", origin: "Russia", motivation: "Political / Disruption",
    description: "Pro-Russian hacktivist group conducting DDoS attacks against NATO countries and organizations supporting Ukraine.",
    firstSeen: "2022", lastActive: "2024", threatLevel: "medium", sophistication: "basic",
    targetSectors: ["Government", "Healthcare", "Transportation", "Financial Services"],
    targetRegions: ["Europe", "North America"],
    techniques: [
      { id: "T1498", name: "Network Denial of Service", tactic: "Impact", score: 3, description: "Volumetric DDoS attacks." },
      { id: "T1499", name: "Endpoint Denial of Service", tactic: "Impact", score: 2, description: "Application-layer DDoS." },
    ],
    tools: ["DDoS tools", "CC attack tools"],
    malware: [],
    activityTimeline: [
      { date: "2022", event: "DDoS attacks against US airports and hospitals", source: "CISA" },
    ],
    dataSource: "osint", confidence: 80,
  },
  {
    actorId: "noname057", name: "NoName057(16)", aliases: [],
    type: "hacktivist", origin: "Russia", motivation: "Political",
    description: "Pro-Russian hacktivist group conducting DDoS attacks against European government websites using DDoSia tool.",
    firstSeen: "2022", lastActive: "2025", threatLevel: "medium", sophistication: "basic",
    targetSectors: ["Government", "Financial Services", "Transportation"],
    targetRegions: ["Europe"],
    techniques: [
      { id: "T1498", name: "Network Denial of Service", tactic: "Impact", score: 3, description: "DDoSia crowdsourced DDoS." },
    ],
    tools: ["DDoSia"],
    malware: [],
    activityTimeline: [
      { date: "2023", event: "Sustained DDoS campaigns against European governments", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 75,
  },
  {
    actorId: "anonymous-sudan", name: "Anonymous Sudan", aliases: ["Storm-1359"],
    type: "hacktivist", origin: "Sudan", motivation: "Political / Financial",
    description: "Hacktivist group conducting DDoS attacks against Western organizations, Microsoft, and others. Two members arrested by FBI in 2024.",
    firstSeen: "2023", lastActive: "2024", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Technology", "Government", "Healthcare", "Financial Services"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1498", name: "Network Denial of Service", tactic: "Impact", score: 3, description: "Layer 7 DDoS attacks." },
    ],
    tools: ["DCAT (Distributed Cloud Attack Tool)", "Skynet Botnet", "InfraShutdown"],
    malware: [],
    activityTimeline: [
      { date: "2023", event: "DDoS attacks against Microsoft Azure and Outlook", source: "Microsoft" },
      { date: "2024", event: "Two members arrested by FBI", source: "FBI" },
    ],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "cyber-av3ngers", name: "CyberAv3ngers", aliases: ["IRGC-affiliated"],
    type: "hacktivist", origin: "Iran", motivation: "Political / Disruption",
    description: "IRGC-affiliated hacktivist group targeting Israeli and Western critical infrastructure, particularly water treatment facilities.",
    firstSeen: "2023", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Water", "Energy", "Manufacturing"],
    targetRegions: ["North America", "Europe", "Middle East"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of Unitronics PLCs." },
      { id: "T1495", name: "Firmware Corruption", tactic: "Impact", score: 2, description: "ICS/SCADA manipulation." },
    ],
    tools: ["Custom ICS exploitation tools"],
    malware: [],
    activityTimeline: [
      { date: "2023", event: "Targeting US water treatment facilities (Unitronics PLCs)", source: "CISA" },
    ],
    dataSource: "osint", confidence: 80,
  },
  {
    actorId: "predatory-sparrow", name: "Predatory Sparrow", aliases: ["Gonjeshke Darande"],
    type: "hacktivist", origin: "Israel (suspected)", motivation: "Disruption",
    description: "Sophisticated hacktivist group targeting Iranian infrastructure, including steel mills and gas stations, with destructive cyberattacks.",
    firstSeen: "2021", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Manufacturing", "Energy", "Transportation"],
    targetRegions: ["Middle East"],
    techniques: [
      { id: "T1495", name: "Firmware Corruption", tactic: "Impact", score: 3, description: "ICS attacks on steel mills." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Destructive attacks on infrastructure." },
    ],
    tools: ["Custom ICS tools"],
    malware: [],
    activityTimeline: [
      { date: "2022", event: "Attack on Iranian steel mills causing physical damage", source: "Multiple" },
      { date: "2023", event: "Attack on Iranian gas station payment systems", source: "Multiple" },
    ],
    dataSource: "osint", confidence: 70,
  },
];

export { MORE_APT_GROUPS, CYBERCRIME_GROUPS, RANSOMWARE_GROUPS, HACKTIVIST_GROUPS };
