// Comprehensive threat actor seed data - 400+ actors
// Organized by type: APT, Cybercrime, Ransomware, Hacktivist

export interface SeedThreatActor {
  actorId: string;
  name: string;
  aliases: string[];
  type: "apt" | "cybercrime" | "ransomware" | "hacktivist" | "unknown";
  origin: string;
  description: string;
  motivation: string;
  firstSeen: string;
  lastActive: string;
  threatLevel: "critical" | "high" | "medium" | "low";
  sophistication: "nation-state" | "advanced" | "intermediate" | "basic";
  targetSectors: string[];
  targetRegions: string[];
  techniques: { id: string; name: string; tactic: string; score: number; description: string }[];
  tools: string[];
  malware: string[];
  activityTimeline: { date: string; event: string; source: string }[];
  dataSource: string;
  confidence: number;
}

// ============================================================
// APT GROUPS (State-Sponsored)
// ============================================================

const APT_GROUPS: SeedThreatActor[] = [
  {
    actorId: "apt1", name: "APT1", aliases: ["Comment Crew", "Comment Panda", "PLA Unit 61398"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese military cyber espionage unit (PLA Unit 61398) responsible for extensive campaigns against US corporations, stealing hundreds of terabytes of data from at least 141 organizations across 20 major industries.",
    firstSeen: "2006", lastActive: "2023", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Defense", "Technology", "Aerospace", "Energy", "Telecommunications"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Weaponized document attachments targeting specific individuals." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell scripts for command execution and payload delivery." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential harvesting from compromised systems." },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration", score: 3, description: "Data theft through command and control channels." },
    ],
    tools: ["WEBC2", "Poison Ivy", "BISCUIT", "CALENDAR"],
    malware: ["WEBC2-DIV", "WEBC2-GREENCAT", "BISCUIT"],
    activityTimeline: [
      { date: "2006", event: "First observed operations targeting US defense contractors", source: "Mandiant" },
      { date: "2013", event: "Mandiant APT1 report published, exposing PLA Unit 61398", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt2", name: "APT2", aliases: ["Putter Panda", "MSUpdater"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese cyber espionage group associated with PLA Unit 61486, primarily targeting space, aerospace, and satellite industries.",
    firstSeen: "2007", lastActive: "2020", threatLevel: "medium", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Defense", "Satellite", "Technology"],
    targetRegions: ["North America", "Europe", "Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing with weaponized documents." },
      { id: "T1105", name: "Ingress Tool Transfer", tactic: "Command and Control", score: 2, description: "Downloading additional tools post-compromise." },
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control", score: 2, description: "HTTP/HTTPS for C2 communication." },
    ],
    tools: ["MSUpdater", "4H RAT", "3PARA RAT"],
    malware: ["MSUpdater", "4H RAT"],
    activityTimeline: [
      { date: "2007", event: "Initial operations targeting aerospace sector", source: "CrowdStrike" },
      { date: "2014", event: "CrowdStrike report on Putter Panda operations", source: "CrowdStrike" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt3", name: "APT3", aliases: ["Gothic Panda", "Pirpi", "UPS Team", "Buckeye", "TG-0110"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group linked to MSS (Ministry of State Security) Guangdong bureau, known for using zero-day exploits and targeting political organizations, aerospace, and defense.",
    firstSeen: "2007", lastActive: "2022", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Defense", "Aerospace", "Technology", "Political Organizations", "Telecommunications"],
    targetRegions: ["North America", "Europe", "Asia"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation of browsers and web applications." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for post-exploitation activities." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "LSASS memory dumping for credential theft." },
      { id: "T1021.002", name: "SMB/Windows Admin Shares", tactic: "Lateral Movement", score: 3, description: "Lateral movement via admin shares." },
    ],
    tools: ["Pirpi", "PlugX", "RemoteCMD", "schtasks"],
    malware: ["Pirpi", "PlugX", "OSInfo"],
    activityTimeline: [
      { date: "2014", event: "Clandestine Fox campaign using IE zero-day", source: "FireEye" },
      { date: "2015", event: "Operation Clandestine Wolf targeting aerospace", source: "FireEye" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt4", name: "APT4", aliases: ["Maverick Panda", "Sykipot", "Wisp"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese cyber espionage group targeting aerospace, defense, and telecommunications sectors with focus on military technology theft.",
    firstSeen: "2007", lastActive: "2018", threatLevel: "medium", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Defense", "Telecommunications"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Weaponized PDF and Office documents." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 2, description: "Exploiting client applications for code execution." },
    ],
    tools: ["Sykipot"],
    malware: ["Sykipot"],
    activityTimeline: [
      { date: "2007", event: "First observed targeting US defense sector", source: "MITRE" },
    ],
    dataSource: "mitre", confidence: 75,
  },
  {
    actorId: "apt5", name: "APT5", aliases: ["Keyhole Panda", "MANGANESE"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting telecommunications and technology companies, particularly focused on satellite communications and networking equipment.",
    firstSeen: "2007", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Telecommunications", "Technology", "Defense", "Satellite"],
    targetRegions: ["Southeast Asia", "North America", "Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of Citrix and Pulse Secure VPN vulnerabilities." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Use of stolen credentials for persistent access." },
      { id: "T1021", name: "Remote Services", tactic: "Lateral Movement", score: 2, description: "Lateral movement via remote services." },
    ],
    tools: ["LEOUNCIA", "BLOODMINE", "BLOODBANK"],
    malware: ["LEOUNCIA", "BLOODMINE"],
    activityTimeline: [
      { date: "2022", event: "Exploitation of Citrix ADC zero-day (CVE-2022-27518)", source: "NSA" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt6", name: "APT6", aliases: ["1.php Group"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese cyber espionage group targeting transportation and automotive sectors.",
    firstSeen: "2008", lastActive: "2016", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Transportation", "Automotive", "Government"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with malicious attachments." },
      { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution", score: 2, description: "Script-based execution." },
    ],
    tools: ["Poison Ivy", "Gh0st RAT"],
    malware: ["Poison Ivy"],
    activityTimeline: [
      { date: "2011", event: "Targeted US transportation sector", source: "FBI" },
    ],
    dataSource: "mitre", confidence: 70,
  },
  {
    actorId: "apt7", name: "APT7", aliases: ["Flying Kitten"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting government and military organizations.",
    firstSeen: "2008", lastActive: "2015", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Military", "Defense"],
    targetRegions: ["North America", "Asia"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 2, description: "Phishing links to credential harvesting." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 2, description: "Credential reuse for persistence." },
    ],
    tools: ["Gh0st RAT"],
    malware: ["Gh0st RAT"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 65,
  },
  {
    actorId: "apt8", name: "APT8", aliases: ["Nightshade Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting media, entertainment, and financial services.",
    firstSeen: "2010", lastActive: "2017", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Media", "Entertainment", "Financial Services"],
    targetRegions: ["North America", "Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Targeted phishing campaigns." },
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control", score: 2, description: "HTTP-based C2." },
    ],
    tools: ["Poison Ivy", "BADNEWS"],
    malware: ["BADNEWS"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 65,
  },
  {
    actorId: "apt9", name: "APT9", aliases: ["Flowershop"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese cyber espionage group targeting healthcare and pharmaceutical sectors for intellectual property theft.",
    firstSeen: "2009", lastActive: "2018", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Healthcare", "Pharmaceutical", "Biotechnology"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with healthcare-themed lures." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 2, description: "Credential theft from compromised systems." },
    ],
    tools: ["Poison Ivy", "SOGU"],
    malware: ["SOGU"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 70,
  },
  {
    actorId: "apt10", name: "APT10", aliases: ["Stone Panda", "MenuPass", "Red Apollo", "CVNX", "POTASSIUM"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group known for Operation Cloud Hopper, targeting managed service providers (MSPs) to gain access to their clients' networks. One of the most prolific Chinese APT groups.",
    firstSeen: "2009", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["MSP", "Technology", "Healthcare", "Defense", "Government", "Manufacturing"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1199", name: "Trusted Relationship", tactic: "Initial Access", score: 3, description: "Compromising MSPs to access client networks (supply chain)." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing with weaponized documents." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Mimikatz and custom tools for credential theft." },
      { id: "T1021.001", name: "Remote Desktop Protocol", tactic: "Lateral Movement", score: 3, description: "RDP for lateral movement within MSP networks." },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration", score: 3, description: "Large-scale data exfiltration." },
    ],
    tools: ["PlugX", "QuasarRAT", "RedLeaves", "Mimikatz", "certutil"],
    malware: ["PlugX", "RedLeaves", "UPPERCUT", "ANEL", "ChChes"],
    activityTimeline: [
      { date: "2016", event: "Operation Cloud Hopper targeting MSPs globally", source: "PwC/BAE Systems" },
      { date: "2018", event: "DOJ indictment of two APT10 members", source: "US DOJ" },
      { date: "2024", event: "Continued operations against technology sector", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt12", name: "APT12", aliases: ["IXESHE", "DynCalc", "Numbered Panda", "JoyRAT"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting media, high-tech, and government organizations, particularly those covering East Asian affairs.",
    firstSeen: "2009", lastActive: "2020", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Media", "Technology", "Government"],
    targetRegions: ["North America", "East Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with current events lures." },
      { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution", score: 2, description: "Script-based payload execution." },
    ],
    tools: ["IXESHE", "Etumbot", "HIGHTIDE"],
    malware: ["IXESHE", "Etumbot"],
    activityTimeline: [
      { date: "2012", event: "Targeting New York Times journalists", source: "NYT/Mandiant" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "apt14", name: "APT14", aliases: ["Anchor Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting government and maritime organizations.",
    firstSeen: "2010", lastActive: "2016", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Maritime", "Defense"],
    targetRegions: ["Southeast Asia", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Targeted phishing campaigns." },
      { id: "T1071.001", name: "Web Protocols", tactic: "Command and Control", score: 2, description: "HTTP-based C2 communication." },
    ],
    tools: ["Gh0st RAT", "Poison Ivy"],
    malware: ["Gh0st RAT"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 70,
  },
  {
    actorId: "apt15", name: "APT15", aliases: ["Vixen Panda", "Ke3chang", "NICKEL", "Playful Dragon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting government ministries, diplomatic missions, and international organizations, particularly in Europe and Central/South America.",
    firstSeen: "2010", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Diplomatic", "International Organizations", "Energy"],
    targetRegions: ["Europe", "Central America", "South America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Diplomatic-themed phishing lures." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Stolen credentials for long-term access." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential harvesting from domain controllers." },
    ],
    tools: ["Ketrican", "RoyalDNS", "Okrum", "Mimikatz"],
    malware: ["Ketrican", "RoyalDNS", "Okrum", "BS2005"],
    activityTimeline: [
      { date: "2012", event: "Operation Ke3chang targeting European ministries", source: "FireEye" },
      { date: "2021", event: "Microsoft disrupts NICKEL infrastructure", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt16", name: "APT16", aliases: ["SVCMONDR"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting Japanese and Taiwanese organizations with focus on political and military intelligence.",
    firstSeen: "2010", lastActive: "2018", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Military", "Technology"],
    targetRegions: ["East Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with regional political lures." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 2, description: "Exploiting document viewer vulnerabilities." },
    ],
    tools: ["ELMER", "IRONHALO"],
    malware: ["ELMER", "IRONHALO"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 70,
  },
  {
    actorId: "apt17", name: "APT17", aliases: ["Deputy Dog", "Elderwood", "Sneaky Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group known for using zero-day exploits and watering hole attacks, targeting defense, government, and technology sectors.",
    firstSeen: "2009", lastActive: "2019", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Defense", "Government", "Technology", "Law Firms"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks using compromised websites." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation of browsers." },
      { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution", score: 2, description: "Script-based execution." },
    ],
    tools: ["BLACKCOFFEE", "9002 RAT", "DeputyDog"],
    malware: ["BLACKCOFFEE", "9002 RAT"],
    activityTimeline: [
      { date: "2013", event: "Operation DeputyDog using IE zero-day", source: "FireEye" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt18", name: "APT18", aliases: ["Wekby", "Dynamite Panda", "TG-0416"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting healthcare, technology, and aerospace sectors. Known for rapid exploitation of newly disclosed vulnerabilities.",
    firstSeen: "2009", lastActive: "2020", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Healthcare", "Technology", "Aerospace", "Defense"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Rapid exploitation of new vulnerabilities." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Targeted phishing campaigns." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell for post-exploitation." },
    ],
    tools: ["HTTPBrowser", "Gh0st RAT", "pisloader"],
    malware: ["HTTPBrowser", "pisloader"],
    activityTimeline: [
      { date: "2015", event: "Targeting US healthcare organizations", source: "ThreatConnect" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "apt19", name: "APT19", aliases: ["Codoso", "C0d0so0", "Sunshop Group"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting law firms, investment companies, and technology organizations. Known for sophisticated supply chain attacks.",
    firstSeen: "2010", lastActive: "2019", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Legal", "Financial Services", "Technology", "Mining"],
    targetRegions: ["North America", "Australia"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Supply chain compromise through software updates." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with legal-themed lures." },
      { id: "T1059.005", name: "Visual Basic", tactic: "Execution", score: 2, description: "VBA macros in Office documents." },
    ],
    tools: ["Cobalt Strike", "Derusbi", "Bergard"],
    malware: ["Derusbi", "Bergard"],
    activityTimeline: [
      { date: "2017", event: "Targeting law firms handling sensitive M&A deals", source: "FireEye" },
    ],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "apt20", name: "APT20", aliases: ["Violin Panda", "TH3Bug"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting government, defense, and energy sectors. Known for bypassing 2FA and targeting VPN infrastructure.",
    firstSeen: "2011", lastActive: "2022", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Defense", "Energy", "Aviation"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of web servers and VPN appliances." },
      { id: "T1111", name: "Multi-Factor Authentication Interception", tactic: "Credential Access", score: 3, description: "Bypassing 2FA through token theft." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Using stolen VPN credentials." },
    ],
    tools: ["China Chopper", "Mimikatz", "PowerSploit"],
    malware: ["China Chopper"],
    activityTimeline: [
      { date: "2019", event: "Fox-IT report on APT20 bypassing 2FA", source: "Fox-IT" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt21", name: "APT21", aliases: ["Zhenbao"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting government and military organizations in Southeast Asia.",
    firstSeen: "2011", lastActive: "2017", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Military"],
    targetRegions: ["Southeast Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with political lures." },
    ],
    tools: ["Gh0st RAT", "Travelnet"],
    malware: ["Travelnet"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 65,
  },
  {
    actorId: "apt23", name: "APT23", aliases: ["Pirate Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting media and government organizations in the Philippines and other Southeast Asian countries.",
    firstSeen: "2012", lastActive: "2018", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Media", "Government"],
    targetRegions: ["Southeast Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing targeting journalists and government officials." },
    ],
    tools: ["NONGMIN"],
    malware: ["NONGMIN"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 65,
  },
  {
    actorId: "apt24", name: "APT24", aliases: ["PittyTiger"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting government and military organizations, particularly focused on political intelligence.",
    firstSeen: "2011", lastActive: "2017", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Military", "Defense"],
    targetRegions: ["Europe", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Targeted phishing campaigns." },
      { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution", score: 2, description: "Script-based execution." },
    ],
    tools: ["PittyTiger RAT", "Gh0st RAT"],
    malware: ["PittyTiger RAT"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 65,
  },
  {
    actorId: "apt25", name: "APT25", aliases: ["Uncool", "Volgmer", "Manganese"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting defense and government organizations.",
    firstSeen: "2012", lastActive: "2018", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Defense", "Government"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing with defense-themed lures." },
    ],
    tools: ["LINGBO", "PLAYFUL"],
    malware: ["LINGBO"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 60,
  },
  {
    actorId: "apt26", name: "APT26", aliases: ["Turbine Panda", "Shell Crew"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese espionage group targeting aerospace and defense sectors, linked to theft of C-17 military transport aircraft designs.",
    firstSeen: "2010", lastActive: "2019", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Defense", "Technology"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing of defense contractors." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft for lateral movement." },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration", score: 3, description: "Large-scale IP theft." },
    ],
    tools: ["PlugX", "Sakula", "StreamEx"],
    malware: ["Sakula", "StreamEx"],
    activityTimeline: [
      { date: "2014", event: "Theft of C-17 aircraft designs", source: "US DOJ" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt27", name: "APT27", aliases: ["Emissary Panda", "LuckyMouse", "Iron Tiger", "TG-3390", "Bronze Union"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting government, defense, technology, and energy sectors globally. Known for sophisticated supply chain attacks and exploitation of web applications.",
    firstSeen: "2010", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Defense", "Technology", "Energy", "Aerospace"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of SharePoint, Exchange, and web servers." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for post-exploitation." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential harvesting with Mimikatz." },
      { id: "T1021.002", name: "SMB/Windows Admin Shares", tactic: "Lateral Movement", score: 3, description: "Lateral movement via admin shares." },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration", score: 3, description: "Data exfiltration through C2." },
    ],
    tools: ["SysUpdate", "HyperBro", "PlugX", "China Chopper", "Mimikatz"],
    malware: ["SysUpdate", "HyperBro", "PlugX"],
    activityTimeline: [
      { date: "2015", event: "Operation Iron Tiger targeting US defense contractors", source: "Trend Micro" },
      { date: "2020", event: "Exploitation of ProxyLogon Exchange vulnerabilities", source: "ESET" },
      { date: "2024", event: "German BfV warns of APT27 targeting German companies", source: "BfV" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt28", name: "APT28", aliases: ["Fancy Bear", "Sofacy", "Pawn Storm", "Sednit", "STRONTIUM", "Forest Blizzard"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian military intelligence (GRU Unit 26165) cyber espionage group, one of the most active and well-known threat actors globally. Responsible for DNC hack, WADA breach, and numerous government targeting campaigns.",
    firstSeen: "2004", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Defense", "Media", "Political Organizations", "International Organizations"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Weaponized documents exploiting Office vulnerabilities." },
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential harvesting phishing pages." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation of web applications." },
      { id: "T1068", name: "Exploitation for Privilege Escalation", tactic: "Privilege Escalation", score: 3, description: "Kernel and application exploits for escalation." },
      { id: "T1562", name: "Impair Defenses", tactic: "Defense Evasion", score: 3, description: "Disabling security tools and logging." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Mimikatz and custom credential theft tools." },
    ],
    tools: ["X-Agent", "X-Tunnel", "Zebrocy", "Mimikatz", "Responder", "Cobalt Strike"],
    malware: ["X-Agent", "X-Tunnel", "Zebrocy", "Seduploader", "CHOPSTICK"],
    activityTimeline: [
      { date: "2014", event: "Targeting Ukrainian military with X-Agent Android malware", source: "CrowdStrike" },
      { date: "2016", event: "DNC hack and election interference operations", source: "CrowdStrike/FBI" },
      { date: "2018", event: "WADA and anti-doping agency targeting", source: "Microsoft" },
      { date: "2024", event: "Continued targeting of NATO countries", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "apt29", name: "APT29", aliases: ["Cozy Bear", "The Dukes", "NOBELIUM", "Midnight Blizzard", "YTTRIUM"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian intelligence service (SVR) cyber espionage group responsible for SolarWinds supply chain attack, targeting government, diplomatic, think tank, and technology organizations worldwide.",
    firstSeen: "2008", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Diplomatic", "Think Tanks", "Technology", "Healthcare"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "SolarWinds Orion supply chain compromise." },
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Targeted phishing with credential harvesting." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Cloud account compromise and token theft." },
      { id: "T1550.001", name: "Application Access Token", tactic: "Lateral Movement", score: 3, description: "OAuth token abuse for cloud lateral movement." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "LSASS dumping and NTDS.dit extraction." },
      { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration", score: 3, description: "Stealthy data exfiltration." },
    ],
    tools: ["SUNBURST", "TEARDROP", "Cobalt Strike", "Mimikatz", "EnvyScout"],
    malware: ["SUNBURST", "TEARDROP", "RAINDROP", "WellMess", "WellMail", "EnvyScout"],
    activityTimeline: [
      { date: "2015", event: "Compromise of DNC networks", source: "CrowdStrike" },
      { date: "2020", event: "SolarWinds supply chain attack affecting 18,000+ organizations", source: "FireEye/Microsoft" },
      { date: "2023", event: "Microsoft corporate email compromise via OAuth abuse", source: "Microsoft" },
      { date: "2024", event: "Targeting diplomatic entities across Europe", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "apt30", name: "APT30", aliases: ["Naikon", "Override Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting ASEAN countries and India for political and military intelligence. One of the longest-running APT campaigns.",
    firstSeen: "2005", lastActive: "2023", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Diplomatic", "Media"],
    targetRegions: ["Southeast Asia", "South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with geopolitical lures." },
      { id: "T1091", name: "Replication Through Removable Media", tactic: "Lateral Movement", score: 2, description: "USB-based malware propagation." },
      { id: "T1025", name: "Data from Removable Media", tactic: "Collection", score: 2, description: "Stealing data from air-gapped networks via USB." },
    ],
    tools: ["BACKSPACE", "NETEAGLE", "SHIPSHAPE"],
    malware: ["BACKSPACE", "NETEAGLE", "FLASHFLOOD"],
    activityTimeline: [
      { date: "2015", event: "FireEye report on decade-long APT30 campaign", source: "FireEye" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt31", name: "APT31", aliases: ["Zirconium", "Judgment Panda", "Violet Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group targeting government, international affairs, and technology sectors. Known for targeting political campaigns and government officials.",
    firstSeen: "2010", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Political Organizations", "Technology", "International Affairs"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Phishing links to credential harvesting." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of web applications and routers." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell-based payloads." },
    ],
    tools: ["RAWDOOR", "Cobalt Strike", "China Chopper"],
    malware: ["RAWDOOR"],
    activityTimeline: [
      { date: "2020", event: "Targeting US presidential campaign staff", source: "Google TAG" },
      { date: "2024", event: "DOJ indictment of APT31 members", source: "US DOJ" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt32", name: "APT32", aliases: ["OceanLotus", "Ocean Buffalo", "SeaLotus", "Canvas Cyclone"],
    type: "apt", origin: "Vietnam", motivation: "Espionage",
    description: "Vietnamese state-sponsored group targeting private sector companies, foreign governments, journalists, and dissidents. Known for sophisticated social engineering and custom malware.",
    firstSeen: "2012", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Media", "Manufacturing", "Technology", "Hospitality"],
    targetRegions: ["Southeast Asia", "North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Sophisticated phishing with social engineering." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks on targeted websites." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for payload delivery and execution." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 3, description: "DLL injection and process hollowing." },
    ],
    tools: ["Cobalt Strike", "METALJACK", "KERRDOWN", "Denis"],
    malware: ["METALJACK", "KERRDOWN", "Denis", "SOUNDBITE"],
    activityTimeline: [
      { date: "2017", event: "Targeting multinational corporations in Vietnam", source: "FireEye" },
      { date: "2020", event: "COVID-19 themed campaigns against Chinese targets", source: "FireEye" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt33", name: "APT33", aliases: ["Elfin", "Magnallium", "Refined Kitten", "Peach Sandstorm", "HOLMIUM"],
    type: "apt", origin: "Iran", motivation: "Espionage / Disruption",
    description: "Iranian state-sponsored group targeting aerospace, energy, and petrochemical sectors. Known for destructive attacks using wiper malware and password spraying campaigns.",
    firstSeen: "2013", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Energy", "Petrochemical", "Defense", "Government"],
    targetRegions: ["Middle East", "North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Phishing with job recruitment lures." },
      { id: "T1110.003", name: "Password Spraying", tactic: "Credential Access", score: 3, description: "Large-scale password spraying campaigns." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Wiper malware deployment." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "Shamoon-style destructive attacks." },
    ],
    tools: ["Shamoon", "TURNEDUP", "NANOCORE", "Ruler"],
    malware: ["Shamoon", "TURNEDUP", "STONEDRILL"],
    activityTimeline: [
      { date: "2017", event: "Targeting Saudi Arabian and US organizations", source: "FireEye" },
      { date: "2023", event: "Password spraying against defense organizations", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt34", name: "APT34", aliases: ["OilRig", "Helix Kitten", "Hazel Sandstorm", "CHRYSENE"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian state-sponsored group targeting government, financial, energy, and telecommunications sectors primarily in the Middle East. Known for DNS tunneling and custom backdoors.",
    firstSeen: "2014", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Financial Services", "Energy", "Telecommunications", "Chemical"],
    targetRegions: ["Middle East", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Macro-enabled documents for initial access." },
      { id: "T1071.004", name: "DNS", tactic: "Command and Control", score: 3, description: "DNS tunneling for C2 communication." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential harvesting tools." },
      { id: "T1053.005", name: "Scheduled Task", tactic: "Persistence", score: 2, description: "Scheduled tasks for persistence." },
    ],
    tools: ["BONDUPDATER", "QUADAGENT", "POWRUNER", "Mimikatz"],
    malware: ["BONDUPDATER", "QUADAGENT", "POWRUNER", "VALUEVAULT"],
    activityTimeline: [
      { date: "2019", event: "Tools and infrastructure leaked on Telegram", source: "Lab Dookhtegan" },
      { date: "2023", event: "Targeting Middle Eastern government networks", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt35", name: "APT35", aliases: ["Charming Kitten", "Phosphorus", "Mint Sandstorm", "TA453", "Newscaster"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian state-sponsored group (IRGC-linked) targeting academics, journalists, diplomats, and human rights activists. Known for sophisticated social engineering and credential phishing.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Academic", "Media", "Human Rights", "Defense"],
    targetRegions: ["Middle East", "North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Sophisticated credential phishing impersonating journalists." },
      { id: "T1534", name: "Internal Spearphishing", tactic: "Lateral Movement", score: 3, description: "Using compromised accounts to phish colleagues." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Credential reuse and account takeover." },
    ],
    tools: ["HYPERSCRAPE", "BASICSTAR", "PowerLess", "CharmPower"],
    malware: ["HYPERSCRAPE", "BASICSTAR", "PowerLess", "CharmPower"],
    activityTimeline: [
      { date: "2019", event: "Targeting US presidential campaign", source: "Microsoft" },
      { date: "2022", event: "HYPERSCRAPE tool for Gmail/Yahoo/Outlook theft", source: "Google TAG" },
      { date: "2024", event: "Targeting Middle East policy researchers", source: "Mandiant" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "apt36", name: "APT36", aliases: ["Transparent Tribe", "Mythic Leopard", "ProjectM", "COPPER FIELDSTONE"],
    type: "apt", origin: "Pakistan", motivation: "Espionage",
    description: "Pakistani state-sponsored group primarily targeting Indian military and government organizations. Known for using CrimsonRAT and social engineering via fake dating apps.",
    firstSeen: "2013", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Military", "Government", "Defense", "Education"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with military-themed documents." },
      { id: "T1204.002", name: "Malicious File", tactic: "Execution", score: 3, description: "Trojanized applications and documents." },
      { id: "T1113", name: "Screen Capture", tactic: "Collection", score: 2, description: "Screenshot capture for intelligence." },
    ],
    tools: ["CrimsonRAT", "ObliqueRAT", "CapraRAT"],
    malware: ["CrimsonRAT", "ObliqueRAT", "CapraRAT"],
    activityTimeline: [
      { date: "2019", event: "Targeting Indian military with fake dating apps", source: "Kaspersky" },
      { date: "2023", event: "CapraRAT targeting Indian government officials", source: "SentinelOne" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt37", name: "APT37", aliases: ["Reaper", "ScarCruft", "Group123", "Ricochet Chollima", "InkySquid"],
    type: "apt", origin: "North Korea", motivation: "Espionage",
    description: "North Korean state-sponsored group targeting South Korea, Japan, and organizations involved in North Korean affairs. Known for zero-day exploitation and destructive capabilities.",
    firstSeen: "2012", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Media", "Chemical", "Manufacturing"],
    targetRegions: ["East Asia", "Middle East"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with Korean-language lures." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks on Korean websites." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 2, description: "Process injection for evasion." },
    ],
    tools: ["ROKRAT", "BLUELIGHT", "Dolphin", "GOLDBACKDOOR"],
    malware: ["ROKRAT", "BLUELIGHT", "Dolphin", "GOLDBACKDOOR", "Konni"],
    activityTimeline: [
      { date: "2017", event: "Zero-day exploitation of Adobe Flash", source: "FireEye" },
      { date: "2023", event: "Targeting North Korean defectors and journalists", source: "AhnLab" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt38", name: "APT38", aliases: ["Lazarus Group", "HIDDEN COBRA", "Zinc", "Diamond Sleet", "Labyrinth Chollima"],
    type: "apt", origin: "North Korea", motivation: "Financial / Espionage",
    description: "North Korean state-sponsored group (RGB) responsible for some of the largest cyber heists in history, including the Bangladesh Bank SWIFT attack ($81M) and cryptocurrency theft totaling billions. Also conducts espionage operations.",
    firstSeen: "2009", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Financial Services", "Cryptocurrency", "Government", "Defense", "Entertainment"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing of financial sector employees." },
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Supply chain attacks (3CX, npm packages)." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for payload delivery." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "WannaCry ransomware deployment." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Destructive wiper attacks (Sony Pictures)." },
      { id: "T1565.001", name: "Stored Data Manipulation", tactic: "Impact", score: 3, description: "SWIFT transaction manipulation." },
    ],
    tools: ["FALLCHILL", "Manuscrypt", "HOPLIGHT", "Mimikatz", "Cobalt Strike"],
    malware: ["WannaCry", "FALLCHILL", "Manuscrypt", "HOPLIGHT", "DTrack", "BLINDINGCAN"],
    activityTimeline: [
      { date: "2014", event: "Sony Pictures Entertainment hack", source: "FBI" },
      { date: "2016", event: "Bangladesh Bank SWIFT heist ($81M stolen)", source: "BAE Systems" },
      { date: "2017", event: "WannaCry global ransomware outbreak", source: "NSA/CISA" },
      { date: "2022", event: "Ronin Network cryptocurrency theft ($620M)", source: "FBI" },
      { date: "2024", event: "Continued cryptocurrency exchange targeting", source: "FBI" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "apt39", name: "APT39", aliases: ["Chafer", "Remix Kitten", "Cotton Sandstorm"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian state-sponsored group (MOIS-linked) targeting telecommunications and travel industries to track individuals of interest to the Iranian government.",
    firstSeen: "2014", lastActive: "2023", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Telecommunications", "Travel", "Government", "Technology"],
    targetRegions: ["Middle East", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing targeting telecom employees." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell for post-exploitation." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft from telecom infrastructure." },
    ],
    tools: ["Remexi", "SEAWEED", "CACHEMONEY", "Mimikatz"],
    malware: ["Remexi", "SEAWEED", "CACHEMONEY"],
    activityTimeline: [
      { date: "2019", event: "FBI indictment of APT39 members", source: "FBI" },
    ],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt40", name: "APT40", aliases: ["Leviathan", "TEMP.Periscope", "TEMP.Jumper", "Kryptonite Panda", "Gingham Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese state-sponsored group (MSS Hainan) targeting maritime, defense, aviation, and government organizations. Known for rapid exploitation of newly disclosed vulnerabilities.",
    firstSeen: "2009", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Maritime", "Defense", "Aviation", "Government", "Technology", "Research"],
    targetRegions: ["Southeast Asia", "North America", "Europe", "Oceania"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Rapid exploitation of new CVEs." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with maritime/defense lures." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for execution." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential harvesting." },
    ],
    tools: ["AIRBREAK", "MURKYTOP", "China Chopper", "Cobalt Strike", "Mimikatz"],
    malware: ["AIRBREAK", "MURKYTOP", "PHOTO", "BADFLICK"],
    activityTimeline: [
      { date: "2021", event: "DOJ indictment of APT40 members", source: "US DOJ" },
      { date: "2024", event: "CISA advisory on APT40 rapid exploitation techniques", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt41", name: "APT41", aliases: ["Double Dragon", "Winnti", "Barium", "Wicked Panda", "Brass Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage / Financial",
    description: "Chinese state-sponsored group unique for conducting both espionage and financially motivated operations. Targets healthcare, telecom, technology, and gaming sectors. Known for supply chain attacks.",
    firstSeen: "2012", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Technology", "Healthcare", "Telecommunications", "Gaming", "Government", "Financial Services"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Supply chain attacks through software vendors." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Exploitation of Citrix, Cisco, Zoho vulnerabilities." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell for execution and persistence." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft with custom tools." },
      { id: "T1005", name: "Data from Local System", tactic: "Collection", score: 3, description: "Data collection from compromised systems." },
    ],
    tools: ["ShadowPad", "Winnti", "PlugX", "Cobalt Strike", "Mimikatz", "DEADEYE"],
    malware: ["ShadowPad", "Winnti", "PlugX", "DEADEYE", "DUSTPAN", "DUSTTRAP"],
    activityTimeline: [
      { date: "2019", event: "Supply chain attacks on gaming companies", source: "ESET" },
      { date: "2020", event: "DOJ indictment of five APT41 members", source: "US DOJ" },
      { date: "2022", event: "Targeting US state government networks", source: "Mandiant" },
      { date: "2024", event: "Continued global espionage operations", source: "CISA" },
    ],
    dataSource: "mitre", confidence: 95,
  },
];

export { APT_GROUPS };
