// Part 4: Bulk additional threat actors - more APTs, cybercrime, and emerging groups
import type { SeedThreatActor } from "./threatActorSeed";

// Helper to create actors with minimal boilerplate
function actor(
  id: string, name: string, aliases: string[], type: SeedThreatActor["type"],
  origin: string, motivation: string, description: string,
  firstSeen: string, lastActive: string, threatLevel: SeedThreatActor["threatLevel"],
  sophistication: SeedThreatActor["sophistication"],
  sectors: string[], regions: string[],
  techniques: SeedThreatActor["techniques"],
  tools: string[], malware: string[],
  timeline: SeedThreatActor["activityTimeline"] = [],
  source: SeedThreatActor["dataSource"] = "mitre", confidence = 75
): SeedThreatActor {
  return {
    actorId: id, name, aliases, type, origin, motivation, description,
    firstSeen, lastActive, threatLevel, sophistication,
    targetSectors: sectors, targetRegions: regions, techniques,
    tools, malware, activityTimeline: timeline, dataSource: source, confidence,
  };
}

// T = technique shorthand
function t(id: string, name: string, tactic: string, score = 2, desc = ""): SeedThreatActor["techniques"][0] {
  return { id, name, tactic, score, description: desc || name };
}

// ============================================================
// BATCH 1: More Chinese Groups
// ============================================================
const BATCH_CHINESE: SeedThreatActor[] = [
  actor("apt2", "APT2", ["Putter Panda", "MSUpdater"], "apt", "China", "Espionage",
    "Chinese PLA-linked group targeting space, satellite, and defense technology.", "2007", "2015", "medium", "nation-state",
    ["Aerospace", "Defense", "Technology"], ["North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["MOOSE", "4H RAT"], ["MOOSE", "4H RAT"]),
  actor("apt5", "APT5", ["Keyhole Panda", "MANGANESE"], "apt", "China", "Espionage",
    "Chinese group targeting telecommunications and technology sectors, particularly Citrix and Pulse Secure VPNs.", "2007", "2024", "high", "nation-state",
    ["Telecommunications", "Technology", "Defense"], ["Southeast Asia", "North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3, "VPN appliance exploitation")], ["BLOODMINE", "THINSPOOL"], ["BLOODMINE"]),
  actor("apt6", "APT6", ["1.php Group"], "apt", "China", "Espionage",
    "Chinese group targeting government and commercial networks.", "2008", "2016", "medium", "nation-state",
    ["Government", "Technology"], ["North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 2)], ["Poison Ivy", "Gh0st RAT"], ["Poison Ivy"]),
  actor("apt9", "APT9", ["Flowershop"], "apt", "China", "Espionage",
    "Chinese group targeting healthcare and pharmaceutical sectors for IP theft.", "2009", "2018", "medium", "nation-state",
    ["Healthcare", "Pharmaceutical"], ["North America", "Southeast Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["Poison Ivy", "PlugX"], ["Poison Ivy"]),
  actor("apt12", "APT12", ["IXESHE", "DynCalc", "Numbered Panda", "JoyRAT"], "apt", "China", "Espionage",
    "Chinese group targeting media, government, and defense organizations.", "2009", "2018", "medium", "nation-state",
    ["Media", "Government", "Defense"], ["East Asia", "North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["IXESHE", "Etumbot"], ["IXESHE", "Etumbot"]),
  actor("apt14", "APT14", ["QAZTeam"], "apt", "China", "Espionage",
    "Chinese group targeting government organizations.", "2010", "2016", "medium", "nation-state",
    ["Government"], ["North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["Gh0st RAT"], ["Gh0st RAT"]),
  actor("apt15", "APT15", ["Vixen Panda", "Ke3chang", "Nickel", "Playful Dragon", "Royal APT"], "apt", "China", "Espionage",
    "Chinese MSS-linked group targeting government and diplomatic organizations in Europe and the Americas.", "2010", "2024", "high", "nation-state",
    ["Government", "Diplomatic", "Energy"], ["Europe", "Latin America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1505.003", "Web Shell", "Persistence", 3)],
    ["Ketrican", "Okrum", "RoyalDNS"], ["Ketrican", "Okrum"]),
  actor("apt16", "APT16", ["EPS Team"], "apt", "China", "Espionage",
    "Chinese group targeting Japanese and Taiwanese organizations.", "2010", "2016", "medium", "intermediate",
    ["Government", "Technology"], ["East Asia"],
    [t("T1203", "Exploitation for Client Execution", "Execution", 2)], ["ELMER", "IRONHALO"], ["ELMER"]),
  actor("apt18", "APT18", ["Wekby", "Dynamite Panda", "TG-0416"], "apt", "China", "Espionage",
    "Chinese group targeting healthcare, technology, and aerospace sectors.", "2009", "2017", "medium", "nation-state",
    ["Healthcare", "Technology", "Aerospace"], ["North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["Gh0st RAT", "HTTPBrowser"], ["Gh0st RAT"]),
  actor("apt20", "APT20", ["Violin Panda", "TH3Bug"], "apt", "China", "Espionage",
    "Chinese group targeting government and defense sectors.", "2011", "2020", "medium", "nation-state",
    ["Government", "Defense", "Energy"], ["North America", "Europe"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["Poison Ivy", "PlugX"], ["Poison Ivy"]),
  actor("apt21", "APT21", ["Zhenbao", "Hammer Panda"], "apt", "China", "Espionage",
    "Chinese group targeting government organizations.", "2011", "2017", "medium", "nation-state",
    ["Government", "Diplomatic"], ["North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["Travelnet", "Sogu"], ["Travelnet"]),
  actor("apt22", "APT22", ["Barista", "Group 46"], "apt", "China", "Espionage",
    "Chinese group targeting political and military organizations in East Asia.", "2012", "2019", "medium", "nation-state",
    ["Political", "Military"], ["East Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["PISCES", "SOGU"], ["PISCES"]),
  actor("apt23", "APT23", ["Pirate Panda", "Tropic Trooper", "KeyBoy"], "apt", "China", "Espionage",
    "Chinese group targeting government, military, and healthcare in Taiwan and the Philippines.", "2011", "2024", "high", "nation-state",
    ["Government", "Military", "Healthcare"], ["East Asia", "Southeast Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1059.001", "PowerShell", "Execution", 2)],
    ["Yahoyah", "TClient", "USBferry"], ["Yahoyah", "USBferry"]),
  actor("apt24", "APT24", ["PittyTiger"], "apt", "China", "Espionage",
    "Chinese group targeting government and defense sectors.", "2009", "2015", "medium", "intermediate",
    ["Government", "Defense", "Telecommunications"], ["North America", "Europe"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["Gh0st RAT", "PittyTiger"], ["PittyTiger"]),
  actor("apt25", "APT25", ["Uncool", "Vixen Panda (partial)", "Trefoil"], "apt", "China", "Espionage",
    "Chinese group targeting defense and media organizations.", "2010", "2016", "medium", "intermediate",
    ["Defense", "Media"], ["North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["LINGBO", "PLAYFUL"], ["LINGBO"]),
  actor("apt26", "APT26", ["Turbine Panda", "Shell Crew (partial)"], "apt", "China", "Espionage",
    "Chinese group targeting aerospace and defense for IP theft.", "2010", "2018", "high", "nation-state",
    ["Aerospace", "Defense", "Technology"], ["North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["HUC Packet Transmitter", "PlugX"], ["PlugX"]),
  actor("apt37", "APT37", ["Reaper", "ScarCruft", "Group123", "Ricochet Chollima", "InkySquid"], "apt", "North Korea", "Espionage",
    "North Korean group targeting South Korean government, military, and defectors. Also targets Japan and Middle East.", "2012", "2025", "high", "nation-state",
    ["Government", "Military", "Media", "Defectors"], ["East Asia", "Middle East"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1189", "Drive-by Compromise", "Initial Access", 3)],
    ["ROKRAT", "BLUELIGHT", "Dolphin", "Konni"], ["ROKRAT", "BLUELIGHT", "Dolphin"],
    [{ date: "2023", event: "Targeting North Korean defectors with new malware", source: "AhnLab" }], "mitre", 90),
  actor("blacktech", "BlackTech", ["Palmerworm", "Manga Taurus", "Circuit Panda", "Radio Panda"], "apt", "China", "Espionage",
    "Chinese group targeting technology and government in East Asia, known for router firmware modification.", "2010", "2024", "high", "nation-state",
    ["Technology", "Government", "Telecommunications", "Defense"], ["East Asia", "North America"],
    [t("T1542.004", "ROMMONkit", "Defense Evasion", 3, "Router firmware modification"), t("T1199", "Trusted Relationship", "Initial Access", 3)],
    ["Waterbear", "Plead", "TSCookie"], ["Waterbear", "Plead"],
    [{ date: "2023", event: "CISA advisory on BlackTech router firmware modification", source: "CISA/NSA" }], "mitre", 88),
  actor("earth-estries", "Earth Estries", ["Salt Typhoon (partial)", "FamousSparrow", "GhostEmperor"], "apt", "China", "Espionage",
    "Chinese group targeting government and technology sectors with sophisticated backdoors.", "2020", "2025", "high", "nation-state",
    ["Government", "Technology", "Telecommunications"], ["Southeast Asia", "North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["HemiGate", "Zingdoor", "TrillClient"], ["HemiGate", "Zingdoor"]),
  actor("tonto-team", "Tonto Team", ["CactusPete", "Karma Panda", "Earth Akhlut"], "apt", "China", "Espionage",
    "Chinese PLA-linked group targeting military, government, and technology in Russia, Japan, and South Korea.", "2009", "2024", "high", "nation-state",
    ["Military", "Government", "Technology"], ["East Asia", "Russia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["Bisonal", "Dexbia", "ShadowPad"], ["Bisonal", "Dexbia"]),
];

// ============================================================
// BATCH 2: More Iranian, Turkish, and Middle Eastern Groups
// ============================================================
const BATCH_MENA: SeedThreatActor[] = [
  actor("oilrig-ext", "Lyceum", ["Hexane", "Spirlin", "SIAMESEKITTEN"], "apt", "Iran", "Espionage",
    "Iranian group targeting telecommunications, ISPs, and energy sectors in the Middle East and Africa.", "2017", "2024", "high", "advanced",
    ["Telecommunications", "Energy", "ISP"], ["Middle East", "Africa"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1071.004", "DNS", "Command and Control", 3)],
    ["DanBot", "Shark", "Milan"], ["DanBot", "Shark"]),
  actor("tortoiseshell", "Tortoiseshell", ["Imperial Kitten", "Crimson Sandstorm", "TA456"], "apt", "Iran", "Espionage",
    "Iranian IRGC-linked group targeting defense contractors and IT providers through supply chain attacks.", "2018", "2024", "high", "advanced",
    ["Defense", "IT Services", "Aerospace"], ["North America", "Middle East"],
    [t("T1195.002", "Compromise Software Supply Chain", "Initial Access", 3), t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)],
    ["IMAPLoader", "LEMPO"], ["IMAPLoader"]),
  actor("pioneer-kitten", "Pioneer Kitten", ["Fox Kitten", "Parisite", "RUBIDIUM", "Lemon Sandstorm"], "apt", "Iran", "Espionage / Financial",
    "Iranian group exploiting VPN vulnerabilities and selling access to ransomware affiliates.", "2017", "2025", "high", "advanced",
    ["Technology", "Government", "Defense", "Healthcare"], ["North America", "Middle East"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3, "VPN and firewall exploitation")],
    ["Custom web shells", "Chisel", "Ligolo"], [],
    [{ date: "2024", event: "FBI advisory on selling access to ransomware groups", source: "FBI/CISA" }], "osint", 85),
  actor("sea-turtle", "Sea Turtle", ["Teal Kurma", "Cosmic Wolf", "Marbled Dust"], "apt", "Turkey", "Espionage",
    "Turkish government-linked group conducting DNS hijacking campaigns against government and telecom targets.", "2017", "2024", "high", "nation-state",
    ["Government", "Telecommunications", "DNS Registrars"], ["Middle East", "Europe"],
    [t("T1584.002", "DNS Server", "Resource Development", 3, "DNS hijacking"), t("T1557", "Adversary-in-the-Middle", "Collection", 3)],
    ["SnappyTCP"], ["SnappyTCP"],
    [{ date: "2023", event: "Targeting Kurdish political websites", source: "PwC" }], "osint", 80),
  actor("mabna-institute", "Mabna Institute", ["Silent Librarian", "TA407", "Cobalt Dickens"], "apt", "Iran", "Espionage",
    "Iranian group conducting massive credential theft against universities worldwide to steal academic research.", "2013", "2024", "high", "intermediate",
    ["Academic", "Research", "Government"], ["Global"],
    [t("T1566.002", "Spearphishing Link", "Initial Access", 3, "University credential phishing")],
    ["Custom phishing kits"], [],
    [{ date: "2018", event: "Nine members indicted by US DOJ", source: "US DOJ" }], "osint", 88),
  actor("ta410", "TA410", ["FlowingFrog", "LookingFrog", "JollyFrog"], "apt", "China", "Espionage",
    "Chinese group targeting US utilities and government organizations.", "2018", "2023", "high", "nation-state",
    ["Utilities", "Government", "Diplomatic"], ["North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["FlowCloud", "LookBack"], ["FlowCloud", "LookBack"]),
  actor("ta413", "TA413", ["LuckyCat", "Earth Berberoka"], "apt", "China", "Espionage",
    "Chinese group targeting Tibetan organizations and dissidents.", "2012", "2024", "medium", "nation-state",
    ["NGO", "Religious", "Government"], ["East Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["Sepulcher", "ExileRAT"], ["Sepulcher", "ExileRAT"]),
  actor("ta416", "TA416", ["RedDelta", "Mustang Panda (partial)"], "apt", "China", "Espionage",
    "Chinese group targeting European diplomatic entities and Vatican.", "2014", "2024", "high", "nation-state",
    ["Diplomatic", "Religious", "Government"], ["Europe", "Southeast Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1574.002", "DLL Side-Loading", "Defense Evasion", 3)],
    ["PlugX", "Poison Ivy"], ["PlugX"]),
  actor("ta428", "TA428", ["Colourful Panda", "PinkMen"], "apt", "China", "Espionage",
    "Chinese group targeting defense and government in Russia and East Asia.", "2013", "2023", "high", "nation-state",
    ["Defense", "Government", "Aerospace"], ["Russia", "East Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["Cotx RAT", "DNSep"], ["Cotx RAT"]),
  actor("ta459", "TA459", ["Tick", "Bronze Butler", "REDBALDKNIGHT"], "apt", "China", "Espionage",
    "Chinese group targeting Japanese organizations for IP theft.", "2006", "2023", "high", "nation-state",
    ["Technology", "Defense", "Government"], ["East Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)],
    ["Daserf", "xxmm", "Datper"], ["Daserf", "Datper"]),
];

// ============================================================
// BATCH 3: More Cybercrime and Access Brokers
// ============================================================
const BATCH_CYBERCRIME: SeedThreatActor[] = [
  actor("fin4", "FIN4", ["Wolf Spider"], "cybercrime", "Unknown", "Financial",
    "Group targeting pharmaceutical and healthcare companies for insider trading information.", "2013", "2019", "high", "advanced",
    ["Pharmaceutical", "Healthcare", "Financial Services"], ["North America"],
    [t("T1566.002", "Spearphishing Link", "Initial Access", 3, "Credential phishing for M&A intel")],
    ["Custom phishing tools"], []),
  actor("fin5", "FIN5", [], "cybercrime", "Unknown", "Financial",
    "Group targeting POS systems in casinos and hospitality.", "2008", "2019", "medium", "advanced",
    ["Hospitality", "Gaming", "Retail"], ["North America"],
    [t("T1078", "Valid Accounts", "Persistence", 3, "Stolen RDP credentials")], ["FlawedAmmyy", "ServHelper"], ["FlawedAmmyy"]),
  actor("fin6", "FIN6", ["Skeleton Spider", "ITG08", "Magecart Group 6"], "cybercrime", "Unknown", "Financial",
    "Group targeting POS systems and e-commerce for payment card theft. Linked to Magecart and ransomware operations.", "2015", "2023", "high", "advanced",
    ["Retail", "Hospitality", "E-commerce"], ["North America", "Europe"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1005", "Data from Local System", "Collection", 3, "POS memory scraping")],
    ["FrameworkPOS", "Cobalt Strike", "Metasploit", "Ryuk"], ["FrameworkPOS", "TRINITY"]),
  actor("fin9", "FIN9", [], "cybercrime", "Vietnam", "Financial",
    "Vietnamese cybercrime group targeting technology and financial sectors.", "2018", "2024", "medium", "intermediate",
    ["Technology", "Financial Services", "Retail"], ["North America"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 2)], ["Custom tools"], [],
    [{ date: "2024", event: "Four members indicted by US DOJ", source: "US DOJ" }], "osint", 72),
  actor("fin10", "FIN10", [], "cybercrime", "Unknown", "Financial",
    "Group conducting extortion against casinos and mining companies in North America.", "2013", "2018", "medium", "intermediate",
    ["Mining", "Gaming", "Technology"], ["North America"],
    [t("T1059.001", "PowerShell", "Execution", 2)], ["SplinterRAT", "Meterpreter"], ["SplinterRAT"]),
  actor("fin13", "FIN13", ["Elephant Beetle"], "cybercrime", "Mexico", "Financial",
    "Latin American cybercrime group conducting long-term financial fraud against large corporations.", "2016", "2023", "high", "advanced",
    ["Financial Services", "Retail", "Manufacturing"], ["Latin America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3), t("T1565.001", "Stored Data Manipulation", "Impact", 3, "Financial transaction manipulation")],
    ["Custom Java tools", "Cobalt Strike"], []),
  actor("ta551", "TA551", ["Shathak", "Gold Cabin"], "cybercrime", "Unknown", "Financial",
    "Malware distribution group using thread-hijacked email campaigns to deliver banking trojans and ransomware.", "2016", "2024", "high", "intermediate",
    ["Financial Services", "Manufacturing", "Technology"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3, "Thread-hijacked email campaigns")],
    ["IcedID", "QakBot", "Ursnif"], ["IcedID", "QakBot"]),
  actor("ta577", "TA577", [], "cybercrime", "Unknown", "Financial",
    "Prolific initial access broker distributing QakBot and Pikabot malware.", "2020", "2025", "high", "intermediate",
    ["Various"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["QakBot", "Pikabot"], ["QakBot", "Pikabot"]),
  actor("ta578", "TA578", [], "cybercrime", "Unknown", "Financial",
    "Initial access broker using contact form spam and callback phishing.", "2020", "2024", "medium", "intermediate",
    ["Various"], ["North America"],
    [t("T1566.002", "Spearphishing Link", "Initial Access", 3)], ["BazarLoader", "BumbleBee"], ["BumbleBee"]),
  actor("ta580", "TA580", ["Storm-0324"], "cybercrime", "Unknown", "Financial",
    "Initial access broker distributing JSSLoader and handing off to ransomware operators.", "2019", "2024", "high", "intermediate",
    ["Various"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["JSSLoader", "Gozi"], ["JSSLoader"]),
  actor("ta569", "TA569", ["Gold Prelude", "SocGholish"], "cybercrime", "Unknown", "Financial",
    "Group operating SocGholish/FakeUpdates malware through compromised websites.", "2017", "2025", "high", "intermediate",
    ["Various"], ["Global"],
    [t("T1189", "Drive-by Compromise", "Initial Access", 3, "Fake browser update prompts")],
    ["SocGholish", "BLISTER"], ["SocGholish"]),
  actor("emotet-op", "Emotet Operators", ["TA542", "Mummy Spider", "GOLD CRESTWOOD"], "cybercrime", "Ukraine/Russia", "Financial",
    "Operators of the Emotet botnet, one of the most prolific malware distribution networks. Disrupted in 2021, returned in 2022.", "2014", "2023", "critical", "advanced",
    ["Various"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3, "Massive spam campaigns"), t("T1059.005", "Visual Basic", "Execution", 3)],
    ["Emotet", "Cobalt Strike"], ["Emotet"],
    [{ date: "2021", event: "Emotet infrastructure taken down by Europol", source: "Europol" }, { date: "2022", event: "Emotet returns", source: "Multiple" }], "osint", 95),
  actor("trickbot-op", "TrickBot Operators", ["ITG23", "GOLD BLACKBURN (partial)"], "cybercrime", "Russia", "Financial",
    "Operators of the TrickBot banking trojan and botnet, one of the largest cybercrime operations.", "2016", "2022", "critical", "advanced",
    ["Financial Services", "Healthcare", "Government"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)],
    ["TrickBot", "BazarLoader", "Anchor"], ["TrickBot", "BazarLoader", "Anchor"],
    [{ date: "2022", event: "TrickBot infrastructure shut down", source: "Multiple" }], "osint", 92),
  actor("qakbot-op", "QakBot Operators", ["Gold Lagoon", "TA570"], "cybercrime", "Unknown", "Financial",
    "Operators of the QakBot/Qbot banking trojan, a major initial access vector for ransomware.", "2008", "2024", "high", "advanced",
    ["Various"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)],
    ["QakBot", "Cobalt Strike"], ["QakBot"],
    [{ date: "2023", event: "FBI disrupts QakBot infrastructure", source: "FBI" }], "osint", 90),
  actor("gootloader-op", "GootLoader Operators", ["TAC-011", "UNC2565"], "cybercrime", "Unknown", "Financial",
    "Operators of GootLoader malware using SEO poisoning to deliver payloads.", "2014", "2025", "high", "intermediate",
    ["Legal", "Financial Services", "Healthcare"], ["North America", "Europe"],
    [t("T1608.006", "SEO Poisoning", "Resource Development", 3, "Search engine optimization poisoning")],
    ["GootLoader", "Cobalt Strike"], ["GootLoader"]),
  actor("raspberry-robin", "Raspberry Robin Operators", ["Storm-0856"], "cybercrime", "Unknown", "Financial",
    "Operators of Raspberry Robin worm, a major initial access vector spreading via USB drives.", "2021", "2025", "high", "intermediate",
    ["Various"], ["Global"],
    [t("T1091", "Replication Through Removable Media", "Lateral Movement", 3, "USB worm propagation")],
    ["Raspberry Robin"], ["Raspberry Robin"]),
];

// ============================================================
// BATCH 4: More Ransomware Groups
// ============================================================
const BATCH_RANSOMWARE: SeedThreatActor[] = [
  actor("maze-rw", "Maze", ["Twisted Spider", "GOLD VILLAGE"], "ransomware", "Russia", "Financial",
    "Pioneered the double extortion model (encrypt + leak). Disbanded in 2020, members joined Egregor.", "2019", "2020", "high", "advanced",
    ["Healthcare", "Technology", "Government"], ["North America", "Europe"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3), t("T1567", "Exfiltration Over Web Service", "Exfiltration", 3)],
    ["Maze ransomware", "Cobalt Strike"], ["Maze"],
    [{ date: "2020", event: "Maze pioneers double extortion model", source: "Multiple" }], "osint", 88),
  actor("egregor-rw", "Egregor", ["Twisted Spider (partial)"], "ransomware", "Russia", "Financial",
    "Successor to Maze ransomware, disrupted by French/Ukrainian law enforcement in 2021.", "2020", "2021", "high", "advanced",
    ["Retail", "Manufacturing", "Technology"], ["Global"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Egregor ransomware", "QakBot"], ["Egregor"],
    [{ date: "2021", event: "Arrests in Ukraine and France", source: "Europol" }], "osint", 82),
  actor("avaddon-rw", "Avaddon", [], "ransomware", "Russia", "Financial",
    "RaaS operation that shut down and released decryption keys in 2021.", "2020", "2021", "medium", "intermediate",
    ["Healthcare", "Manufacturing", "Government"], ["Global"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Avaddon ransomware"], ["Avaddon"]),
  actor("babuk-rw", "Babuk", ["Babyk"], "ransomware", "Unknown", "Financial",
    "Ransomware group that attacked Washington DC Metropolitan Police. Source code leaked, spawning many variants.", "2021", "2021", "high", "intermediate",
    ["Government", "Healthcare", "Manufacturing"], ["Global"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Babuk ransomware"], ["Babuk"],
    [{ date: "2021", event: "DC Metropolitan Police breach", source: "Multiple" }], "osint", 80),
  actor("cuba-rw", "Cuba", ["COLDDRAW", "Tropical Scorpius"], "ransomware", "Russia", "Financial",
    "Ransomware group targeting critical infrastructure and IT sectors.", "2019", "2024", "high", "advanced",
    ["Financial Services", "Government", "Healthcare", "Technology"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Cuba ransomware", "BUGHATCH", "Veeamp"], ["Cuba", "BUGHATCH"],
    [{ date: "2022", event: "CISA advisory on Cuba ransomware", source: "CISA" }], "osint", 82),
  actor("blackmatter-rw", "BlackMatter", ["DarkSide successor"], "ransomware", "Russia", "Financial",
    "Successor to DarkSide ransomware, operated briefly before shutting down due to law enforcement pressure.", "2021", "2021", "high", "advanced",
    ["Agriculture", "Technology", "Government"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["BlackMatter ransomware"], ["BlackMatter"],
    [{ date: "2021", event: "CISA advisory on BlackMatter", source: "CISA" }], "osint", 82),
  actor("pysa-rw", "PYSA", ["Mespinoza"], "ransomware", "Unknown", "Financial",
    "Ransomware group targeting education and government sectors.", "2019", "2023", "medium", "intermediate",
    ["Education", "Government", "Healthcare"], ["North America", "Europe"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["PYSA ransomware", "ChaChi"], ["PYSA", "ChaChi"]),
  actor("avos-locker-rw", "AvosLocker", [], "ransomware", "Unknown", "Financial",
    "RaaS operation targeting critical infrastructure.", "2021", "2023", "medium", "intermediate",
    ["Financial Services", "Government", "Manufacturing"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["AvosLocker ransomware"], ["AvosLocker"],
    [{ date: "2023", event: "CISA advisory on AvosLocker", source: "CISA" }], "osint", 75),
  actor("karakurt-rw", "Karakurt", ["Karakurt Lair"], "ransomware", "Russia", "Financial",
    "Data extortion group linked to Conti, focusing on data theft without encryption.", "2021", "2024", "high", "advanced",
    ["Healthcare", "Technology", "Government"], ["North America", "Europe"],
    [t("T1567", "Exfiltration Over Web Service", "Exfiltration", 3, "Data theft for extortion")],
    ["Cobalt Strike", "Rclone", "FileZilla"], [],
    [{ date: "2022", event: "CISA advisory on Karakurt", source: "CISA" }], "osint", 80),
  actor("snatch-rw", "Snatch", [], "ransomware", "Russia", "Financial",
    "Ransomware group known for rebooting systems into Safe Mode to evade security tools.", "2018", "2024", "medium", "intermediate",
    ["Defense", "Technology", "Agriculture"], ["North America", "Europe"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3), t("T1562.009", "Safe Mode Boot", "Defense Evasion", 3, "Rebooting into Safe Mode")],
    ["Snatch ransomware"], ["Snatch"],
    [{ date: "2023", event: "CISA advisory on Snatch ransomware", source: "CISA" }], "osint", 75),
  actor("nokoyawa-rw", "Nokoyawa", [], "ransomware", "Russia", "Financial",
    "Ransomware group using zero-day Windows exploits.", "2022", "2024", "high", "advanced",
    ["Manufacturing", "Technology"], ["Global"],
    [t("T1068", "Exploitation for Privilege Escalation", "Privilege Escalation", 3, "Windows zero-day exploitation")],
    ["Nokoyawa ransomware"], ["Nokoyawa"]),
  actor("trigona-rw", "Trigona", [], "ransomware", "Unknown", "Financial",
    "Ransomware group targeting technology and manufacturing sectors.", "2022", "2024", "medium", "intermediate",
    ["Technology", "Manufacturing"], ["Global"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Trigona ransomware"], ["Trigona"]),
  actor("cactus-rw", "Cactus", [], "ransomware", "Unknown", "Financial",
    "Ransomware group exploiting VPN vulnerabilities for initial access, known for encrypting its own binary to evade detection.", "2023", "2025", "high", "advanced",
    ["Manufacturing", "Technology", "Professional Services"], ["Global"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3, "VPN exploitation"), t("T1027", "Obfuscated Files or Information", "Defense Evasion", 3, "Self-encrypting binary")],
    ["Cactus ransomware"], ["Cactus"]),
  actor("blacksuit-rw", "BlackSuit", ["Royal successor"], "ransomware", "Russia", "Financial",
    "Rebrand of Royal ransomware, targeting critical infrastructure.", "2023", "2025", "high", "advanced",
    ["Healthcare", "Government", "Manufacturing"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["BlackSuit ransomware"], ["BlackSuit"],
    [{ date: "2024", event: "CISA advisory on BlackSuit", source: "CISA" }], "osint", 80),
  actor("fog-rw", "Fog", [], "ransomware", "Unknown", "Financial",
    "Emerging ransomware group targeting education and recreation sectors.", "2024", "2025", "medium", "intermediate",
    ["Education", "Recreation", "Financial Services"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Fog ransomware"], ["Fog"]),
  actor("embargo-rw", "Embargo", [], "ransomware", "Unknown", "Financial",
    "Emerging ransomware group using Rust-based malware.", "2024", "2025", "medium", "intermediate",
    ["Healthcare", "Technology"], ["North America"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Embargo ransomware", "MDeployer"], ["Embargo"]),
];

// ============================================================
// BATCH 5: More Hacktivists and Emerging Groups
// ============================================================
const BATCH_HACKTIVIST: SeedThreatActor[] = [
  actor("it-army-ukraine", "IT Army of Ukraine", [], "hacktivist", "Ukraine", "Political / Disruption",
    "Volunteer hacktivist collective conducting DDoS and cyber operations against Russian targets.", "2022", "2025", "medium", "basic",
    ["Government", "Financial Services", "Media"], ["Russia"],
    [t("T1498", "Network Denial of Service", "Impact", 3)], ["DDoS tools"], []),
  actor("ghostsec", "GhostSec", [], "hacktivist", "Various", "Political",
    "Hacktivist group originally targeting ISIS, now conducting broader operations.", "2015", "2024", "medium", "intermediate",
    ["Government", "Technology"], ["Middle East", "Global"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 2)], ["GhostLocker ransomware"], ["GhostLocker"]),
  actor("siegedsec", "SiegedSec", [], "hacktivist", "Various", "Political",
    "Hacktivist group targeting government organizations for political causes.", "2022", "2024", "medium", "intermediate",
    ["Government", "Military"], ["North America"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 2)], ["Custom tools"], []),
  actor("from-lace-to-killnet", "UserSec", [], "hacktivist", "Russia", "Political",
    "Pro-Russian hacktivist group conducting DDoS attacks against NATO countries.", "2023", "2025", "low", "basic",
    ["Government", "Financial Services"], ["Europe"],
    [t("T1498", "Network Denial of Service", "Impact", 2)], ["DDoS tools"], []),
  actor("cyber-toufan", "Cyber Toufan", [], "hacktivist", "Iran", "Political",
    "Pro-Iranian hacktivist group conducting destructive attacks against Israeli organizations.", "2023", "2025", "high", "intermediate",
    ["Technology", "Government", "Financial Services"], ["Middle East"],
    [t("T1485", "Data Destruction", "Impact", 3), t("T1486", "Data Encrypted for Impact", "Impact", 3)],
    ["Custom wiper tools"], []),
  actor("solntsepek", "Solntsepek", ["GRU-linked"], "hacktivist", "Russia", "Disruption",
    "Russian GRU-linked group posing as hacktivists, responsible for Kyivstar telecom attack.", "2022", "2025", "high", "advanced",
    ["Telecommunications", "Government"], ["Eastern Europe"],
    [t("T1485", "Data Destruction", "Impact", 3)], ["Custom wiper tools"], [],
    [{ date: "2023", event: "Kyivstar telecom attack affecting 24M+ subscribers", source: "Multiple" }], "osint", 78),
  actor("people-cyber-army", "People's Cyber Army", [], "hacktivist", "Russia", "Political",
    "Pro-Russian hacktivist group conducting DDoS attacks.", "2022", "2024", "low", "basic",
    ["Government", "Financial Services"], ["Europe"],
    [t("T1498", "Network Denial of Service", "Impact", 2)], ["DDoS tools"], []),
  actor("xaknet", "XakNet", [], "hacktivist", "Russia", "Political",
    "Pro-Russian hacktivist group with suspected GRU connections.", "2022", "2024", "medium", "intermediate",
    ["Government"], ["Eastern Europe"],
    [t("T1498", "Network Denial of Service", "Impact", 2)], ["DDoS tools"], []),
];

// ============================================================
// BATCH 6: Access Brokers and Specialized Groups
// ============================================================
const BATCH_SPECIALIZED: SeedThreatActor[] = [
  actor("exotic-lily", "Exotic Lily", ["GOLD OSBURN"], "cybercrime", "Unknown", "Financial (IAB)",
    "Initial access broker using elaborate social engineering and fake personas to deliver BumbleBee loader.", "2021", "2024", "high", "advanced",
    ["Technology", "Healthcare", "Financial Services"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3, "Elaborate social engineering with fake personas")],
    ["BumbleBee", "IcedID", "Cobalt Strike"], ["BumbleBee"]),
  actor("prophet-spider", "Prophet Spider", ["UNC961"], "cybercrime", "Unknown", "Financial (IAB)",
    "Initial access broker exploiting web-facing applications and selling access to ransomware operators.", "2017", "2024", "high", "advanced",
    ["Various"], ["Global"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3, "Exploiting web apps for access brokering")],
    ["BLUEBIRD", "Cobalt Strike"], ["BLUEBIRD"]),
  actor("zebra2104", "Zebra2104", [], "cybercrime", "Unknown", "Financial (IAB)",
    "Initial access broker providing access to multiple ransomware groups.", "2020", "2023", "medium", "intermediate",
    ["Various"], ["Global"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)], ["Cobalt Strike"], []),
  actor("silence-group", "Silence Group", ["Silence", "WHISPER SPIDER"], "cybercrime", "Russia", "Financial",
    "Russian-speaking cybercrime group targeting financial institutions, particularly banks in CIS countries.", "2016", "2023", "high", "advanced",
    ["Financial Services", "Banking"], ["Russia", "Eastern Europe", "Asia"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1565.001", "Stored Data Manipulation", "Impact", 3, "ATM manipulation")],
    ["Silence framework", "TrueBot"], ["Silence", "TrueBot"]),
  actor("cobalt-group", "Cobalt Group", ["GOLD KINGSWOOD", "Cobalt Gang", "Cobalt Spider"], "cybercrime", "Unknown", "Financial",
    "Cybercrime group targeting financial institutions with ATM jackpotting and SWIFT fraud.", "2016", "2020", "high", "advanced",
    ["Financial Services", "Banking"], ["Global"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3), t("T1565.001", "Stored Data Manipulation", "Impact", 3)],
    ["Cobalt Strike", "CobInt"], ["CobInt"],
    [{ date: "2018", event: "Leader arrested in Spain", source: "Europol" }], "osint", 85),
  actor("xenotime", "XENOTIME", ["TEMP.Veles"], "apt", "Russia", "Sabotage",
    "Russian group behind TRITON/TRISIS malware targeting industrial safety systems (SIS), potentially capable of causing physical destruction.", "2014", "2023", "critical", "nation-state",
    ["Energy", "Oil & Gas", "Manufacturing", "Utilities"], ["Middle East", "North America"],
    [t("T1495", "Firmware Corruption", "Impact", 3, "Safety instrumented system manipulation"), t("T1190", "Exploit Public-Facing Application", "Initial Access", 3)],
    ["TRITON", "TRISIS"], ["TRITON"],
    [{ date: "2017", event: "TRITON attack on Saudi petrochemical plant safety systems", source: "FireEye/Dragos" }], "mitre", 92),
  actor("electrum", "ELECTRUM", ["Sandworm (partial)"], "apt", "Russia", "Sabotage",
    "Russian group targeting energy sector with ICS-focused malware.", "2015", "2024", "critical", "nation-state",
    ["Energy", "Utilities"], ["Eastern Europe"],
    [t("T1495", "Firmware Corruption", "Impact", 3, "ICS/SCADA attacks")],
    ["Industroyer", "CrashOverride"], ["Industroyer"]),
  actor("kamacite", "KAMACITE", ["Sandworm access team"], "apt", "Russia", "Espionage / Sabotage",
    "Russian group providing initial access for Sandworm's ICS operations.", "2014", "2024", "high", "nation-state",
    ["Energy", "Government"], ["Eastern Europe"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["BlackEnergy", "GreyEnergy"], ["BlackEnergy"]),
  actor("raspite", "RASPITE", ["Leafminer"], "apt", "Iran", "Espionage",
    "Iranian group targeting energy and government in the Middle East.", "2017", "2022", "medium", "intermediate",
    ["Energy", "Government"], ["Middle East"],
    [t("T1190", "Exploit Public-Facing Application", "Initial Access", 2)], ["Impacket", "Mimikatz"], []),
  actor("chrysene", "CHRYSENE", ["OilRig (partial)"], "apt", "Iran", "Espionage",
    "Iranian group targeting petrochemical and oil & gas sectors.", "2017", "2023", "high", "advanced",
    ["Oil & Gas", "Petrochemical"], ["Middle East"],
    [t("T1566.001", "Spearphishing Attachment", "Initial Access", 3)], ["Custom backdoors"], []),
  actor("erythrite", "ERYTHRITE", [], "cybercrime", "Unknown", "Financial",
    "Group conducting SEO poisoning and credential theft campaigns.", "2020", "2024", "medium", "intermediate",
    ["Various"], ["North America"],
    [t("T1608.006", "SEO Poisoning", "Resource Development", 3)], ["Custom tools"], []),
  actor("storm-0558", "Storm-0558", [], "apt", "China", "Espionage",
    "Chinese group that compromised Microsoft cloud signing key, accessing email accounts of senior US government officials.", "2021", "2023", "critical", "nation-state",
    ["Government", "Diplomatic"], ["North America"],
    [t("T1199", "Trusted Relationship", "Initial Access", 3, "Cloud signing key compromise")],
    ["Custom tools"], [],
    [{ date: "2023", event: "Compromise of US government officials' email via Microsoft cloud key", source: "Microsoft/CISA" }], "osint", 92),
  actor("storm-0501", "Storm-0501", [], "cybercrime", "Unknown", "Financial",
    "Ransomware affiliate targeting hybrid cloud environments.", "2021", "2025", "high", "advanced",
    ["Government", "Healthcare", "Manufacturing"], ["North America"],
    [t("T1078.004", "Cloud Accounts", "Persistence", 3, "Cloud environment compromise")],
    ["Cobalt Strike", "Embargo ransomware"], ["Embargo"]),
  actor("storm-1811", "Storm-1811", [], "cybercrime", "Unknown", "Financial",
    "Group abusing Microsoft Quick Assist for social engineering attacks.", "2024", "2025", "medium", "intermediate",
    ["Various"], ["North America"],
    [t("T1219", "Remote Access Software", "Command and Control", 3, "Quick Assist abuse")],
    ["Black Basta ransomware"], ["Black Basta"]),
  actor("storm-1567", "Storm-1567", ["Akira operators"], "cybercrime", "Unknown", "Financial",
    "Ransomware operators behind Akira ransomware.", "2023", "2025", "high", "advanced",
    ["Manufacturing", "Technology"], ["Global"],
    [t("T1486", "Data Encrypted for Impact", "Impact", 3)], ["Akira ransomware"], ["Akira"]),
];

export { BATCH_CHINESE, BATCH_MENA, BATCH_CYBERCRIME, BATCH_RANSOMWARE, BATCH_HACKTIVIST, BATCH_SPECIALIZED };
