// Part 3: Additional APT groups, regional actors, and emerging threats
import type { SeedThreatActor } from "./threatActorSeed";

// ============================================================
// CHINESE APT GROUPS (Extended)
// ============================================================

const CHINESE_APTS: SeedThreatActor[] = [
  {
    actorId: "apt1", name: "APT1", aliases: ["Comment Crew", "Comment Panda", "PLA Unit 61398"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "PLA Unit 61398, one of the first publicly attributed Chinese APT groups. Targeted 141+ organizations across 20 industries.",
    firstSeen: "2006", lastActive: "2015", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Technology", "Aerospace", "Energy", "Manufacturing", "Defense"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with malicious attachments." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "Command execution." },
    ],
    tools: ["WEBC2", "BISCUIT", "GLOOXMAIL"], malware: ["WEBC2", "BISCUIT"],
    activityTimeline: [{ date: "2013", event: "Mandiant APT1 report publicly attributes PLA Unit 61398", source: "Mandiant" }],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt3", name: "APT3", aliases: ["Gothic Panda", "Buckeye", "UPS Team", "TG-0110"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese MSS-linked group targeting aerospace, defense, and technology sectors. Known for zero-day exploitation.",
    firstSeen: "2007", lastActive: "2017", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Defense", "Technology", "Telecommunications"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 3, description: "Advanced evasion." },
    ],
    tools: ["Pirpi", "DoublePulsar", "Bemstour"], malware: ["Pirpi", "Bemstour"],
    activityTimeline: [{ date: "2017", event: "Linked to Chinese MSS contractor Boyusec", source: "Recorded Future" }],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt10", name: "APT10", aliases: ["Stone Panda", "MenuPass", "Red Apollo", "CVNX", "Potassium"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese MSS-linked group known for Operation Cloud Hopper, targeting managed service providers to access their clients' networks.",
    firstSeen: "2006", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["MSP", "Technology", "Healthcare", "Defense", "Government"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1199", name: "Trusted Relationship", tactic: "Initial Access", score: 3, description: "MSP supply chain compromise." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft." },
    ],
    tools: ["PlugX", "QuasarRAT", "Poison Ivy", "ChChes"], malware: ["PlugX", "QuasarRAT", "ChChes", "UPPERCUT"],
    activityTimeline: [
      { date: "2018", event: "Operation Cloud Hopper targeting MSPs globally", source: "PwC/BAE" },
      { date: "2018", event: "Two members indicted by US DOJ", source: "US DOJ" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt17", name: "APT17", aliases: ["Deputy Dog", "Elderwood", "Sneaky Panda"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting US government, defense, law firms, and technology companies.",
    firstSeen: "2010", lastActive: "2018", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Defense", "Legal", "Technology"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation." },
    ],
    tools: ["BLACKCOFFEE", "Deputy Dog"], malware: ["BLACKCOFFEE"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 80,
  },
  {
    actorId: "apt19", name: "APT19", aliases: ["Deep Panda", "Codoso", "Shell Crew", "C0d0so0"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting legal, investment, and technology sectors. Known for exploiting Forbes.com as a watering hole.",
    firstSeen: "2010", lastActive: "2020", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Legal", "Financial Services", "Technology", "Government"],
    targetRegions: ["North America"],
    techniques: [
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Strategic web compromises." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 2, description: "PowerShell execution." },
    ],
    tools: ["Derusbi", "Sakula", "Cobalt Strike"], malware: ["Derusbi", "Sakula"],
    activityTimeline: [{ date: "2014", event: "Forbes.com watering hole attack", source: "iSIGHT" }],
    dataSource: "mitre", confidence: 82,
  },
  {
    actorId: "apt27", name: "APT27", aliases: ["Emissary Panda", "LuckyMouse", "Iron Tiger", "Bronze Union"],
    type: "apt", origin: "China", motivation: "Espionage / Financial",
    description: "Chinese group targeting government, technology, and defense sectors. Has shifted to include financially motivated attacks.",
    firstSeen: "2010", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Technology", "Defense", "Aerospace"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Web application exploitation." },
      { id: "T1059.001", name: "PowerShell", tactic: "Execution", score: 3, description: "PowerShell backdoors." },
    ],
    tools: ["HyperBro", "PlugX", "SysUpdate", "Cobalt Strike"], malware: ["HyperBro", "PlugX", "SysUpdate"],
    activityTimeline: [{ date: "2021", event: "ProxyLogon exploitation campaign", source: "ESET" }],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "apt30", name: "APT30", aliases: ["Override Panda", "Naikon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting ASEAN countries and journalists covering Southeast Asian geopolitics.",
    firstSeen: "2005", lastActive: "2021", threatLevel: "medium", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Media", "Diplomatic"],
    targetRegions: ["Southeast Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing with geopolitical lures." },
    ],
    tools: ["BACKSPACE", "NETEAGLE", "SHIPSHAPE"], malware: ["BACKSPACE", "NETEAGLE"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 78,
  },
  {
    actorId: "apt31", name: "APT31", aliases: ["Zirconium", "Judgment Panda", "Violet Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese MSS-linked group targeting government officials, political campaigns, and technology companies.",
    firstSeen: "2010", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Technology", "Political", "Defense"],
    targetRegions: ["North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential phishing." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Router exploitation." },
    ],
    tools: ["RAWDOOR", "Trochilus", "China Chopper"], malware: ["RAWDOOR", "Trochilus"],
    activityTimeline: [{ date: "2024", event: "Seven members indicted by US DOJ", source: "US DOJ" }],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "apt40", name: "APT40", aliases: ["Leviathan", "TEMP.Periscope", "TEMP.Jumper", "Gingham Typhoon", "BRONZE MOHAWK"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese MSS-linked group (Hainan Province) targeting maritime, defense, and government sectors. Rapid zero-day exploitation capability.",
    firstSeen: "2009", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Maritime", "Defense", "Government", "Technology", "Aviation"],
    targetRegions: ["Asia-Pacific", "North America"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Rapid exploitation of new vulnerabilities." },
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Maritime-themed phishing." },
    ],
    tools: ["AIRBREAK", "MURKYTOP", "China Chopper", "Derusbi"], malware: ["AIRBREAK", "MURKYTOP", "PHOTO"],
    activityTimeline: [{ date: "2024", event: "Five Eyes joint advisory on APT40", source: "ASD/CISA" }],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "hafnium", name: "HAFNIUM", aliases: ["Silk Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group responsible for mass exploitation of Microsoft Exchange Server vulnerabilities (ProxyLogon) affecting 250,000+ servers worldwide.",
    firstSeen: "2017", lastActive: "2024", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Defense", "Healthcare", "Education", "Technology"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "ProxyLogon/ProxyShell exploitation." },
      { id: "T1505.003", name: "Web Shell", tactic: "Persistence", score: 3, description: "China Chopper and custom web shells." },
    ],
    tools: ["China Chopper", "ASPXSpy", "Covenant", "Nishang"], malware: ["China Chopper"],
    activityTimeline: [{ date: "2021", event: "ProxyLogon mass exploitation affecting 250,000+ Exchange servers", source: "Microsoft/CISA" }],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "mustang-panda", name: "Mustang Panda", aliases: ["Bronze President", "Stately Taurus", "RedDelta", "TEMP.Hex"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting government, NGO, and religious organizations, particularly those connected to Tibetan, Uyghur, and Mongolian interests.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "NGO", "Religious", "Diplomatic", "Telecommunications"],
    targetRegions: ["Southeast Asia", "Europe", "Africa"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Geopolitical-themed phishing." },
      { id: "T1574.002", name: "DLL Side-Loading", tactic: "Defense Evasion", score: 3, description: "PlugX DLL side-loading." },
    ],
    tools: ["PlugX", "Korplug", "TONEINS", "TONESHELL"], malware: ["PlugX", "Korplug", "TONESHELL"],
    activityTimeline: [{ date: "2023", event: "Targeting European government organizations", source: "ESET" }],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "winnti", name: "Winnti Group", aliases: ["APT41 (partial)", "Barium", "Wicked Panda", "Brass Typhoon"],
    type: "apt", origin: "China", motivation: "Espionage / Financial",
    description: "Chinese group conducting both state-sponsored espionage and financially motivated attacks, particularly supply chain compromises.",
    firstSeen: "2010", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Gaming", "Technology", "Healthcare", "Telecommunications", "Government"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Supply chain attacks (CCleaner, ASUS)." },
      { id: "T1055", name: "Process Injection", tactic: "Defense Evasion", score: 3, description: "Sophisticated injection." },
    ],
    tools: ["Winnti", "ShadowPad", "PlugX", "Cobalt Strike"], malware: ["Winnti", "ShadowPad", "PlugX"],
    activityTimeline: [
      { date: "2017", event: "CCleaner supply chain attack (2.27M infections)", source: "Avast" },
      { date: "2019", event: "ASUS Live Update supply chain attack", source: "Kaspersky" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "gallium", name: "GALLIUM", aliases: ["Granite Typhoon", "Alloy Taurus"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting telecommunications providers and government organizations in Southeast Asia and Africa.",
    firstSeen: "2018", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Telecommunications", "Government", "Financial Services"],
    targetRegions: ["Southeast Asia", "Africa", "Middle East"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Web server exploitation." },
      { id: "T1505.003", name: "Web Shell", tactic: "Persistence", score: 3, description: "Web shell deployment." },
    ],
    tools: ["China Chopper", "Gh0st RAT", "Poison Ivy", "PingPull"], malware: ["PingPull", "Gh0st RAT"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 80,
  },
];

// ============================================================
// IRANIAN APT GROUPS (Extended)
// ============================================================

const IRANIAN_APTS: SeedThreatActor[] = [
  {
    actorId: "apt33", name: "APT33", aliases: ["Elfin", "Magnallium", "Refined Kitten", "Peach Sandstorm", "Holmium"],
    type: "apt", origin: "Iran", motivation: "Espionage / Disruption",
    description: "Iranian IRGC-linked group targeting aerospace, energy, and petrochemical sectors. Linked to Shamoon wiper attacks.",
    firstSeen: "2013", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Aerospace", "Energy", "Petrochemical", "Defense"],
    targetRegions: ["Middle East", "North America", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Job-themed phishing." },
      { id: "T1110", name: "Brute Force", tactic: "Credential Access", score: 3, description: "Password spraying campaigns." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "Shamoon wiper deployment." },
    ],
    tools: ["Shamoon", "TURNEDUP", "POWERTON", "Ruler"], malware: ["Shamoon", "TURNEDUP", "POWERTON"],
    activityTimeline: [
      { date: "2017", event: "Shamoon 2 attacks on Saudi organizations", source: "Symantec" },
      { date: "2023", event: "Password spraying targeting defense sector", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 90,
  },
  {
    actorId: "apt34", name: "APT34", aliases: ["OilRig", "Helix Kitten", "Hazel Sandstorm", "EUROPIUM", "Crambus"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian MOIS-linked group targeting government, financial, energy, and telecommunications sectors across the Middle East.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Financial Services", "Energy", "Telecommunications"],
    targetRegions: ["Middle East"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing campaigns." },
      { id: "T1071.004", name: "DNS", tactic: "Command and Control", score: 3, description: "DNS tunneling for C2." },
      { id: "T1505.003", name: "Web Shell", tactic: "Persistence", score: 3, description: "Custom web shells." },
    ],
    tools: ["BONDUPDATER", "QUADAGENT", "OopsIE", "Karkoff"], malware: ["BONDUPDATER", "OopsIE", "Karkoff", "SideTwist"],
    activityTimeline: [
      { date: "2019", event: "Tools and member identities leaked on Telegram", source: "Lab Dookhtegan" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "apt35", name: "APT35", aliases: ["Charming Kitten", "Phosphorus", "Mint Sandstorm", "TA453", "Yellow Garuda"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian IRGC-linked group targeting academics, journalists, diplomats, and dissidents. Known for sophisticated social engineering.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Academic", "Media", "Diplomatic", "Government", "Think Tanks"],
    targetRegions: ["North America", "Europe", "Middle East"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Impersonation-based credential phishing." },
      { id: "T1598.003", name: "Spearphishing Link (Recon)", tactic: "Reconnaissance", score: 3, description: "Long-term social engineering." },
    ],
    tools: ["HYPERSCRAPE", "PowerLess", "BellaCiao", "POWERSTAR"], malware: ["HYPERSCRAPE", "PowerLess", "BellaCiao", "POWERSTAR"],
    activityTimeline: [
      { date: "2023", event: "Targeting nuclear security experts", source: "Proofpoint" },
    ],
    dataSource: "mitre", confidence: 92,
  },
  {
    actorId: "apt39", name: "APT39", aliases: ["Chafer", "Remix Kitten", "Cotton Sandstorm"],
    type: "apt", origin: "Iran", motivation: "Espionage",
    description: "Iranian MOIS-linked group targeting telecommunications and travel industries to track individuals of interest.",
    firstSeen: "2014", lastActive: "2023", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Telecommunications", "Travel", "Government", "Technology"],
    targetRegions: ["Middle East", "North America"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Phishing campaigns." },
      { id: "T1078", name: "Valid Accounts", tactic: "Persistence", score: 3, description: "Stolen credentials." },
    ],
    tools: ["Remexi", "Seaweed", "MECHAFLOUNDER"], malware: ["Remexi", "MECHAFLOUNDER"],
    activityTimeline: [{ date: "2021", event: "US sanctions against Rana Intelligence Computing", source: "US Treasury" }],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "apt42", name: "APT42", aliases: ["Calanque", "UNC788", "Mint Sandstorm (partial)"],
    type: "apt", origin: "Iran", motivation: "Espionage / Surveillance",
    description: "Iranian IRGC-IO group conducting surveillance operations against dissidents, activists, and opposition figures.",
    firstSeen: "2015", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Civil Society", "Media", "Government", "Legal"],
    targetRegions: ["Middle East", "North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential phishing of activists." },
      { id: "T1437", name: "Application Layer Protocol", tactic: "Command and Control", score: 2, description: "Mobile surveillance." },
    ],
    tools: ["VINETHORN", "TAMECAT", "NICECURL"], malware: ["VINETHORN", "TAMECAT"],
    activityTimeline: [{ date: "2024", event: "Targeting US presidential campaign", source: "Google TAG" }],
    dataSource: "mitre", confidence: 88,
  },
];

// ============================================================
// NORTH KOREAN APT GROUPS (Extended)
// ============================================================

const NK_APTS: SeedThreatActor[] = [
  {
    actorId: "lazarus", name: "Lazarus Group", aliases: ["HIDDEN COBRA", "Zinc", "Diamond Sleet", "Labyrinth Chollima", "APT38 (partial)"],
    type: "apt", origin: "North Korea", motivation: "Financial / Espionage / Disruption",
    description: "North Korea's premier cyber threat group, responsible for the Sony Pictures hack, WannaCry ransomware, Bangladesh Bank heist ($81M), and billions in cryptocurrency theft.",
    firstSeen: "2007", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Financial Services", "Cryptocurrency", "Defense", "Technology", "Entertainment"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Sophisticated phishing campaigns." },
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Supply chain attacks (3CX, JumpCloud)." },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact", score: 3, description: "WannaCry ransomware." },
      { id: "T1496", name: "Resource Hijacking", tactic: "Impact", score: 2, description: "Cryptocurrency mining." },
    ],
    tools: ["Manuscrypt", "FALLCHILL", "HOPLIGHT", "AppleJeus", "BLINDINGCAN"],
    malware: ["WannaCry", "Manuscrypt", "FALLCHILL", "AppleJeus", "BLINDINGCAN"],
    activityTimeline: [
      { date: "2014", event: "Sony Pictures Entertainment hack", source: "FBI" },
      { date: "2016", event: "Bangladesh Bank SWIFT heist ($81M)", source: "Multiple" },
      { date: "2017", event: "WannaCry global ransomware attack", source: "Multiple" },
      { date: "2023", event: "3CX supply chain attack", source: "Mandiant" },
      { date: "2024", event: "$1.5B+ in cryptocurrency theft", source: "Chainalysis" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "apt38", name: "APT38", aliases: ["BlueNoroff", "Sapphire Sleet", "Stardust Chollima", "CryptoCore"],
    type: "apt", origin: "North Korea", motivation: "Financial",
    description: "North Korean group specializing in financial theft from banks and cryptocurrency exchanges. Subgroup of Lazarus focused on revenue generation.",
    firstSeen: "2014", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Financial Services", "Cryptocurrency", "DeFi", "Venture Capital"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Fake job offers and VC meeting requests." },
      { id: "T1059.007", name: "JavaScript", tactic: "Execution", score: 3, description: "Malicious npm packages." },
      { id: "T1565.001", name: "Stored Data Manipulation", tactic: "Impact", score: 3, description: "SWIFT transaction manipulation." },
    ],
    tools: ["AppleJeus", "TraderTraitor", "DYEPACK"], malware: ["AppleJeus", "TraderTraitor", "DYEPACK"],
    activityTimeline: [
      { date: "2022", event: "Ronin Network hack ($620M)", source: "FBI" },
      { date: "2025", event: "Bybit exchange hack ($1.5B)", source: "Multiple" },
    ],
    dataSource: "mitre", confidence: 95,
  },
  {
    actorId: "apt43", name: "APT43", aliases: ["Kimsuky (partial)", "Emerald Sleet", "Velvet Chollima", "Thallium"],
    type: "apt", origin: "North Korea", motivation: "Espionage / Financial",
    description: "North Korean group supporting intelligence collection on nuclear policy and sanctions. Uses cryptocurrency theft to fund operations.",
    firstSeen: "2012", lastActive: "2025", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Think Tanks", "Academic", "Cryptocurrency"],
    targetRegions: ["East Asia", "North America", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential harvesting." },
      { id: "T1496", name: "Resource Hijacking", tactic: "Impact", score: 2, description: "Cryptocurrency mining and theft." },
    ],
    tools: ["BabyShark", "AppleSeed", "LATEOP"], malware: ["BabyShark", "AppleSeed", "LATEOP"],
    activityTimeline: [{ date: "2023", event: "Mandiant publishes APT43 report", source: "Mandiant" }],
    dataSource: "mitre", confidence: 85,
  },
  {
    actorId: "temp-hermit", name: "TEMP.Hermit", aliases: ["Citrine Sleet", "UNC4736", "AppleJeus operator"],
    type: "apt", origin: "North Korea", motivation: "Financial",
    description: "North Korean group targeting cryptocurrency and blockchain companies through trojanized trading applications.",
    firstSeen: "2018", lastActive: "2025", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Cryptocurrency", "Blockchain", "DeFi", "Financial Services"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "Trojanized crypto applications." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 2, description: "Browser zero-day exploitation." },
    ],
    tools: ["AppleJeus variants", "JumpCloud tools"], malware: ["AppleJeus"],
    activityTimeline: [{ date: "2024", event: "Chrome zero-day targeting crypto users", source: "Microsoft" }],
    dataSource: "osint", confidence: 78,
  },
];

// ============================================================
// RUSSIAN APT GROUPS (Extended)
// ============================================================

const RUSSIAN_APTS: SeedThreatActor[] = [
  {
    actorId: "apt28", name: "APT28", aliases: ["Fancy Bear", "Sofacy", "Sednit", "Forest Blizzard", "STRONTIUM", "Pawn Storm"],
    type: "apt", origin: "Russia", motivation: "Espionage / Disruption",
    description: "Russian GRU Unit 26165, one of the most active and well-known threat groups. Responsible for DNC hack, WADA breach, and targeting of NATO/government organizations.",
    firstSeen: "2004", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Defense", "Media", "Political"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing campaigns." },
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Zero-day exploitation." },
      { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access", score: 3, description: "Credential theft." },
      { id: "T1027", name: "Obfuscated Files or Information", tactic: "Defense Evasion", score: 3, description: "Advanced obfuscation." },
    ],
    tools: ["X-Agent", "X-Tunnel", "Zebrocy", "GoDownloader", "Cannon"],
    malware: ["X-Agent", "X-Tunnel", "Zebrocy", "Cannon", "Drovorub"],
    activityTimeline: [
      { date: "2016", event: "DNC hack and election interference", source: "FBI/NSA/CISA" },
      { date: "2018", event: "WADA and Olympic anti-doping agency breach", source: "Multiple" },
      { date: "2023", event: "Outlook zero-day exploitation (CVE-2023-23397)", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "apt29", name: "APT29", aliases: ["Cozy Bear", "The Dukes", "Midnight Blizzard", "NOBELIUM", "Cloaked Ursa"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian SVR group responsible for SolarWinds supply chain attack, one of the most sophisticated espionage operations ever discovered. Targets government, diplomatic, and technology sectors.",
    firstSeen: "2008", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Government", "Diplomatic", "Technology", "Think Tanks", "Healthcare"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Initial Access", score: 3, description: "SolarWinds Orion supply chain attack." },
      { id: "T1078.004", name: "Cloud Accounts", tactic: "Persistence", score: 3, description: "Cloud infrastructure compromise." },
      { id: "T1550.001", name: "Application Access Token", tactic: "Lateral Movement", score: 3, description: "OAuth token abuse." },
    ],
    tools: ["SUNBURST", "TEARDROP", "EnvyScout", "FoggyWeb", "MagicWeb"],
    malware: ["SUNBURST", "TEARDROP", "EnvyScout", "FoggyWeb", "MagicWeb"],
    activityTimeline: [
      { date: "2020", event: "SolarWinds supply chain attack (18,000+ organizations)", source: "FireEye/Microsoft" },
      { date: "2024", event: "Microsoft corporate email breach", source: "Microsoft" },
    ],
    dataSource: "mitre", confidence: 98,
  },
  {
    actorId: "ember-bear", name: "Ember Bear", aliases: ["UAC-0056", "Lorec53", "UNC2589", "Cadet Blizzard"],
    type: "apt", origin: "Russia", motivation: "Disruption",
    description: "Russian GRU-linked group conducting destructive operations against Ukraine, including WhisperGate wiper deployment.",
    firstSeen: "2021", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Technology", "Education"],
    targetRegions: ["Eastern Europe"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Web application exploitation." },
      { id: "T1485", name: "Data Destruction", tactic: "Impact", score: 3, description: "WhisperGate wiper." },
    ],
    tools: ["WhisperGate", "CaddyWiper", "Cobalt Strike"], malware: ["WhisperGate"],
    activityTimeline: [{ date: "2022", event: "WhisperGate attacks against Ukraine before invasion", source: "Microsoft" }],
    dataSource: "mitre", confidence: 82,
  },
  {
    actorId: "gossamer-bear", name: "Gossamer Bear", aliases: ["UTA0137", "ColdRiver (partial)"],
    type: "apt", origin: "Russia", motivation: "Espionage",
    description: "Russian group targeting Western government officials and defense sector with credential phishing.",
    firstSeen: "2019", lastActive: "2024", threatLevel: "medium", sophistication: "advanced",
    targetSectors: ["Government", "Defense", "Think Tanks"],
    targetRegions: ["Europe", "North America"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Credential phishing." },
    ],
    tools: ["Custom phishing frameworks"], malware: [],
    activityTimeline: [],
    dataSource: "osint", confidence: 70,
  },
];

// ============================================================
// ADDITIONAL REGIONAL ACTORS
// ============================================================

const REGIONAL_ACTORS: SeedThreatActor[] = [
  {
    actorId: "ocean-lotus", name: "OceanLotus", aliases: ["APT32", "SeaLotus", "Canvas Cyclone", "BISMUTH"],
    type: "apt", origin: "Vietnam", motivation: "Espionage",
    description: "Vietnamese government-linked group targeting foreign governments, dissidents, journalists, and private sector organizations in Southeast Asia.",
    firstSeen: "2012", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Media", "Manufacturing", "Technology", "Automotive"],
    targetRegions: ["Southeast Asia", "Europe"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Watering hole attacks." },
      { id: "T1574.002", name: "DLL Side-Loading", tactic: "Defense Evasion", score: 3, description: "DLL side-loading." },
    ],
    tools: ["Denis", "Kerrdown", "Cobalt Strike"], malware: ["Denis", "Kerrdown", "METALJACK"],
    activityTimeline: [{ date: "2020", event: "Targeting COVID-19 response organizations", source: "Volexity" }],
    dataSource: "mitre", confidence: 88,
  },
  {
    actorId: "nso-group", name: "NSO Group", aliases: ["Pegasus operator"],
    type: "apt", origin: "Israel", motivation: "Surveillance (commercial)",
    description: "Israeli commercial surveillance company developing Pegasus spyware, used by governments worldwide to target journalists, activists, and political figures.",
    firstSeen: "2016", lastActive: "2025", threatLevel: "critical", sophistication: "nation-state",
    targetSectors: ["Civil Society", "Media", "Government", "Legal"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 3, description: "Zero-click mobile exploits." },
      { id: "T1437", name: "Application Layer Protocol", tactic: "Command and Control", score: 3, description: "Mobile C2." },
    ],
    tools: ["Pegasus"], malware: ["Pegasus"],
    activityTimeline: [
      { date: "2021", event: "Pegasus Project reveals 50,000+ potential targets", source: "Amnesty/Forbidden Stories" },
      { date: "2021", event: "US Commerce Department blacklists NSO Group", source: "US Commerce" },
    ],
    dataSource: "osint", confidence: 95,
  },
  {
    actorId: "candiru", name: "Candiru", aliases: ["Saito Tech", "SOURGUM"],
    type: "apt", origin: "Israel", motivation: "Surveillance (commercial)",
    description: "Israeli commercial surveillance company selling spyware to governments for targeting journalists, activists, and political dissidents.",
    firstSeen: "2018", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Civil Society", "Media", "Government"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 3, description: "Browser zero-day exploitation." },
      { id: "T1203", name: "Exploitation for Client Execution", tactic: "Execution", score: 3, description: "Windows zero-day exploitation." },
    ],
    tools: ["DevilsTongue"], malware: ["DevilsTongue"],
    activityTimeline: [{ date: "2021", event: "Microsoft and Citizen Lab expose Candiru operations", source: "Microsoft/Citizen Lab" }],
    dataSource: "osint", confidence: 82,
  },
  {
    actorId: "dark-caracal", name: "Dark Caracal", aliases: ["Lebanese GDGS"],
    type: "apt", origin: "Lebanon", motivation: "Espionage",
    description: "Lebanese General Directorate of General Security-linked group conducting mobile surveillance operations.",
    firstSeen: "2012", lastActive: "2021", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Government", "Military", "Media"],
    targetRegions: ["Middle East", "Europe"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 2, description: "Phishing for mobile malware." },
    ],
    tools: ["Pallas", "CrossRAT", "Bandook"], malware: ["Pallas", "CrossRAT"],
    activityTimeline: [{ date: "2018", event: "EFF/Lookout expose Dark Caracal operations", source: "EFF/Lookout" }],
    dataSource: "osint", confidence: 72,
  },
  {
    actorId: "molerats", name: "Molerats", aliases: ["Gaza Cybergang", "Extreme Jackal", "TA402"],
    type: "apt", origin: "Palestine", motivation: "Espionage",
    description: "Palestinian group targeting Middle Eastern government, energy, and media organizations with politically motivated espionage.",
    firstSeen: "2012", lastActive: "2024", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Government", "Energy", "Media", "Diplomatic"],
    targetRegions: ["Middle East"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Political-themed phishing." },
      { id: "T1059.005", name: "Visual Basic", tactic: "Execution", score: 2, description: "VBA macro execution." },
    ],
    tools: ["Spark", "Pierogi", "NimbleMamba"], malware: ["Spark", "Pierogi", "NimbleMamba"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 75,
  },
  {
    actorId: "bahamut", name: "Bahamut", aliases: [],
    type: "apt", origin: "Unknown (mercenary)", motivation: "Espionage (for hire)",
    description: "Cyber mercenary group conducting targeted surveillance operations for multiple clients, using fake apps and sophisticated social engineering.",
    firstSeen: "2016", lastActive: "2024", threatLevel: "high", sophistication: "advanced",
    targetSectors: ["Government", "Civil Society", "Diplomatic", "Technology"],
    targetRegions: ["Middle East", "South Asia"],
    techniques: [
      { id: "T1566.002", name: "Spearphishing Link", tactic: "Initial Access", score: 3, description: "Phishing with fake apps." },
      { id: "T1437", name: "Application Layer Protocol", tactic: "Command and Control", score: 2, description: "Mobile surveillance." },
    ],
    tools: ["Custom Android spyware", "Fake VPN apps"], malware: ["Bahamut spyware"],
    activityTimeline: [{ date: "2022", event: "Fake VPN apps targeting South Asian users", source: "ESET" }],
    dataSource: "osint", confidence: 72,
  },
  {
    actorId: "confucius", name: "Confucius", aliases: ["APT-C-24"],
    type: "apt", origin: "India", motivation: "Espionage",
    description: "Indian group targeting Pakistani military and government organizations.",
    firstSeen: "2013", lastActive: "2023", threatLevel: "medium", sophistication: "intermediate",
    targetSectors: ["Military", "Government"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 2, description: "Phishing campaigns." },
    ],
    tools: ["SunBird", "Hornbill"], malware: ["SunBird", "Hornbill"],
    activityTimeline: [],
    dataSource: "osint", confidence: 68,
  },
  {
    actorId: "transparent-tribe", name: "Transparent Tribe", aliases: ["APT36", "Mythic Leopard", "ProjectM", "C-Major"],
    type: "apt", origin: "Pakistan", motivation: "Espionage",
    description: "Pakistani ISI-linked group targeting Indian military, government, and education sectors.",
    firstSeen: "2013", lastActive: "2025", threatLevel: "high", sophistication: "intermediate",
    targetSectors: ["Military", "Government", "Education", "Defense"],
    targetRegions: ["South Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Military-themed phishing." },
      { id: "T1204.002", name: "Malicious File", tactic: "Execution", score: 3, description: "Trojanized documents." },
    ],
    tools: ["CrimsonRAT", "ObliqueRAT", "Poseidon"], malware: ["CrimsonRAT", "ObliqueRAT", "Poseidon"],
    activityTimeline: [{ date: "2023", event: "Targeting Indian education sector", source: "SentinelOne" }],
    dataSource: "mitre", confidence: 82,
  },
  {
    actorId: "spring-dragon", name: "Spring Dragon", aliases: ["Lotus Blossom", "DRAGONFISH", "Elise"],
    type: "apt", origin: "China", motivation: "Espionage",
    description: "Chinese group targeting government and military organizations in Southeast Asia.",
    firstSeen: "2012", lastActive: "2022", threatLevel: "medium", sophistication: "nation-state",
    targetSectors: ["Government", "Military", "Telecommunications"],
    targetRegions: ["Southeast Asia"],
    techniques: [
      { id: "T1566.001", name: "Spearphishing Attachment", tactic: "Initial Access", score: 3, description: "Targeted phishing." },
    ],
    tools: ["Elise", "Emissary"], malware: ["Elise", "Emissary"],
    activityTimeline: [],
    dataSource: "mitre", confidence: 72,
  },
  {
    actorId: "earth-lusca", name: "Earth Lusca", aliases: ["TAG-22", "Charcoal Typhoon", "CHROMIUM"],
    type: "apt", origin: "China", motivation: "Espionage / Financial",
    description: "Chinese group targeting government, education, and technology sectors while also conducting financially motivated cryptocurrency theft.",
    firstSeen: "2019", lastActive: "2024", threatLevel: "high", sophistication: "nation-state",
    targetSectors: ["Government", "Education", "Technology", "Cryptocurrency"],
    targetRegions: ["Global"],
    techniques: [
      { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access", score: 3, description: "Web application exploitation." },
      { id: "T1189", name: "Drive-by Compromise", tactic: "Initial Access", score: 2, description: "Watering hole attacks." },
    ],
    tools: ["ShadowPad", "Cobalt Strike", "Winnti"], malware: ["ShadowPad", "Winnti"],
    activityTimeline: [],
    dataSource: "osint", confidence: 78,
  },
];

export { CHINESE_APTS, IRANIAN_APTS, NK_APTS, RUSSIAN_APTS, REGIONAL_ACTORS };
