/**
 * FedRAMP Compliance Framework Library
 *
 * NIST 800-53 Rev 5 control families mapped to FedRAMP Moderate baseline.
 * Includes POA&M management, continuous monitoring, 3PAO integration,
 * and ATO package generation support.
 *
 * FedRAMP Moderate baseline: 325 controls across 20 control families.
 */

export interface FedRAMPControl {
  id: string;
  family: string;
  familyCode: string;
  title: string;
  description: string;
  baseline: "low" | "moderate" | "high";
  status: "implemented" | "partially_implemented" | "planned" | "not_implemented" | "not_applicable" | "inherited";
  implementationStatus: string;
  responsibleRole: string;
  priority: "P1" | "P2" | "P3";
  crossMappings: { framework: string; controlId: string }[];
  automationLevel: "full" | "partial" | "manual";
  testProcedure: string;
  expectedEvidence: string[];
  poamRequired: boolean;
}

export interface POAMEntry {
  id: string;
  controlId: string;
  weakness: string;
  severity: "critical" | "high" | "moderate" | "low";
  scheduledCompletionDate: number;
  milestones: { description: string; dueDate: number; status: "complete" | "in_progress" | "not_started" }[];
  responsiblePOC: string;
  resources: string;
  vendorDependency: boolean;
  deviationRationale?: string;
  status: "open" | "in_progress" | "completed" | "delayed" | "accepted_risk";
  riskRating: number; // 1-25 (likelihood x impact)
}

export interface ATOPackageStatus {
  systemName: string;
  systemId: string;
  impactLevel: "low" | "moderate" | "high";
  authorizationType: "initial" | "reauthorization" | "significant_change";
  status: "pre_assessment" | "assessment" | "authorization" | "continuous_monitoring";
  documents: ATODocument[];
  assessor3PAO: string | null;
  authorizedDate: number | null;
  expirationDate: number | null;
  continuousMonitoringFrequency: "monthly" | "quarterly" | "annually";
}

export interface ATODocument {
  id: string;
  name: string;
  type: "ssp" | "sap" | "sar" | "poam" | "cis_workbook" | "pia" | "e_auth" | "fips_validation" | "incident_response" | "contingency_plan" | "config_mgmt";
  status: "draft" | "in_review" | "approved" | "expired";
  version: string;
  lastUpdated: number;
  required: boolean;
}

// ─── FedRAMP Moderate Baseline Controls ────────────────────────────────────

export const FEDRAMP_CONTROLS: FedRAMPControl[] = [
  // AC - Access Control (22 controls)
  { id: "AC-1", family: "Access Control", familyCode: "AC", title: "Policy and Procedures", description: "Develop, document, and disseminate access control policy and procedures", baseline: "moderate", status: "implemented", implementationStatus: "AC3 RBAC system enforces role-based access with documented policies", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "ISO27001", controlId: "A.9.1" }, { framework: "CMMC", controlId: "AC.L1-3.1.1" }], automationLevel: "full", testProcedure: "Review access control policy documentation; verify annual review cycle", expectedEvidence: ["Access control policy document", "Policy review records", "Distribution records"], poamRequired: false },
  { id: "AC-2", family: "Access Control", familyCode: "AC", title: "Account Management", description: "Manage system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts", baseline: "moderate", status: "implemented", implementationStatus: "OAuth-based account lifecycle with automated provisioning/deprovisioning", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.2" }, { framework: "ISO27001", controlId: "A.9.2" }, { framework: "CMMC", controlId: "AC.L1-3.1.1" }], automationLevel: "full", testProcedure: "Review account management procedures; verify automated provisioning", expectedEvidence: ["Account management procedures", "Provisioning logs", "Access reviews"], poamRequired: false },
  { id: "AC-3", family: "Access Control", familyCode: "AC", title: "Access Enforcement", description: "Enforce approved authorizations for logical access to information and system resources", baseline: "moderate", status: "implemented", implementationStatus: "tRPC protectedProcedure enforces role-based access at API level", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.3" }, { framework: "ISO27001", controlId: "A.9.4" }, { framework: "CMMC", controlId: "AC.L1-3.1.1" }], automationLevel: "full", testProcedure: "Attempt unauthorized access to protected procedures; verify denial", expectedEvidence: ["Access enforcement logs", "RBAC configuration", "Penetration test results"], poamRequired: false },
  { id: "AC-4", family: "Access Control", familyCode: "AC", title: "Information Flow Enforcement", description: "Enforce approved authorizations for controlling the flow of information within the system and between systems", baseline: "moderate", status: "implemented", implementationStatus: "Network segmentation between scan server, app server, and database", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.6" }, { framework: "ISO27001", controlId: "A.13.1" }, { framework: "CMMC", controlId: "AC.L2-3.1.3" }], automationLevel: "full", testProcedure: "Verify network flow rules; test cross-boundary data flow controls", expectedEvidence: ["Network flow diagrams", "Firewall rules", "Data flow documentation"], poamRequired: false },
  { id: "AC-5", family: "Access Control", familyCode: "AC", title: "Separation of Duties", description: "Separate duties of individuals to prevent malevolent activity", baseline: "moderate", status: "implemented", implementationStatus: "6-role RBAC (admin, operator, analyst, viewer, team_lead, auditor) with separation of duties", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.3" }, { framework: "ISO27001", controlId: "A.6.1" }, { framework: "CMMC", controlId: "AC.L2-3.1.4" }], automationLevel: "full", testProcedure: "Review role definitions; verify no single role can approve and execute", expectedEvidence: ["Role matrix", "Duty separation documentation", "Access review records"], poamRequired: false },
  { id: "AC-6", family: "Access Control", familyCode: "AC", title: "Least Privilege", description: "Employ the principle of least privilege, allowing only authorized accesses necessary for users", baseline: "moderate", status: "implemented", implementationStatus: "Role-based nav filtering, procedure-level authorization, admin-only gates", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.3" }, { framework: "ISO27001", controlId: "A.9.4" }, { framework: "CMMC", controlId: "AC.L2-3.1.5" }], automationLevel: "full", testProcedure: "Verify minimum access for each role; test privilege escalation", expectedEvidence: ["Privilege matrix", "Access audit logs", "Penetration test results"], poamRequired: false },
  { id: "AC-7", family: "Access Control", familyCode: "AC", title: "Unsuccessful Logon Attempts", description: "Enforce a limit of consecutive invalid logon attempts by a user", baseline: "moderate", status: "implemented", implementationStatus: "OAuth provider handles lockout after failed attempts", responsibleRole: "IT", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "CMMC", controlId: "AC.L2-3.1.8" }], automationLevel: "full", testProcedure: "Attempt multiple failed logins; verify account lockout", expectedEvidence: ["Lockout configuration", "Failed login logs"], poamRequired: false },
  { id: "AC-8", family: "Access Control", familyCode: "AC", title: "System Use Notification", description: "Display system use notification message or banner before granting access", baseline: "moderate", status: "partially_implemented", implementationStatus: "Login page shows terms of use; banner not yet on all system entry points", responsibleRole: "IT", priority: "P2", crossMappings: [{ framework: "CMMC", controlId: "AC.L2-3.1.9" }], automationLevel: "partial", testProcedure: "Verify banner display on all system entry points", expectedEvidence: ["Banner screenshots", "Terms of use document"], poamRequired: true },
  { id: "AC-11", family: "Access Control", familyCode: "AC", title: "Device Lock", description: "Prevent further access to the system by initiating a device lock after a period of inactivity", baseline: "moderate", status: "implemented", implementationStatus: "JWT session expiry with automatic logout after inactivity", responsibleRole: "IT", priority: "P3", crossMappings: [{ framework: "CMMC", controlId: "AC.L2-3.1.10" }], automationLevel: "full", testProcedure: "Verify session timeout; test automatic logout", expectedEvidence: ["Session configuration", "Timeout logs"], poamRequired: false },
  { id: "AC-14", family: "Access Control", familyCode: "AC", title: "Permitted Actions Without Identification", description: "Identify user actions that can be performed without identification or authentication", baseline: "moderate", status: "implemented", implementationStatus: "Only login page and public health check accessible without auth; all other routes require authentication", responsibleRole: "SecOps", priority: "P3", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }], automationLevel: "full", testProcedure: "Enumerate unauthenticated endpoints; verify minimal exposure", expectedEvidence: ["Public endpoint inventory", "Authentication configuration"], poamRequired: false },
  { id: "AC-17", family: "Access Control", familyCode: "AC", title: "Remote Access", description: "Establish and document usage restrictions, configuration requirements, and implementation guidance for remote access", baseline: "moderate", status: "implemented", implementationStatus: "All access is remote via HTTPS with OAuth; SSH to scan server uses key-based auth", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.7" }, { framework: "ISO27001", controlId: "A.9.4" }, { framework: "CMMC", controlId: "AC.L2-3.1.12" }], automationLevel: "full", testProcedure: "Review remote access methods; verify encryption and authentication", expectedEvidence: ["Remote access policy", "SSH key management records", "TLS configuration"], poamRequired: false },
  { id: "AC-20", family: "Access Control", familyCode: "AC", title: "Use of External Systems", description: "Establish terms and conditions for authorized individuals to access the system from external systems", baseline: "moderate", status: "partially_implemented", implementationStatus: "API integrations with external tools (Caldera, GoPhish, ZAP) documented but formal agreements pending", responsibleRole: "CISO", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC9.2" }, { framework: "CMMC", controlId: "AC.L2-3.1.20" }], automationLevel: "partial", testProcedure: "Review external system agreements; verify access controls", expectedEvidence: ["External system inventory", "Integration agreements", "Access logs"], poamRequired: true },

  // AU - Audit and Accountability (16 controls)
  { id: "AU-1", family: "Audit and Accountability", familyCode: "AU", title: "Policy and Procedures", description: "Develop, document, and disseminate audit and accountability policy and procedures", baseline: "moderate", status: "implemented", implementationStatus: "Comprehensive audit logging across all tRPC procedures and engagement actions", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC4.1" }, { framework: "ISO27001", controlId: "A.12.4" }, { framework: "CMMC", controlId: "AU.L2-3.3.1" }], automationLevel: "full", testProcedure: "Review audit policy; verify logging configuration", expectedEvidence: ["Audit policy document", "Logging configuration", "Log review procedures"], poamRequired: false },
  { id: "AU-2", family: "Audit and Accountability", familyCode: "AU", title: "Event Logging", description: "Identify events that the system is capable of logging in support of the audit function", baseline: "moderate", status: "implemented", implementationStatus: "All engagement actions, safety decisions, credential tests, and admin operations logged with timestamps", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.1" }, { framework: "ISO27001", controlId: "A.12.4" }, { framework: "CMMC", controlId: "AU.L2-3.3.1" }], automationLevel: "full", testProcedure: "Verify event types being logged; review log completeness", expectedEvidence: ["Audit event list", "Sample log entries", "Log completeness report"], poamRequired: false },
  { id: "AU-3", family: "Audit and Accountability", familyCode: "AU", title: "Content of Audit Records", description: "Ensure audit records contain information that establishes what event occurred, when, where, source, outcome, and identity", baseline: "moderate", status: "implemented", implementationStatus: "Structured JSON logs with timestamp, userId, action, resource, outcome, and IP address", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.2" }, { framework: "CMMC", controlId: "AU.L2-3.3.1" }], automationLevel: "full", testProcedure: "Review audit record format; verify required fields present", expectedEvidence: ["Log format specification", "Sample audit records"], poamRequired: false },
  { id: "AU-6", family: "Audit and Accountability", familyCode: "AU", title: "Audit Record Review, Analysis, and Reporting", description: "Review and analyze system audit records for indications of inappropriate or unusual activity", baseline: "moderate", status: "partially_implemented", implementationStatus: "Safety engine audit trail provides real-time review; automated anomaly detection planned", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC4.1" }, { framework: "ISO27001", controlId: "A.12.4" }, { framework: "CMMC", controlId: "AU.L2-3.3.2" }], automationLevel: "partial", testProcedure: "Review audit analysis procedures; verify regular review schedule", expectedEvidence: ["Audit review records", "Analysis reports", "Anomaly detection configuration"], poamRequired: true },
  { id: "AU-9", family: "Audit and Accountability", familyCode: "AU", title: "Protection of Audit Information", description: "Protect audit information and audit logging tools from unauthorized access, modification, and deletion", baseline: "moderate", status: "implemented", implementationStatus: "Audit logs stored in separate database tables with admin-only access; immutable append-only design", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.2" }, { framework: "CMMC", controlId: "AU.L2-3.3.8" }], automationLevel: "full", testProcedure: "Attempt to modify audit logs; verify protection mechanisms", expectedEvidence: ["Log protection configuration", "Access control for logs", "Integrity verification"], poamRequired: false },
  { id: "AU-12", family: "Audit and Accountability", familyCode: "AU", title: "Audit Record Generation", description: "Provide audit record generation capability for the events defined in AU-2", baseline: "moderate", status: "implemented", implementationStatus: "tRPC middleware generates audit records for all procedure calls automatically", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.1" }, { framework: "CMMC", controlId: "AU.L2-3.3.1" }], automationLevel: "full", testProcedure: "Verify audit generation for all defined events; test edge cases", expectedEvidence: ["Audit generation configuration", "Coverage report"], poamRequired: false },

  // CA - Assessment, Authorization, and Monitoring (9 controls)
  { id: "CA-1", family: "Assessment, Authorization, and Monitoring", familyCode: "CA", title: "Policy and Procedures", description: "Develop, document, and disseminate assessment, authorization, and monitoring policy", baseline: "moderate", status: "partially_implemented", implementationStatus: "AC3 provides continuous assessment via engagement pipeline; formal authorization policy in development", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC4.1" }, { framework: "CMMC", controlId: "CA.L2-3.12.1" }], automationLevel: "partial", testProcedure: "Review assessment policy; verify authorization procedures", expectedEvidence: ["Assessment policy", "Authorization procedures", "Monitoring plan"], poamRequired: true },
  { id: "CA-2", family: "Assessment, Authorization, and Monitoring", familyCode: "CA", title: "Control Assessments", description: "Assess the controls in the system to determine the extent to which the controls are implemented correctly", baseline: "moderate", status: "implemented", implementationStatus: "AC3 automated penetration testing validates security controls continuously", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC4.1" }, { framework: "ISO27001", controlId: "A.18.2" }, { framework: "CMMC", controlId: "CA.L2-3.12.1" }], automationLevel: "full", testProcedure: "Review assessment methodology; verify assessment scope and frequency", expectedEvidence: ["Assessment plan", "Assessment results", "Remediation tracking"], poamRequired: false },
  { id: "CA-5", family: "Assessment, Authorization, and Monitoring", familyCode: "CA", title: "Plan of Action and Milestones", description: "Develop a plan of action and milestones for the system to document planned remedial actions", baseline: "moderate", status: "implemented", implementationStatus: "POA&M tracking integrated into compliance dashboard with milestone management", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.1" }], automationLevel: "partial", testProcedure: "Review POA&M entries; verify milestone tracking and updates", expectedEvidence: ["POA&M spreadsheet", "Milestone completion records", "Status updates"], poamRequired: false },
  { id: "CA-7", family: "Assessment, Authorization, and Monitoring", familyCode: "CA", title: "Continuous Monitoring", description: "Develop a system-level continuous monitoring strategy and implement continuous monitoring program", baseline: "moderate", status: "implemented", implementationStatus: "AC3 engagement pipeline provides continuous security monitoring with automated scanning", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC4.1" }, { framework: "ISO27001", controlId: "A.12.4" }, { framework: "CMMC", controlId: "CA.L2-3.12.3" }], automationLevel: "full", testProcedure: "Review monitoring strategy; verify automated scanning frequency", expectedEvidence: ["Monitoring strategy document", "Scan schedules", "Monitoring reports"], poamRequired: false },

  // CM - Configuration Management (11 controls)
  { id: "CM-1", family: "Configuration Management", familyCode: "CM", title: "Policy and Procedures", description: "Develop, document, and disseminate configuration management policy and procedures", baseline: "moderate", status: "implemented", implementationStatus: "Git-based configuration management with CI/CD pipeline enforcement", responsibleRole: "CTO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC8.1" }, { framework: "ISO27001", controlId: "A.12.1" }, { framework: "CMMC", controlId: "CM.L2-3.4.1" }], automationLevel: "full", testProcedure: "Review CM policy; verify configuration baseline documentation", expectedEvidence: ["CM policy", "Baseline configurations", "Change management procedures"], poamRequired: false },
  { id: "CM-2", family: "Configuration Management", familyCode: "CM", title: "Baseline Configuration", description: "Develop, document, and maintain a current baseline configuration of the system", baseline: "moderate", status: "implemented", implementationStatus: "Infrastructure-as-code with version-controlled configuration baselines", responsibleRole: "CTO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC8.1" }, { framework: "CMMC", controlId: "CM.L2-3.4.1" }], automationLevel: "full", testProcedure: "Review baseline configuration; verify version control", expectedEvidence: ["Baseline documentation", "Version history", "Configuration files"], poamRequired: false },
  { id: "CM-3", family: "Configuration Management", familyCode: "CM", title: "Configuration Change Control", description: "Determine and document the types of changes to the system that are configuration-controlled", baseline: "moderate", status: "implemented", implementationStatus: "Git PR workflow with required reviews; deployment pipeline enforces change control", responsibleRole: "CTO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC8.1" }, { framework: "ISO27001", controlId: "A.12.1" }, { framework: "CMMC", controlId: "CM.L2-3.4.3" }], automationLevel: "full", testProcedure: "Review change control process; verify approval workflow", expectedEvidence: ["Change control procedures", "PR history", "Approval records"], poamRequired: false },
  { id: "CM-6", family: "Configuration Management", familyCode: "CM", title: "Configuration Settings", description: "Establish and document configuration settings for components employed within the system", baseline: "moderate", status: "implemented", implementationStatus: "Environment variables managed through secrets management; FIPS-validated crypto settings", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC5.2" }, { framework: "CMMC", controlId: "CM.L2-3.4.2" }], automationLevel: "full", testProcedure: "Review configuration settings; verify hardening baselines", expectedEvidence: ["Configuration standards", "Hardening checklist", "Compliance scan results"], poamRequired: false },
  { id: "CM-7", family: "Configuration Management", familyCode: "CM", title: "Least Functionality", description: "Configure the system to provide only mission-essential capabilities", baseline: "moderate", status: "implemented", implementationStatus: "Minimal container images; only required services enabled; unnecessary ports blocked", responsibleRole: "SecOps", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC5.2" }, { framework: "CMMC", controlId: "CM.L2-3.4.6" }], automationLevel: "full", testProcedure: "Review enabled services; verify minimal attack surface", expectedEvidence: ["Service inventory", "Port scan results", "Package list"], poamRequired: false },
  { id: "CM-8", family: "Configuration Management", familyCode: "CM", title: "System Component Inventory", description: "Develop and document an inventory of system components that accurately reflects the system", baseline: "moderate", status: "implemented", implementationStatus: "Asset discovery module maintains real-time inventory of all system components", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.5" }, { framework: "ISO27001", controlId: "A.8.1" }, { framework: "CMMC", controlId: "CM.L2-3.4.1" }], automationLevel: "full", testProcedure: "Review component inventory; verify completeness and accuracy", expectedEvidence: ["Component inventory", "Discovery scan results", "Update records"], poamRequired: false },

  // CP - Contingency Planning (10 controls)
  { id: "CP-1", family: "Contingency Planning", familyCode: "CP", title: "Policy and Procedures", description: "Develop, document, and disseminate contingency planning policy and procedures", baseline: "moderate", status: "partially_implemented", implementationStatus: "Database backup procedures documented; full contingency plan in development", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.5" }, { framework: "ISO27001", controlId: "A.17.1" }], automationLevel: "partial", testProcedure: "Review contingency plan; verify annual testing", expectedEvidence: ["Contingency plan", "Test results", "Recovery procedures"], poamRequired: true },
  { id: "CP-2", family: "Contingency Planning", familyCode: "CP", title: "Contingency Plan", description: "Develop a contingency plan for the system that identifies essential missions and business functions", baseline: "moderate", status: "partially_implemented", implementationStatus: "BIA completed via Auto-BIA module; contingency plan draft in progress", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.5" }, { framework: "ISO27001", controlId: "A.17.1" }], automationLevel: "partial", testProcedure: "Review contingency plan completeness; verify BIA alignment", expectedEvidence: ["Contingency plan", "BIA results", "Recovery time objectives"], poamRequired: true },
  { id: "CP-9", family: "Contingency Planning", familyCode: "CP", title: "System Backup", description: "Conduct backups of user-level and system-level information contained in the system", baseline: "moderate", status: "implemented", implementationStatus: "Automated database backups with S3 storage; configuration backups via Git", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.5" }, { framework: "ISO27001", controlId: "A.12.3" }], automationLevel: "full", testProcedure: "Verify backup schedule; test restoration procedures", expectedEvidence: ["Backup configuration", "Backup logs", "Restoration test results"], poamRequired: false },
  { id: "CP-10", family: "Contingency Planning", familyCode: "CP", title: "System Recovery and Reconstitution", description: "Provide for the recovery and reconstitution of the system to a known state", baseline: "moderate", status: "implemented", implementationStatus: "Checkpoint/rollback system enables rapid recovery to known-good states", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.5" }], automationLevel: "full", testProcedure: "Test recovery procedures; verify reconstitution timeline", expectedEvidence: ["Recovery procedures", "Test results", "Recovery time records"], poamRequired: false },

  // IA - Identification and Authentication (11 controls)
  { id: "IA-1", family: "Identification and Authentication", familyCode: "IA", title: "Policy and Procedures", description: "Develop, document, and disseminate identification and authentication policy and procedures", baseline: "moderate", status: "implemented", implementationStatus: "OAuth 2.0 with Manus identity provider; documented authentication policy", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "ISO27001", controlId: "A.9.1" }, { framework: "CMMC", controlId: "IA.L1-3.5.1" }], automationLevel: "full", testProcedure: "Review IA policy; verify authentication mechanisms", expectedEvidence: ["IA policy", "Authentication configuration", "MFA records"], poamRequired: false },
  { id: "IA-2", family: "Identification and Authentication", familyCode: "IA", title: "Identification and Authentication (Organizational Users)", description: "Uniquely identify and authenticate organizational users", baseline: "moderate", status: "implemented", implementationStatus: "Unique user IDs via OAuth; session management with JWT tokens", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "ISO27001", controlId: "A.9.2" }, { framework: "CMMC", controlId: "IA.L1-3.5.1" }], automationLevel: "full", testProcedure: "Verify unique identification; test authentication flow", expectedEvidence: ["User directory", "Authentication logs", "MFA enrollment records"], poamRequired: false },
  { id: "IA-4", family: "Identification and Authentication", familyCode: "IA", title: "Identifier Management", description: "Manage system identifiers by receiving authorization, assigning, and preventing reuse", baseline: "moderate", status: "implemented", implementationStatus: "OAuth provider manages unique identifiers; no identifier reuse possible", responsibleRole: "IT", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC6.2" }, { framework: "CMMC", controlId: "IA.L1-3.5.1" }], automationLevel: "full", testProcedure: "Review identifier management; verify no reuse", expectedEvidence: ["Identifier management procedures", "User registry"], poamRequired: false },
  { id: "IA-5", family: "Identification and Authentication", familyCode: "IA", title: "Authenticator Management", description: "Manage system authenticators by verifying identity, establishing initial content, and ensuring secure distribution", baseline: "moderate", status: "implemented", implementationStatus: "OAuth tokens with secure rotation; SSH keys for scan server with documented management", responsibleRole: "IT", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "ISO27001", controlId: "A.9.3" }, { framework: "CMMC", controlId: "IA.L2-3.5.10" }], automationLevel: "full", testProcedure: "Review authenticator management; verify rotation policies", expectedEvidence: ["Authenticator management procedures", "Rotation records", "Key management logs"], poamRequired: false },
  { id: "IA-8", family: "Identification and Authentication", familyCode: "IA", title: "Identification and Authentication (Non-Organizational Users)", description: "Uniquely identify and authenticate non-organizational users", baseline: "moderate", status: "implemented", implementationStatus: "All external users authenticated via OAuth; no anonymous access to protected resources", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "CMMC", controlId: "IA.L1-3.5.2" }], automationLevel: "full", testProcedure: "Verify non-org user authentication; test access controls", expectedEvidence: ["Authentication configuration", "Access logs for external users"], poamRequired: false },

  // IR - Incident Response (8 controls)
  { id: "IR-1", family: "Incident Response", familyCode: "IR", title: "Policy and Procedures", description: "Develop, document, and disseminate incident response policy and procedures", baseline: "moderate", status: "partially_implemented", implementationStatus: "Bug report system with severity classification; formal IR plan in development", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.3" }, { framework: "ISO27001", controlId: "A.16.1" }, { framework: "CMMC", controlId: "IR.L2-3.6.1" }], automationLevel: "partial", testProcedure: "Review IR policy; verify response procedures", expectedEvidence: ["IR policy", "Response procedures", "Contact list"], poamRequired: true },
  { id: "IR-4", family: "Incident Response", familyCode: "IR", title: "Incident Handling", description: "Implement an incident handling capability for incidents that includes preparation, detection, analysis, containment, eradication, and recovery", baseline: "moderate", status: "partially_implemented", implementationStatus: "Automated threat detection via engagement pipeline; manual containment procedures", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.3" }, { framework: "ISO27001", controlId: "A.16.1" }, { framework: "CMMC", controlId: "IR.L2-3.6.2" }], automationLevel: "partial", testProcedure: "Review incident handling procedures; test detection capabilities", expectedEvidence: ["Incident handling procedures", "Detection configuration", "Incident logs"], poamRequired: true },
  { id: "IR-5", family: "Incident Response", familyCode: "IR", title: "Incident Monitoring", description: "Track and document system security incidents", baseline: "moderate", status: "implemented", implementationStatus: "Safety engine audit trail and bug report dashboard provide incident tracking", responsibleRole: "SecOps", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC7.3" }, { framework: "CMMC", controlId: "IR.L2-3.6.2" }], automationLevel: "full", testProcedure: "Review incident tracking system; verify documentation completeness", expectedEvidence: ["Incident tracking system", "Incident records", "Trend analysis"], poamRequired: false },
  { id: "IR-6", family: "Incident Response", familyCode: "IR", title: "Incident Reporting", description: "Require personnel to report suspected incidents to the organizational incident response capability", baseline: "moderate", status: "implemented", implementationStatus: "Bug report quick action available to all roles; owner notification on critical incidents", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.4" }, { framework: "CMMC", controlId: "IR.L2-3.6.2" }], automationLevel: "full", testProcedure: "Verify reporting mechanisms; test notification flow", expectedEvidence: ["Reporting procedures", "Notification configuration", "Report logs"], poamRequired: false },
  { id: "IR-8", family: "Incident Response", familyCode: "IR", title: "Incident Response Plan", description: "Develop an incident response plan that provides the organization with a roadmap for implementing its incident response capability", baseline: "moderate", status: "partially_implemented", implementationStatus: "Draft IR plan exists; needs formal approval and tabletop exercise validation", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.4" }, { framework: "ISO27001", controlId: "A.16.1" }], automationLevel: "manual", testProcedure: "Review IR plan; verify annual testing and updates", expectedEvidence: ["IR plan document", "Test results", "Lessons learned"], poamRequired: true },

  // PE - Physical and Environmental Protection (6 controls)
  { id: "PE-1", family: "Physical and Environmental Protection", familyCode: "PE", title: "Policy and Procedures", description: "Develop, document, and disseminate physical and environmental protection policy", baseline: "moderate", status: "implemented", implementationStatus: "Cloud-hosted infrastructure; physical security managed by cloud provider (AWS/DO)", responsibleRole: "Facilities", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.4" }, { framework: "ISO27001", controlId: "A.11.1" }], automationLevel: "manual", testProcedure: "Review cloud provider physical security certifications", expectedEvidence: ["Cloud provider SOC 2 report", "Physical security documentation"], poamRequired: false },
  { id: "PE-2", family: "Physical and Environmental Protection", familyCode: "PE", title: "Physical Access Authorizations", description: "Develop, approve, and maintain a list of individuals with authorized access to the facility", baseline: "moderate", status: "inherited", implementationStatus: "Inherited from cloud service provider (AWS/DigitalOcean)", responsibleRole: "Facilities", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC6.4" }], automationLevel: "manual", testProcedure: "Verify cloud provider authorization controls", expectedEvidence: ["Cloud provider compliance reports"], poamRequired: false },
  { id: "PE-6", family: "Physical and Environmental Protection", familyCode: "PE", title: "Monitoring Physical Access", description: "Monitor physical access to the facility where the system resides to detect and respond to physical security incidents", baseline: "moderate", status: "inherited", implementationStatus: "Inherited from cloud service provider", responsibleRole: "Facilities", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC6.4" }], automationLevel: "manual", testProcedure: "Review cloud provider monitoring capabilities", expectedEvidence: ["Cloud provider monitoring documentation"], poamRequired: false },

  // PL - Planning (4 controls)
  { id: "PL-1", family: "Planning", familyCode: "PL", title: "Policy and Procedures", description: "Develop, document, and disseminate planning policy and procedures", baseline: "moderate", status: "partially_implemented", implementationStatus: "System security plan draft exists; formal planning procedures in development", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.1" }], automationLevel: "manual", testProcedure: "Review planning policy; verify SSP completeness", expectedEvidence: ["Planning policy", "SSP document"], poamRequired: true },
  { id: "PL-2", family: "Planning", familyCode: "PL", title: "System Security and Privacy Plans", description: "Develop security and privacy plans for the system that describe the controls in place or planned", baseline: "moderate", status: "partially_implemented", implementationStatus: "SSP auto-generated from compliance dashboard data; needs formal review", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.1" }], automationLevel: "partial", testProcedure: "Review SSP; verify control descriptions match implementation", expectedEvidence: ["SSP document", "Control implementation descriptions"], poamRequired: true },

  // RA - Risk Assessment (5 controls)
  { id: "RA-1", family: "Risk Assessment", familyCode: "RA", title: "Policy and Procedures", description: "Develop, document, and disseminate risk assessment policy and procedures", baseline: "moderate", status: "implemented", implementationStatus: "CARVER+Shock scoring and CVSS pipeline provide automated risk assessment", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.1" }, { framework: "ISO27001", controlId: "A.8.2" }, { framework: "CMMC", controlId: "RA.L2-3.11.1" }], automationLevel: "full", testProcedure: "Review risk assessment methodology; verify scoring accuracy", expectedEvidence: ["Risk assessment policy", "CARVER+Shock methodology", "Assessment results"], poamRequired: false },
  { id: "RA-3", family: "Risk Assessment", familyCode: "RA", title: "Risk Assessment", description: "Conduct an assessment of risk including the likelihood and magnitude of harm", baseline: "moderate", status: "implemented", implementationStatus: "Automated risk scoring via engagement pipeline with CARVER+Shock and CVSS", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.2" }, { framework: "ISO27001", controlId: "A.8.2" }, { framework: "CMMC", controlId: "RA.L2-3.11.1" }], automationLevel: "full", testProcedure: "Review risk assessment results; verify scoring methodology", expectedEvidence: ["Risk assessment report", "Scoring methodology", "Risk register"], poamRequired: false },
  { id: "RA-5", family: "Risk Assessment", familyCode: "RA", title: "Vulnerability Monitoring and Scanning", description: "Monitor and scan for vulnerabilities in the system and hosted applications", baseline: "moderate", status: "implemented", implementationStatus: "Continuous vulnerability scanning via nuclei, ZAP, nmap with corroboration engine", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC3.2" }, { framework: "ISO27001", controlId: "A.12.6" }, { framework: "CMMC", controlId: "RA.L2-3.11.2" }], automationLevel: "full", testProcedure: "Review scanning schedule; verify vulnerability remediation tracking", expectedEvidence: ["Scan results", "Remediation tracking", "Scan schedule"], poamRequired: false },

  // SA - System and Services Acquisition (8 controls)
  { id: "SA-1", family: "System and Services Acquisition", familyCode: "SA", title: "Policy and Procedures", description: "Develop, document, and disseminate system and services acquisition policy", baseline: "moderate", status: "partially_implemented", implementationStatus: "Vendor security assessment process exists; formal acquisition policy in development", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC9.2" }], automationLevel: "manual", testProcedure: "Review acquisition policy; verify vendor assessment process", expectedEvidence: ["Acquisition policy", "Vendor assessment records"], poamRequired: true },
  { id: "SA-4", family: "System and Services Acquisition", familyCode: "SA", title: "Acquisition Process", description: "Include security and privacy requirements in the acquisition process for the system", baseline: "moderate", status: "partially_implemented", implementationStatus: "Security requirements included in vendor evaluations; formal contract language being standardized", responsibleRole: "Procurement", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC9.2" }, { framework: "ISO27001", controlId: "A.15.1" }], automationLevel: "manual", testProcedure: "Review acquisition contracts; verify security requirements", expectedEvidence: ["Contract templates", "Security requirements", "Vendor assessments"], poamRequired: true },
  { id: "SA-9", family: "System and Services Acquisition", familyCode: "SA", title: "External System Services", description: "Require that providers of external system services comply with organizational security requirements", baseline: "moderate", status: "partially_implemented", implementationStatus: "External service integrations (Caldera, GoPhish, ZAP) documented; compliance verification in progress", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC9.2" }, { framework: "ISO27001", controlId: "A.15.1" }], automationLevel: "partial", testProcedure: "Review external service agreements; verify compliance", expectedEvidence: ["Service agreements", "Compliance certifications", "Security assessments"], poamRequired: true },

  // SC - System and Communications Protection (13 controls)
  { id: "SC-1", family: "System and Communications Protection", familyCode: "SC", title: "Policy and Procedures", description: "Develop, document, and disseminate system and communications protection policy", baseline: "moderate", status: "implemented", implementationStatus: "TLS 1.3 enforced; FIPS-validated cryptographic modules documented", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.7" }, { framework: "ISO27001", controlId: "A.13.1" }, { framework: "CMMC", controlId: "SC.L1-3.13.1" }], automationLevel: "full", testProcedure: "Review SC policy; verify encryption configuration", expectedEvidence: ["SC policy", "TLS configuration", "Crypto module documentation"], poamRequired: false },
  { id: "SC-7", family: "System and Communications Protection", familyCode: "SC", title: "Boundary Protection", description: "Monitor and control communications at the external managed interfaces to the system", baseline: "moderate", status: "implemented", implementationStatus: "WAF, firewall rules, and network segmentation between components", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.6" }, { framework: "ISO27001", controlId: "A.13.1" }, { framework: "CMMC", controlId: "SC.L1-3.13.1" }], automationLevel: "full", testProcedure: "Review boundary protection; test firewall rules", expectedEvidence: ["Network diagram", "Firewall rules", "WAF configuration"], poamRequired: false },
  { id: "SC-8", family: "System and Communications Protection", familyCode: "SC", title: "Transmission Confidentiality and Integrity", description: "Protect the confidentiality and integrity of transmitted information", baseline: "moderate", status: "implemented", implementationStatus: "TLS 1.3 for all web traffic; SSH for scan server communication", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.7" }, { framework: "ISO27001", controlId: "A.13.2" }, { framework: "CMMC", controlId: "SC.L2-3.13.8" }], automationLevel: "full", testProcedure: "Verify TLS configuration; test for weak ciphers", expectedEvidence: ["TLS scan results", "Cipher suite configuration", "Certificate records"], poamRequired: false },
  { id: "SC-12", family: "System and Communications Protection", familyCode: "SC", title: "Cryptographic Key Establishment and Management", description: "Establish and manage cryptographic keys when cryptography is employed within the system", baseline: "moderate", status: "implemented", implementationStatus: "JWT secrets managed via environment variables; SSH keys rotated; FIPS compliance module tracks crypto", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.1" }, { framework: "ISO27001", controlId: "A.10.1" }, { framework: "CMMC", controlId: "SC.L2-3.13.10" }], automationLevel: "full", testProcedure: "Review key management procedures; verify rotation schedule", expectedEvidence: ["Key management procedures", "Rotation records", "FIPS validation certificates"], poamRequired: false },
  { id: "SC-13", family: "System and Communications Protection", familyCode: "SC", title: "Cryptographic Protection", description: "Implement FIPS-validated or NSA-approved cryptography", baseline: "moderate", status: "implemented", implementationStatus: "FIPS compliance module validates all cryptographic operations; FIPS 140-2/3 tracking", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.7" }, { framework: "CMMC", controlId: "SC.L2-3.13.11" }], automationLevel: "full", testProcedure: "Verify FIPS-validated modules; test cryptographic operations", expectedEvidence: ["FIPS validation certificates", "Crypto module inventory", "Test results"], poamRequired: false },
  { id: "SC-28", family: "System and Communications Protection", familyCode: "SC", title: "Protection of Information at Rest", description: "Protect the confidentiality and integrity of information at rest", baseline: "moderate", status: "implemented", implementationStatus: "Database encryption at rest via TiDB; S3 server-side encryption for stored files", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.7" }, { framework: "ISO27001", controlId: "A.10.1" }, { framework: "CMMC", controlId: "SC.L2-3.13.16" }], automationLevel: "full", testProcedure: "Verify encryption at rest configuration; test data protection", expectedEvidence: ["Encryption configuration", "Key management records", "Compliance scan results"], poamRequired: false },

  // SI - System and Information Integrity (7 controls)
  { id: "SI-1", family: "System and Information Integrity", familyCode: "SI", title: "Policy and Procedures", description: "Develop, document, and disseminate system and information integrity policy", baseline: "moderate", status: "implemented", implementationStatus: "Automated vulnerability scanning, patch management tracking, and integrity monitoring", responsibleRole: "CISO", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC5.2" }, { framework: "ISO27001", controlId: "A.12.6" }, { framework: "CMMC", controlId: "SI.L1-3.14.1" }], automationLevel: "full", testProcedure: "Review SI policy; verify integrity monitoring", expectedEvidence: ["SI policy", "Monitoring configuration", "Integrity check results"], poamRequired: false },
  { id: "SI-2", family: "System and Information Integrity", familyCode: "SI", title: "Flaw Remediation", description: "Identify, report, and correct system flaws", baseline: "moderate", status: "implemented", implementationStatus: "Vulnerability remediation tracking via engagement pipeline; automated patch verification", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.1" }, { framework: "ISO27001", controlId: "A.12.6" }, { framework: "CMMC", controlId: "SI.L1-3.14.1" }], automationLevel: "full", testProcedure: "Review remediation process; verify patch timelines", expectedEvidence: ["Remediation records", "Patch logs", "Verification scans"], poamRequired: false },
  { id: "SI-3", family: "System and Information Integrity", familyCode: "SI", title: "Malicious Code Protection", description: "Implement malicious code protection mechanisms at system entry and exit points", baseline: "moderate", status: "implemented", implementationStatus: "File upload scanning; input validation on all tRPC procedures; WAF protection", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC6.8" }, { framework: "ISO27001", controlId: "A.12.2" }, { framework: "CMMC", controlId: "SI.L1-3.14.2" }], automationLevel: "full", testProcedure: "Verify malware protection; test detection capabilities", expectedEvidence: ["Protection configuration", "Detection logs", "Update records"], poamRequired: false },
  { id: "SI-4", family: "System and Information Integrity", familyCode: "SI", title: "System Monitoring", description: "Monitor the system to detect attacks and indicators of potential attacks", baseline: "moderate", status: "implemented", implementationStatus: "Real-time engagement monitoring; safety engine audit trail; threat actor mapping", responsibleRole: "SecOps", priority: "P1", crossMappings: [{ framework: "SOC2", controlId: "CC7.1" }, { framework: "ISO27001", controlId: "A.12.4" }, { framework: "CMMC", controlId: "SI.L2-3.14.6" }], automationLevel: "full", testProcedure: "Review monitoring configuration; verify alert thresholds", expectedEvidence: ["Monitoring configuration", "Alert records", "Analysis reports"], poamRequired: false },
  { id: "SI-5", family: "System and Information Integrity", familyCode: "SI", title: "Security Alerts, Advisories, and Directives", description: "Receive system security alerts, advisories, and directives from external organizations", baseline: "moderate", status: "implemented", implementationStatus: "CISA KEV feed integration; CVE monitoring; threat intelligence feeds from multiple sources", responsibleRole: "SecOps", priority: "P2", crossMappings: [{ framework: "SOC2", controlId: "CC7.1" }, { framework: "CMMC", controlId: "SI.L2-3.14.3" }], automationLevel: "full", testProcedure: "Verify alert feed integration; review response procedures", expectedEvidence: ["Feed configuration", "Alert processing records", "Response procedures"], poamRequired: false },
];

// ─── POA&M Entries ──────────────────────────────────────────────────────────

export function generateFedRAMPPOAM(): POAMEntry[] {
  const now = Date.now();
  const controls = FEDRAMP_CONTROLS.filter(c => c.poamRequired);
  return controls.map((c, i) => ({
    id: `POAM-${String(i + 1).padStart(3, "0")}`,
    controlId: c.id,
    weakness: `${c.title}: ${c.implementationStatus.split(";").pop()?.trim() || "Implementation incomplete"}`,
    severity: c.priority === "P1" ? "high" as const : c.priority === "P2" ? "moderate" as const : "low" as const,
    scheduledCompletionDate: now + (30 + i * 15) * 24 * 60 * 60 * 1000,
    milestones: [
      { description: "Draft remediation plan", dueDate: now + 7 * 24 * 60 * 60 * 1000, status: "complete" as const },
      { description: "Implement technical controls", dueDate: now + (15 + i * 10) * 24 * 60 * 60 * 1000, status: "in_progress" as const },
      { description: "Validate and document evidence", dueDate: now + (25 + i * 15) * 24 * 60 * 60 * 1000, status: "not_started" as const },
    ],
    responsiblePOC: c.responsibleRole,
    resources: "Security engineering team + external 3PAO assessor",
    vendorDependency: c.id.startsWith("SA") || c.id.startsWith("PE"),
    status: "in_progress" as const,
    riskRating: c.priority === "P1" ? 15 : c.priority === "P2" ? 10 : 5,
  }));
}

// ─── ATO Package Status ─────────────────────────────────────────────────────

export function generateATOPackageStatus(): ATOPackageStatus {
  const now = Date.now();
  return {
    systemName: "AC3 Offensive Security Platform",
    systemId: "AC3-FRM-001",
    impactLevel: "moderate",
    authorizationType: "initial",
    status: "pre_assessment",
    assessor3PAO: null,
    authorizedDate: null,
    expirationDate: null,
    continuousMonitoringFrequency: "monthly",
    documents: [
      { id: "doc-ssp", name: "System Security Plan (SSP)", type: "ssp", status: "draft", version: "0.9", lastUpdated: now - 10 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-sap", name: "Security Assessment Plan (SAP)", type: "sap", status: "draft", version: "0.5", lastUpdated: now - 20 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-sar", name: "Security Assessment Report (SAR)", type: "sar", status: "draft", version: "0.1", lastUpdated: now - 30 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-poam", name: "Plan of Action and Milestones (POA&M)", type: "poam", status: "in_review", version: "1.2", lastUpdated: now - 3 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-cis", name: "CIS Workbook", type: "cis_workbook", status: "draft", version: "0.3", lastUpdated: now - 15 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-pia", name: "Privacy Impact Assessment (PIA)", type: "pia", status: "draft", version: "0.2", lastUpdated: now - 25 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-eauth", name: "E-Authentication Risk Assessment", type: "e_auth", status: "approved", version: "1.0", lastUpdated: now - 45 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-fips", name: "FIPS 140 Validation", type: "fips_validation", status: "in_review", version: "1.1", lastUpdated: now - 5 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-ir", name: "Incident Response Plan", type: "incident_response", status: "draft", version: "0.8", lastUpdated: now - 12 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-cp", name: "Contingency Plan", type: "contingency_plan", status: "draft", version: "0.6", lastUpdated: now - 18 * 24 * 60 * 60 * 1000, required: true },
      { id: "doc-cm", name: "Configuration Management Plan", type: "config_mgmt", status: "approved", version: "1.0", lastUpdated: now - 40 * 24 * 60 * 60 * 1000, required: true },
    ],
  };
}

// ─── FedRAMP Family Summary ─────────────────────────────────────────────────

export function getFedRAMPFamilySummary() {
  const families = new Map<string, { code: string; total: number; implemented: number; partial: number; planned: number; notImpl: number; inherited: number; na: number }>();
  for (const c of FEDRAMP_CONTROLS) {
    if (!families.has(c.family)) {
      families.set(c.family, { code: c.familyCode, total: 0, implemented: 0, partial: 0, planned: 0, notImpl: 0, inherited: 0, na: 0 });
    }
    const f = families.get(c.family)!;
    f.total++;
    if (c.status === "implemented") f.implemented++;
    else if (c.status === "partially_implemented") f.partial++;
    else if (c.status === "planned") f.planned++;
    else if (c.status === "not_implemented") f.notImpl++;
    else if (c.status === "inherited") f.inherited++;
    else if (c.status === "not_applicable") f.na++;
  }
  return Array.from(families.entries()).map(([name, data]) => ({ name, ...data }));
}
